import Link from "next/link";
import { redirect } from "next/navigation";
import { requireActiveOwnerOrganizationContext } from "@/lib/auth/organization-context";
import { IntegrationGuideButton } from "../../integration-guide-button";
import { bindCustomerProjectResource, checkCustomerConnectionHealth, disconnectCustomerConnection, verifyCustomerTokenConnection } from "../../customer-actions";
import { ConnectionSetupAgentPanel } from "../../connection-setup-agent-panel";
import { getCanonicalSetupPlan } from "@/lib/integrations/connections/setup-plans";
import { createExecutionServiceClient } from "@/lib/integrations/service-runner";
import { getConnectionSetupBrowserView } from "@/lib/integrations/connection-setup-agent";

export const dynamic = "force-dynamic";

type ProviderHelp={title:string;intro:string;credentialLabel:string;credentialHelp:string;scopes:string};
type OAuthHelp={action:string;button:string;copy:string};

const providerHelp:Record<string,ProviderHelp>={
  github:{title:"Connect GitHub",intro:"Use a GitHub access token for this validation flow. RYTHM stores it in Vault; it is not exposed to Agents or company records.",credentialLabel:"GitHub access token",credentialHelp:"Create a fine-grained token in GitHub for the organization/repositories you want RYTHM to access. Start read-only for validation.",scopes:"repo:read read:user"},
  cloudflare:{title:"Connect Cloudflare",intro:"Use a restricted Cloudflare API token for the account or zone you want this company to manage.",credentialLabel:"Cloudflare API token",credentialHelp:"Create a token with only the resources and permissions needed by this company.",scopes:"read"},
  vercel:{title:"Connect Vercel",intro:"Use a restricted Vercel token for the team/account that owns the intended deployment project.",credentialLabel:"Vercel access token",credentialHelp:"Create a provider token for the intended Vercel account. Project selection and production deployment authority are handled separately.",scopes:"deployment.read"},
  supabase:{title:"Connect Supabase",intro:"Use a restricted Supabase credential for the intended account or project. Project/resource selection remains separate from the company connection.",credentialLabel:"Supabase access token",credentialHelp:"Use a provider-issued token with the minimum access required for discovery/validation. Database writes require separate governed capability.",scopes:"project.read"},
  ahrefs:{title:"Connect Ahrefs",intro:"Connect SEO research data when the company or client has an Ahrefs subscription.",credentialLabel:"Ahrefs API credential",credentialHelp:"Use the provider-issued API credential for the intended account. This service is normally supporting evidence rather than a universal project blocker.",scopes:"read"},
  semrush:{title:"Connect Semrush",intro:"Connect SEO and market-research data when available to the company or client.",credentialLabel:"Semrush API credential",credentialHelp:"Use the provider-issued credential for the intended account and keep access read-only for research by default.",scopes:"read"},
};

const oauthHelp:Record<string,OAuthHelp>={
  google_workspace:{action:"/api/integrations/google-workspace/connect",button:"Connect Google Workspace in new tab",copy:"Google authorization opens in a separate tab. Keep this RYTHM page and the guide open while you complete sign-in and consent."},
  google_search_console:{action:"/api/integrations/google-search-console/connect",button:"Connect Google Search Console in new tab",copy:"Google authorization opens in a separate tab and requests read-only Search Console access. RYTHM verifies the properties available to the authorized account before marking the connection Connected."},
  google_analytics:{action:"/api/integrations/google-analytics/connect",button:"Connect Google Analytics 4 in new tab",copy:"Google authorization opens in a separate tab and requests read-only Analytics access. RYTHM discovers GA4 properties before marking the connection Connected."},
  microsoft_365:{action:"/api/integrations/microsoft-365/connect",button:"Connect Microsoft 365 in new tab",copy:"Microsoft authorization opens in a separate tab. The first connection verifies the account through Microsoft Graph with a minimal read-only identity scope."},
};

function stateLabel(status:string){return status==="connected"?"Connected":status==="verifying"?"Verifying":status==="reauth_required"?"Reauthentication required":["error","needs_attention"].includes(status)?"Needs attention":status==="disconnected"?"Disconnected":"Setup required";}

export default async function IntegrationSetupPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{message?:string;error?:string;project?:string;agentAnswer?:string;live?:string}>}){
  const {id}=await params;const query=await searchParams;const context=await requireActiveOwnerOrganizationContext();
  const {data:integration}=await context.supabase.from("organization_integrations").select("id,provider_key,display_name,status,granted_scopes,last_verified_at,last_health_check_at,last_error_at,last_error_message").eq("id",id).eq("organization_id",context.organizationId).maybeSingle();
  if(!integration) redirect("/integrations?error=Connection%20not%20found.");
  const {data:provider}=await context.supabase.from("integration_providers").select("display_name,supports_oauth,supports_token,ai_setup_enabled,ai_setup_rollout").eq("provider_key",integration.provider_key).maybeSingle();
  const help=providerHelp[integration.provider_key]??{title:`Connect ${provider?.display_name??integration.provider_key}`,intro:"Finish the secure account connection. RYTHM keeps technical detail out of normal Agent workflows while preserving real verification.",credentialLabel:"Secure access credential",credentialHelp:"Use a provider-issued credential with the minimum permissions needed for this company.",scopes:"read"};
  const oauth=oauthHelp[integration.provider_key];const useToken=Boolean(providerHelp[integration.provider_key]&&provider?.supports_token);const backHref=query.project?`/integrations?project=${encodeURIComponent(query.project)}`:"/integrations";
  const [resourcesResult,capabilitiesResult,bindingResult,sessionResult]=await Promise.all([
    context.supabase.from("integration_resources").select("id,resource_type,resource_id,resource_name,last_verified_at").eq("integration_id",id).eq("organization_id",context.organizationId).eq("available",true).order("resource_name"),
    context.supabase.from("integration_capabilities").select("capability_key,description,risk_level,default_approval_mode").eq("provider_key",integration.provider_key).eq("enabled",true).order("risk_level"),
    query.project?context.supabase.from("project_connection_bindings").select("id,resource_ref,display_name,capabilities,binding_status,verified_at").eq("project_id",query.project).eq("integration_id",id).eq("organization_id",context.organizationId):Promise.resolve({data:[]}),
    context.supabase.from("integration_setup_sessions").select("id,session_status,current_step,control_mode,requires_user_action,user_action_type,human_takeover_reason,started_at,updated_at,metadata").eq("organization_id",context.organizationId).eq("connection_id",id).eq("automation_mode","ai").order("created_at",{ascending:false}).limit(1).maybeSingle(),
  ]);
  const resources=resourcesResult.data??[];const capabilities=capabilitiesResult.data??[];const bindings=bindingResult.data??[];const session=sessionResult.data??null;
  const plan=getCanonicalSetupPlan(integration.provider_key);let events:any[]=[];let browser=null;
  if(session){try{const service=createExecutionServiceClient();const eventResult=await service.from("connection_setup_session_events").select("id,event_type,safe_message,created_at").eq("organization_id",context.organizationId).eq("session_id",session.id).order("created_at",{ascending:false}).limit(12);events=eventResult.data??[];browser=await getConnectionSetupBrowserView(service,{organizationId:context.organizationId,sessionId:session.id});}catch{/* fail closed: setup page must remain usable */}}
  return <main className="command-shell"><span hidden data-integration-guide-provider={integration.provider_key}/><header className="command-header"><div><p className="eyebrow">CONNECTION SETUP</p><h1>{help.title}</h1><p className="subtitle">{help.intro}</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><IntegrationGuideButton providerKey={integration.provider_key} label="Guide me"/><Link className="secondary-button" href={backHref}>Back to connections</Link></div></header>
    {query.message?<p className="form-success">{query.message}</p>:null}{query.error?<p className="form-error">{query.error}</p>:null}
    <ConnectionSetupAgentPanel integrationId={integration.id} projectId={query.project} providerName={provider?.display_name??integration.provider_key} providerKey={integration.provider_key} plan={plan} aiEnabled={Boolean(provider?.ai_setup_enabled)} rollout={String(provider?.ai_setup_rollout??"off")} session={session} events={events} browser={browser} agentAnswer={query.agentAnswer} openLive={query.live==="1"}/>
    <section className="panel" style={{maxWidth:860,marginTop:18}}><div className="panel-heading"><div><p className="label">MANUAL · GUIDE ME</p><h2>{integration.display_name}</h2></div><span data-guide-target="verify" className={integration.status==="connected"?"state-active":"state-paused"}>{stateLabel(integration.status)}</span></div>
      {integration.status!=="connected"?(oauth?<div data-guide-target="credential"><p>{oauth.copy}</p><form action={oauth.action} method="post" target="_blank" rel="opener" style={{marginTop:16}}><input type="hidden" name="integrationId" value={integration.id}/>{query.project?<input type="hidden" name="projectId" value={query.project}/>:null}{integration.provider_key==="google_workspace"?<input type="hidden" name="displayName" value={integration.display_name}/>:null}<button data-guide-target="start-setup" className="primary-button" type="submit">{oauth.button}</button></form><p className="integration-security-note">The external provider must complete authorization successfully before RYTHM changes this status to <strong>Connected</strong>. A local connection record alone is not a successful integration.</p></div>:useToken?<form action={verifyCustomerTokenConnection} className="stacked-form"><input type="hidden" name="integrationId" value={integration.id}/>{query.project?<input type="hidden" name="projectId" value={query.project}/>:null}<label>{help.credentialLabel}<input data-guide-target="credential" type="password" name="secret" autoComplete="off" required placeholder="Paste the provider-issued token"/></label><p className="integration-security-note">{help.credentialHelp} The token is verified against the provider before the connection can become Connected.</p><button data-guide-target="start-setup" className="primary-button" type="submit">Verify & connect securely</button></form>:<div data-guide-target="credential"><p>This service has a setup profile, but its customer authorization adapter is not enabled in this release.</p><p className="integration-security-note">The service remains <strong>Setup required</strong>. RYTHM will not display a successful connection message until real provider verification exists.</p></div>):<div><p>This company connection has verified provider access.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><form action={checkCustomerConnectionHealth}><input type="hidden" name="integrationId" value={integration.id}/>{query.project?<input type="hidden" name="projectId" value={query.project}/>:null}<button className="secondary-button" type="submit">Check connection health</button></form><form action={disconnectCustomerConnection}><input type="hidden" name="integrationId" value={integration.id}/>{query.project?<input type="hidden" name="projectId" value={query.project}/>:null}<button className="secondary-button" type="submit">Disconnect</button></form></div></div>}
      <div className="security-note"><strong>Connection health</strong><span>Last verified: {integration.last_verified_at?new Date(integration.last_verified_at).toLocaleString():"Never"} · Last health check: {integration.last_health_check_at?new Date(integration.last_health_check_at).toLocaleString():"Never"} · Last error: {integration.last_error_at?(integration.last_error_message||new Date(integration.last_error_at).toLocaleString()):"None"}</span></div>
    </section>
    {integration.status==="connected"&&query.project?<section className="panel" style={{maxWidth:860,marginTop:18}}><div className="panel-heading"><div><p className="label">PROJECT RESOURCE BINDING</p><h2>Select the exact resource</h2></div><span className="pill">{resources.length} discovered</span></div>{resources.length?<form action={bindCustomerProjectResource} className="stacked-form"><input type="hidden" name="integrationId" value={integration.id}/><input type="hidden" name="projectId" value={query.project}/><label>Provider resource<select name="resource" required defaultValue=""><option value="" disabled>Select a verified resource</option>{resources.map(resource=><option value={resource.id} key={resource.id}>{resource.resource_name}</option>)}</select></label><fieldset><legend>Project capabilities</legend><div className="compact-list">{capabilities.map(capability=><label key={capability.capability_key} style={{display:"flex",gap:10,alignItems:"flex-start"}}><input type="checkbox" name="capabilities" value={capability.capability_key}/><span><strong>{capability.capability_key}</strong><br/>{capability.description} · {capability.default_approval_mode}</span></label>)}</div></fieldset><button className="primary-button" type="submit">Bind verified resource to project</button></form>:<p className="security-note">Authorization was verified, but the provider returned no selectable resources. Confirm that this account can access at least one resource, then reconnect.</p>}{bindings.length?<div className="compact-list" style={{marginTop:16}}>{bindings.map(binding=><div key={binding.id}><strong>{binding.display_name}</strong><span>{binding.binding_status} · {binding.resource_ref}</span></div>)}</div>:null}</section>:null}
  </main>;
}
