import { getCanonicalSetupPlan } from "@/lib/integrations/connections/setup-plans";

export type IntegrationGuideDefinition={title:string;intro:string;steps:string[];note:string;targets:string[]};
export const commonGuideTargets=['[data-guide-target="provider"]','[data-guide-target="display-name"]','[data-guide-target="start-setup"]','[data-guide-target="credential"]','[data-guide-target="verify"]'];

const LEGACY:Record<string,Omit<IntegrationGuideDefinition,"targets">>={
  google_drive:{title:"Google Drive",intro:"Connect the company or client Drive used for project documents and deliverables.",steps:["Choose Google Drive and name the connection.","Start secure Google authorization.","Sign in with the intended company/client account.","Choose only the folder or shared drive the project requires.","Verify access and bind that resource to the project."],note:"Prefer folder/resource-level scope rather than broad access to an entire Drive."},
  google_ads:{title:"Google Ads",intro:"Connect the agency or client-owned Google Ads account. Campaign authority stays separate from spending authority.",steps:["Choose Google Ads and name the client/agency connection.","Start secure Google authorization.","Sign in to the correct Google account and select the intended Ads account.","Verify account access in RYTHM.","Bind it to the project; publishing and budget capabilities are granted separately."],note:"Budget/spend changes remain Human-controlled unless an explicit policy says otherwise."},
  meta_marketing:{title:"Meta / Facebook / Instagram",intro:"Connect the Business Portfolio used for advertising or publishing.",steps:["Choose Meta Marketing and name the client connection.","Start secure setup.","Sign in to Meta and select the correct business assets.","Confirm the exact Page/Ad Account resources for the project.","Verify the connection before enabling publishing or campaign actions."],note:"Publishing and campaign actions remain governed; spending requires Human approval."},
  youtube:{title:"YouTube",intro:"Connect the company or client YouTube channel through Google authorization.",steps:["Choose YouTube and name the channel connection.","Start secure setup.","Select the correct Google/YouTube account.","Confirm the intended channel/resource.","Verify the connection before uploads or publishing are enabled."],note:"Video publishing is a governed external action."},
  tiktok_business:{title:"TikTok for Business",intro:"Connect the intended advertiser or publishing account.",steps:["Choose TikTok for Business and name the client connection.","Start secure setup.","Sign in and choose the correct business account.","Confirm the intended advertiser/publishing resource.","Verify before campaign or content actions are enabled."],note:"Budget changes remain Human-controlled."},
  linkedin_marketing:{title:"LinkedIn Marketing",intro:"Connect the client Organization/Page and advertising account.",steps:["Choose LinkedIn Marketing and name the client connection.","Start secure setup.","Sign in and select the relevant organization/account.","Confirm the exact Page or Ads resource for this project.","Verify before campaign or Page publishing is enabled."],note:"RYTHM separates publishing authority from financial authority."},
  website_cms:{title:"Website / CMS",intro:"Connect the CMS or website administration surface required by the project.",steps:["Choose Website / CMS and name the site connection.","Create the company connection.","Use the provider's OAuth flow or a restricted application credential when prompted.","Limit access to the intended site/environment.","Verify access before allowing content or production changes."],note:"Content drafts and production publishing should be separate capabilities when the provider supports them."},
  figma:{title:"Figma",intro:"Connect the design workspace or file required for the project.",steps:["Choose Figma and name the client/workspace connection.","Start secure authorization.","Select the intended workspace/team.","Confirm only the files/projects needed for this work.","Verify and bind the selected design resource to the project."],note:"Design access should not implicitly grant unrelated workspace access."},
  ahrefs:{title:"Ahrefs",intro:"Connect SEO research data when the project or plan includes an Ahrefs subscription.",steps:["Choose Ahrefs and name the connection.","Create the connection and continue setup.","Use the provider-issued API credential for the intended account.","Store it securely and verify access.","Bind the relevant site/project to the RYTHM project."],note:"Ahrefs is usually optional/recommended evidence; absence should not block unrelated project work."},
  semrush:{title:"Semrush",intro:"Connect SEO/market research data when the client or company has access.",steps:["Choose Semrush and name the connection.","Create the connection and continue setup.","Use the provider-issued credential for the intended account.","Store it securely and verify access.","Bind only the relevant domain/project to the RYTHM project."],note:"Semrush is normally optional/recommended, not a universal blocker."},
};

const DEFAULT:Omit<IntegrationGuideDefinition,"targets">={title:"Connect a company service",intro:"RYTHM keeps connection setup understandable while preserving real provider verification and least-privilege access.",steps:["Choose the service your company or project uses.","Give the connection a name you will recognize.","Start secure setup.","Follow the provider authorization or restricted credential flow.","Return to RYTHM, verify the connection, then bind only the resource needed by the project."],note:"Passwords are never requested. Connection, resource scope and action permissions are separate layers."};

export function getIntegrationGuideDefinition(providerKey:string):IntegrationGuideDefinition{
  const plan=getCanonicalSetupPlan(providerKey);
  if(plan){return {title:plan.title,intro:plan.intro,steps:plan.steps.map(step=>step.description),note:plan.securityNote,targets:commonGuideTargets};}
  const guide=LEGACY[providerKey]??DEFAULT;return {...guide,targets:commonGuideTargets};
}
