"use client";

import { useEffect, useMemo, useState } from "react";

type Guide = { title:string; intro:string; steps:string[]; note:string; targets:string[] };

const GUIDES: Record<string, Guide> = {
  google_workspace:{title:"Google Workspace",intro:"Use Google OAuth. RYTHM requests only the scopes needed for the selected workflow.",steps:["Choose Google Workspace as the provider.","Select Connect with Google and sign in to the company-owned Google account.","Review the requested Gmail / Calendar scopes before approving.","Return to RYTHM and verify the connection status is Connected.","Grant only the capabilities the relevant Agents need."],note:"RYTHM never asks you to paste your Google password.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  generic_business_api:{title:"Business API / custom system",intro:"Use this for accounting, ERP, CRM, CMS, legal, HR or local software that exposes a secure HTTPS API.",steps:["Choose the provider.","Name the connection so the team can recognize it.","Add the account or tenant reference if your provider uses one.","Paste the secure HTTPS API base URL.","Choose the supported authentication method and minimum scopes.","Paste only a dedicated service credential, then create and verify the connection."],note:"Generic connections are origin-locked. Agents cannot replace the configured API host with an arbitrary URL.",targets:['select[name="providerKey"]','input[name="displayName"]','input[name="accountRef"]','input[name="baseUrl"]','select[name="authType"]','input[name="secret"]','button[type="submit"]']},
  google_ads:{title:"Google Ads",intro:"Connect the agency or client-owned Google Ads account. Campaign execution and budget authority are governed separately.",steps:["Choose Google Ads.","Name the connection and identify the Ads customer account.","Authorize reporting access first.","Verify account visibility.","Enable campaign publish only for responsible Agents. Budget/spend changes require Human CEO approval."],note:"Use minimum scopes and a company-controlled account.",targets:['select[name="providerKey"]','input[name="displayName"]','input[name="accountRef"]','select[name="authType"]','button[type="submit"]']},
  meta_marketing:{title:"Meta / Facebook / Instagram",intro:"Connect the correct Business Portfolio, Ad Account and Pages/Instagram accounts.",steps:["Choose Meta Marketing.","Name the connection and identify the client Business Portfolio / Ad Account.","Authorize only required Meta permissions.","Verify Page, Instagram and Ad Account visibility.","Grant publishing/campaign execution only to responsible Agents. Budget/spend remains Human CEO controlled."],note:"Meta Blueprint is training/certification; operational execution uses Meta platform APIs.",targets:['select[name="providerKey"]','input[name="displayName"]','input[name="accountRef"]','input[name="grantedScopes"]','button[type="submit"]']},
  youtube:{title:"YouTube",intro:"Connect the client-owned YouTube channel through Google OAuth for analytics and governed publishing.",steps:["Choose YouTube.","Identify the correct channel/account.","Authorize read scopes first.","Enable upload/publish scopes only when needed.","Review exact video metadata before governed publishing."],note:"Publishing is a consequential external action and remains approval governed.",targets:['select[name="providerKey"]','input[name="accountRef"]','input[name="grantedScopes"]','button[type="submit"]']},
  tiktok_business:{title:"TikTok for Business",intro:"Connect the advertiser account and publishing identity used for client content.",steps:["Choose TikTok for Business.","Identify the correct advertiser account.","Authorize reporting access first.","Verify advertiser/publishing identity.","Enable campaign/content writes only when needed. Budget changes require Human CEO approval."],note:"Only grant scopes needed for the specific client workflow.",targets:['select[name="providerKey"]','input[name="accountRef"]','input[name="grantedScopes"]','button[type="submit"]']},
  linkedin_marketing:{title:"LinkedIn Marketing",intro:"Connect the client Ad Account and Organization/Page used for campaigns or publishing.",steps:["Choose LinkedIn Marketing.","Identify the Organization/Page and Ad Account.","Authorize reporting and verify access.","Enable campaign/Page publishing only when needed.","Budget changes remain Human CEO controlled."],note:"RYTHM separates content/campaign execution authority from financial authority.",targets:['select[name="providerKey"]','input[name="accountRef"]','input[name="grantedScopes"]','button[type="submit"]']},
};

const DEFAULT_GUIDE: Guide={title:"Connection setup",intro:"Connect company-owned systems with least privilege. Credentials stay in Vault and consequential actions stay governed.",steps:["Select the company/client provider.","Give the connection a recognizable name.","Add account/project reference and base URL if needed.","Choose the minimum authentication/scopes.","Verify before assigning the connection to Agents."],note:"Do not paste personal passwords into API-token fields.",targets:['select[name="providerKey"]','input[name="displayName"]','input[name="accountRef"]','select[name="authType"]','button[type="submit"]']};

export function IntegrationSetupGuide(){
  const [providerKey,setProviderKey]=useState("");
  const [open,setOpen]=useState(false);
  const [step,setStep]=useState(0);
  useEffect(()=>{const select=document.querySelector<HTMLSelectElement>('select[name="providerKey"]');if(!select)return;const update=()=>{setProviderKey(select.value);setStep(0)};update();select.addEventListener("change",update);return()=>select.removeEventListener("change",update)},[]);
  const guide=useMemo(()=>GUIDES[providerKey]??DEFAULT_GUIDE,[providerKey]);
  const safeStep=Math.min(step,guide.steps.length-1);
  function showTarget(){const selector=guide.targets[Math.min(safeStep,guide.targets.length-1)];if(!selector)return;const element=document.querySelector<HTMLElement>(selector);if(!element)return;element.scrollIntoView({behavior:"smooth",block:"center"});element.focus({preventScroll:true});element.style.outline="3px solid #5367ef";element.style.outlineOffset="3px";window.setTimeout(()=>{element.style.outline="";element.style.outlineOffset=""},1800)}
  return <aside aria-label="Integration connection guide" style={{position:"fixed",right:20,bottom:20,zIndex:60,width:open?"min(400px,calc(100vw - 40px))":"auto",maxHeight:"76vh",overflow:"auto",border:"1px solid #d7deea",borderRadius:18,background:"rgba(255,255,255,.985)",color:"#111827",boxShadow:"0 22px 60px rgba(15,23,42,.24)",padding:open?18:0}}>
    {open?<>
      <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><p style={{margin:0,color:"#5367ef",fontWeight:900,fontSize:12,letterSpacing:1.2}}>GUIDED CONNECTION · {safeStep+1}/{guide.steps.length}</p><h3 style={{margin:"6px 0 8px",color:"#111827"}}>{guide.title}</h3></div><button type="button" onClick={()=>setOpen(false)} style={{border:"1px solid #d7deea",background:"#f8fafc",color:"#111827",borderRadius:10,padding:"8px 10px"}}>Hide</button></div>
      <p style={{marginTop:0,color:"#4b5563",lineHeight:1.55}}>{guide.intro}</p>
      <div style={{border:"1px solid #e1e6ef",borderRadius:14,padding:14,background:"#f8fafc"}}><strong style={{display:"block",marginBottom:6}}>Step {safeStep+1}</strong><span style={{color:"#374151",lineHeight:1.55}}>{guide.steps[safeStep]}</span></div>
      <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><button type="button" onClick={showTarget} style={{border:0,borderRadius:10,padding:"10px 12px",background:"#111827",color:"white",fontWeight:800}}>Show me where</button>{safeStep>0?<button type="button" onClick={()=>setStep((value)=>Math.max(0,value-1))} style={{border:"1px solid #d7deea",borderRadius:10,padding:"10px 12px",background:"white",color:"#111827"}}>Back</button>:null}<button type="button" onClick={()=>setStep((value)=>Math.min(guide.steps.length-1,value+1))} disabled={safeStep===guide.steps.length-1} style={{border:"1px solid #cfd7ff",borderRadius:10,padding:"10px 12px",background:"#eef2ff",color:"#29378f",fontWeight:800}}>Next step</button></div>
      <div style={{marginTop:12,borderRadius:12,padding:12,background:"#fff8e8",color:"#704d00",border:"1px solid #f3dfac"}}><strong>Security checkpoint</strong><div style={{marginTop:4,lineHeight:1.45}}>{guide.note}</div></div>
    </>:<button type="button" onClick={()=>setOpen(true)} style={{border:0,borderRadius:999,padding:"12px 16px",background:"#111827",color:"white",fontWeight:800,boxShadow:"0 14px 34px rgba(15,23,42,.22)"}}>Guide this connection</button>}
  </aside>
}
