"use client";

import { useEffect,useMemo,useState } from "react";

type Guide={title:string;intro:string;steps:string[];note:string;targets:string[]};
const GUIDES:Record<string,Guide>={
  google_workspace:{title:"Google Workspace",intro:"Connect the company Google account through the normal Google sign-in flow.",steps:["Choose Google Workspace.","Give the connection a familiar name.","Start secure setup.","Sign in on Google when prompted and review the requested access.","Return to RYTHM and confirm the service shows Connected."],note:"RYTHM never asks for your Google password.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  microsoft_365:{title:"Microsoft 365",intro:"Connect the company Microsoft account without exposing technical configuration.",steps:["Choose Microsoft 365.","Give the connection a familiar name.","Start secure setup.","Sign in on Microsoft when prompted and approve the requested company access.","Return to RYTHM and confirm the service shows Connected."],note:"Use a company-owned account. Technical permissions are managed by RYTHM.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  google_ads:{title:"Google Ads",intro:"Connect the agency or client-owned Google Ads account. RYTHM keeps campaign authority separate from spending authority.",steps:["Choose Google Ads.","Name the client or agency connection.","Start secure setup.","Sign in to the correct Google account when prompted.","Verify the connection. Campaign publishing can be approved later; budget changes remain Human-controlled."],note:"You should never need to enter API scopes, developer tokens or raw credentials here.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  meta_marketing:{title:"Meta / Facebook / Instagram",intro:"Connect the Business Portfolio used for Facebook and Instagram advertising or publishing.",steps:["Choose Meta Marketing.","Name the client connection.","Start secure setup.","Sign in to Meta and select the correct business assets when prompted.","Return to RYTHM and verify the service before enabling publishing or campaign actions."],note:"Publishing and campaign actions remain governed; budget/spend requires Human approval.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  youtube:{title:"YouTube",intro:"Connect the company or client YouTube channel using the normal Google authorization flow.",steps:["Choose YouTube.","Name the channel connection.","Start secure setup.","Select the correct Google/YouTube account when prompted.","Verify the connection before allowing uploads or publishing."],note:"Video publishing is a governed external action.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  tiktok_business:{title:"TikTok for Business",intro:"Connect the client advertiser or publishing account through a guided account flow.",steps:["Choose TikTok for Business.","Name the client connection.","Start secure setup.","Sign in to TikTok when prompted and choose the correct business account.","Return to RYTHM and verify the connection before campaign or content actions are enabled."],note:"Budget changes remain Human-controlled.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
  linkedin_marketing:{title:"LinkedIn Marketing",intro:"Connect the client Organization/Page and advertising account without handling API configuration yourself.",steps:["Choose LinkedIn Marketing.","Name the client connection.","Start secure setup.","Sign in to LinkedIn when prompted and select the relevant organization/account.","Return to RYTHM and verify the service before campaign or Page publishing is enabled."],note:"RYTHM separates publishing authority from financial authority.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']},
};
const DEFAULT_GUIDE:Guide={title:"Connect a company service",intro:"RYTHM guides you through account connection without requiring API knowledge.",steps:["Choose the service your company uses.","Give the connection a name you will recognize.","Start secure setup.","Follow the provider sign-in screen when available.","Return to RYTHM and verify the connection status."],note:"Technical credentials, API scopes and endpoint configuration are intentionally kept out of the normal customer flow.",targets:['select[name="providerKey"]','input[name="displayName"]','button[type="submit"]']};

export function IntegrationSetupGuide(){
  const [providerKey,setProviderKey]=useState("");const [open,setOpen]=useState(false);const [step,setStep]=useState(0);
  useEffect(()=>{const select=document.querySelector<HTMLSelectElement>('select[name="providerKey"]');if(!select)return;const update=()=>{setProviderKey(select.value);setStep(0)};update();select.addEventListener("change",update);return()=>select.removeEventListener("change",update)},[]);
  const guide=useMemo(()=>GUIDES[providerKey]??DEFAULT_GUIDE,[providerKey]);const safeStep=Math.min(step,guide.steps.length-1);
  function showTarget(){const selector=guide.targets[Math.min(safeStep,guide.targets.length-1)];if(!selector)return;const element=document.querySelector<HTMLElement>(selector);if(!element)return;element.scrollIntoView({behavior:"smooth",block:"center"});element.focus({preventScroll:true});element.style.outline="3px solid #5367ef";element.style.outlineOffset="3px";window.setTimeout(()=>{element.style.outline="";element.style.outlineOffset=""},1800)}
  return <aside className={`integration-guide ${open?"is-open":""}`} aria-label="Integration connection guide">
    {open?<><div className="integration-guide-head"><div><p>GUIDED CONNECTION · {safeStep+1}/{guide.steps.length}</p><h3>{guide.title}</h3></div><button type="button" onClick={()=>setOpen(false)}>Hide</button></div><p className="integration-guide-intro">{guide.intro}</p><div className="integration-guide-step"><strong>Step {safeStep+1}</strong><span>{guide.steps[safeStep]}</span></div><div className="integration-guide-actions"><button type="button" onClick={showTarget} className="integration-guide-primary">Show me where</button>{safeStep>0?<button type="button" onClick={()=>setStep((value)=>Math.max(0,value-1))}>Back</button>:null}<button type="button" onClick={()=>setStep((value)=>Math.min(guide.steps.length-1,value+1))} disabled={safeStep===guide.steps.length-1}>Next step</button></div><div className="integration-guide-note"><strong>Security checkpoint</strong><span>{guide.note}</span></div></>:<button type="button" onClick={()=>setOpen(true)} className="integration-guide-launch">Guide this connection</button>}
  </aside>;
}
