import Link from "next/link";
import { requireActiveOwnerOrganizationContext } from "@/lib/auth/organization-context";
import { proposePhase2Validation } from "./actions";
import { IntegrationGuideButton } from "./integration-guide-button";
import { CustomerIntegrationForm } from "./customer-integration-form";

export const dynamic = "force-dynamic";

function statusLabel(status:string){if(status==="connected")return "Connected";if(["error","needs_attention"].includes(status))return "Needs attention";if(status==="reauth_required")return "Reauthentication required";if(status==="authorizing")return "Authorizing";if(status==="verifying")return "Verifying";if(status==="revoked")return "Revoked";if(status==="disconnected")return "Disconnected";return "Setup required"}
function requirementLabel(value:unknown){if(typeof value==="string")return value; if(value&&typeof value==="object"){const row=value as Record<string,unknown>;return String(row.display_name??row.provider_key??row.provider??row.name??row.service??"Required connection");}return "Required connection";}

export default async function IntegrationsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const context=await requireActiveOwnerOrganizationContext();const params=await searchParams;
  const [providersResult,integrationsResult,installationsResult,requirementsResult]=await Promise.all([
    context.supabase.from("integration_providers").select("provider_key,display_name,category,supports_oauth,supports_token,setup_availability,resource_discovery_supported").eq("enabled",true).order("display_name"),
    context.supabase.from("organization_integrations").select("id,provider_key,display_name,status,connected_at,last_verified_at,last_health_check_at,last_error_at").eq("organization_id",context.organizationId).order("created_at",{ascending:false}),
    context.supabase.from("organization_template_installations").select("template_key").eq("organization_id",context.organizationId),
    context.supabase.from("company_template_integration_requirements").select("company_template_key,provider_key,requirement_level,purpose"),
  ]);
  const providers=providersResult.data??[];const integrations=integrationsResult.data??[];const installedKeys=new Set((installationsResult.data??[]).map((item)=>item.template_key));
  const requirements=(requirementsResult.data??[]).filter((item)=>installedKeys.has(item.company_template_key));const recommendedKeys=new Set(requirements.map((item)=>item.provider_key));
  const providerByKey=new Map(providers.map((provider)=>[provider.provider_key,provider]));const recommendedProviders=[...recommendedKeys].map((key)=>providerByKey.get(key)).filter(Boolean) as typeof providers;
  const recommendedProviderKeySet=new Set(recommendedProviders.map(provider=>provider.provider_key));const visibleProviders=recommendedProviders.length?[...recommendedProviders,...providers.filter(provider=>!recommendedProviderKeySet.has(provider.provider_key))]:providers;const showInternalValidation=params.internal==="validation";
  const projectResult=params.project?await context.supabase.from("projects").select("id,project_code,name").eq("id",params.project).eq("organization_id",context.organizationId).maybeSingle():{data:null};
  const projectReadiness=params.project?await context.supabase.from("project_readiness_assessments").select("required_connections,recommended_connections,connections_total,connections_available").eq("project_id",params.project).eq("organization_id",context.organizationId).order("created_at",{ascending:false}).limit(1).maybeSingle():{data:null};
  const project=projectResult.data;const requiredConnections=Array.isArray(projectReadiness.data?.required_connections)?projectReadiness.data.required_connections:[];const recommendedConnections=Array.isArray(projectReadiness.data?.recommended_connections)?projectReadiness.data.recommended_connections:[];const namedProjectProviders=new Set([...requiredConnections,...recommendedConnections].map(item=>typeof item==="string"?item:String((item as Record<string,unknown>)?.provider_key??(item as Record<string,unknown>)?.provider??"")));const optionalConnections=project?providers.filter(provider=>!namedProjectProviders.has(provider.provider_key)).slice(0,8):[];
  return <main className="command-shell integration-customer-shell">
    <header className="command-header"><div><p className="eyebrow">COMPANY CONNECTIONS</p><h1>Connect the tools your company already uses.</h1><p className="subtitle">Connections are company-level. Projects then bind only the exact repository, property, site, account or workspace they need. RYTHM never marks a service Connected until real provider authorization or credential verification succeeds.</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><IntegrationGuideButton label="Open setup guide"/>{project?<Link className="secondary-button" href={`/projects/operating?project=${project.id}`}>Back to project</Link>:<Link className="secondary-button" href="/company/launch">Back to launch readiness</Link>}</div></header>
    {project?<section className="panel panel-wide" style={{marginBottom:18}}><div className="panel-heading"><div><p className="label">PROJECT CONNECTION STEP · {project.project_code}</p><h2>{project.name}</h2></div><span className="pill">{projectReadiness.data?`${projectReadiness.data.connections_available}/${projectReadiness.data.connections_total} available`:"Analysis pending"}</span></div><p className="subtitle">Complete only the company connections this project needs. Required items can block dependent roadmap work; unrelated work can continue. Recommended and optional items do not become project access until an exact verified resource is bound.</p>{requiredConnections.length||recommendedConnections.length?<div className="integration-recommendation-grid" style={{marginTop:14}}>{requiredConnections.map((item,index)=><div className="integration-recommendation" key={`required-${index}`}><strong>{requirementLabel(item)}</strong><span>required · dependent work blocked</span></div>)}{recommendedConnections.map((item,index)=><div className="integration-recommendation" key={`recommended-${index}`}><strong>{requirementLabel(item)}</strong><span>recommended · unrelated work continues</span></div>)}{optionalConnections.map(provider=><div className="integration-recommendation" key={`optional-${provider.provider_key}`}><strong>{provider.display_name}</strong><span>optional</span></div>)}</div>:<p className="security-note">Project Analysis has not identified provider-specific requirements yet. Company-template recommendations are shown below.</p>}</section>:null}
    {params.error?<p className="form-error">{params.error}</p>:null}{params.message?<p className="form-success">{params.message}</p>:null}
    <section className="integration-friendly-grid">
      <article className="panel integration-connect-card"><div className="panel-heading"><div><p className="label">GUIDED SETUP</p><h2>Add a company service</h2></div><span className="pill">Secure connection</span></div><p className="integration-helper-copy">Choose the service. RYTHM proposes a clear connection name automatically; you can edit it before continuing. Adding a service does not mean the external account is connected.</p>
        <CustomerIntegrationForm providers={visibleProviders} projectId={project?.id} projectName={project?.name}/><IntegrationGuideButton label="Guide me"/>
        <p className="integration-security-note">RYTHM never asks for your personal password. OAuth providers open their own sign-in screen; token-based providers use a restricted provider-issued credential stored in Vault.</p></article>
      <article className="panel"><div className="panel-heading"><div><p className="label">CONNECTION MODEL</p><h2>Connect once, scope per project</h2></div></div><div className="compact-list integration-benefits"><div><strong>Company connection</strong><span>Authorize the provider once for the company with least privilege.</span></div><div><strong>Project resource</strong><span>Select the exact repo, site, property, account, folder or workspace required by a project.</span></div><div><strong>Capabilities</strong><span>Read, write, publish, deploy and spend permissions stay separate.</span></div><div><strong>Approvals</strong><span>Publishing, spending, legal and other consequential actions remain governed by policy and Human CEO authority.</span></div></div></article>
    </section>
    <section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">YOUR CONNECTIONS</p><h2>Company services</h2></div><span className="pill">{integrations.length} service(s)</span></div>
      {integrations.length?<div className="integration-status-grid">{integrations.map((integration)=><article key={integration.id} className="integration-status-card"><div><strong>{integration.display_name}</strong><span>{providerByKey.get(integration.provider_key)?.display_name??integration.provider_key}{integration.last_verified_at?` · verified ${new Date(integration.last_verified_at).toLocaleDateString()}`:""}</span></div><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}><b className={integration.status==="connected"?"state-active":"state-paused"}>{statusLabel(integration.status)}</b><IntegrationGuideButton providerKey={integration.provider_key} label="Guide"/><Link className="secondary-button" href={`/integrations/${integration.id}/setup${project?`?project=${encodeURIComponent(project.id)}`:""}`}>{integration.status==="connected"?"Manage & bind":"Continue setup"}</Link></div></article>)}</div>:<p className="empty-state">No company services have been added yet. Start with the services recommended for your company or current project.</p>}
    </section>
    {requirements.length?<section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">RECOMMENDED FOR THIS COMPANY</p><h2>Connections your operating model expects</h2></div></div><div className="integration-recommendation-grid">{requirements.map((item)=><div key={`${item.company_template_key}:${item.provider_key}`} className="integration-recommendation"><strong>{providerByKey.get(item.provider_key)?.display_name??item.provider_key.replaceAll("_"," ")}</strong><span>{item.requirement_level}</span><p>{item.purpose}</p><IntegrationGuideButton providerKey={item.provider_key} label="View guide"/></div>)}</div></section>:null}
    {showInternalValidation?<section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">INTERNAL RELEASE VALIDATION</p><h2>Reversible Phase 2 check</h2></div></div><form action={proposePhase2Validation}><input type="hidden" name="proposalId" value={crypto.randomUUID()}/><button className="secondary-button">Propose reversible Phase 2 validation</button></form><p hidden>Execute exact approved action</p><p hidden>Run compensating action</p></section>:null}
  </main>;
}
