import { createHash, randomUUID } from "node:crypto";
import Link from "next/link";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createAuthServerClient } from "@/lib/supabase/auth-server";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { calculateProjectProgressSnapshot, getProjectProgressSnapshots } from "@/lib/projects/project-progress";

export const dynamic="force-dynamic";

type Project={id:string;project_code:string;name:string;description:string|null;status:string;stage:string;priority:number;progress_percent:number;readiness_score:number;target_date:string|null;updated_at:string;responsible_department:string|null;lifecycle_state:string;overall_project_progress:number;next_required_action:string|null;work_progress:number;deliverable_progress:number;implementation_progress:number;verification_progress:number;outcome_progress:number;acceptance_progress:number;closeout_progress:number;completion_eligible:boolean;};
type ProjectAgent={project_id:string;status:string;assignment_role:string|null;agents:{agent_code:string;display_name:string|null;name:string}|null;};
type ProjectEntity={project_id:string|null;status?:string};
const text=(form:FormData,key:string,max=5000)=>String(form.get(key)??"").trim().slice(0,max);
const jsonLines=(value:string)=>value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);
const safeName=(value:string)=>value.normalize("NFKC").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(-160)||"file";
function formatDate(value:string|null){return value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(value)):"No target date";}
function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());}

async function ownerContext(){
  const supabase=await createAuthServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const {data:membership}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("role","owner").maybeSingle();
  if(!membership)redirect("/login?error=Owner%20authorization%20required.");
  return{supabase,organizationId:membership.organization_id as string,user};
}

async function createProject(formData:FormData){
  "use server";
  const {supabase,organizationId,user}=await ownerContext();
  const objective=text(formData,"objective",5000);
  const quickStart=text(formData,"quickStart",10)==="1";
  const projectCode=(quickStart?`PROJECT-${randomUUID().slice(0,8).toUpperCase()}`:text(formData,"projectCode",40).toUpperCase().replace(/[^A-Z0-9-]+/g,"-").replace(/^-+|-+$/g,""));
  const name=quickStart?objective.slice(0,120):text(formData,"name",120);const description=text(formData,"description",5000);
  if(projectCode.length<3||name.length<3)redirect("/projects?error=Project%20code%20and%20name%20must%20contain%20at%20least%203%20characters.");
  const priority=Math.max(1,Math.min(5,Number(formData.get("priority")??3)));
  const startDate=text(formData,"startDate",20)||null;const targetDate=text(formData,"targetDate",20)||null;
  const tags=text(formData,"tags",1000).split(",").map(v=>v.trim()).filter(Boolean).slice(0,30);
  const autonomyMode=text(formData,"autonomyMode",80)||"approval_required";
  const {data:project,error}=await supabase.from("projects").insert({organization_id:organizationId,project_code:projectCode,name,description,project_type:text(formData,"projectType",80)||"business_project",status:"planning",stage:"intake",priority,owner_type:"human_ceo",objective,scope:{},success_criteria:jsonLines(text(formData,"successCriteria",5000)),constraints:["Human CEO retains consequential authority","External actions remain governed by Integration & Execution Gateway",...jsonLines(text(formData,"constraints",5000))],progress_percent:0,created_by_user_id:user.id,start_date:startDate,target_date:targetDate,internal_owner_label:text(formData,"internalOwner",160)||null,responsible_department:text(formData,"responsibleDepartment",160)||null,tags,notes:text(formData,"notes",8000),autonomy_mode:autonomyMode,readiness_score:0}).select("id").single();
  if(error||!project){console.error("project_create_failed",{projectCode,error});redirect("/projects?error=Project%20could%20not%20be%20created.%20Confirm%20the%20project%20code%20is%20unique%20and%20retry.");}

  const clientName=text(formData,"clientName",240);
  if(clientName){await supabase.from("project_clients").insert({organization_id:organizationId,project_id:project.id,client_name:clientName,legal_company_name:text(formData,"legalCompanyName",240)||null,trading_name:text(formData,"tradingName",240)||null,client_type:text(formData,"clientType",100)||null,contact_person:text(formData,"contactPerson",240)||null,email:text(formData,"clientEmail",320)||null,phone:text(formData,"clientPhone",100)||null,website:text(formData,"clientWebsite",1000)||null,country:text(formData,"clientCountry",160)||null,billing_entity:text(formData,"billingEntity",240)||null,relationship_type:text(formData,"relationshipType",80)||"other"});}

  const contractNumber=text(formData,"contractNumber",160);const contractValue=text(formData,"contractValue",80);
  const hasContract=Boolean(contractNumber||contractValue||text(formData,"deliverables")||text(formData,"paymentTerms")||text(formData,"specialClauses"));
  if(hasContract){await supabase.from("project_contracts").insert({organization_id:organizationId,project_id:project.id,contract_number:contractNumber||null,contract_start_date:text(formData,"contractStartDate",20)||null,contract_end_date:text(formData,"contractEndDate",20)||null,contract_value:contractValue?Number(contractValue):null,currency:text(formData,"currency",12)||null,payment_terms:text(formData,"paymentTerms",3000)||null,deliverables:jsonLines(text(formData,"deliverables",8000)),sla:{text:text(formData,"sla",4000)},milestones:jsonLines(text(formData,"contractMilestones",8000)),provider_obligations:jsonLines(text(formData,"providerObligations",8000)),client_obligations:jsonLines(text(formData,"clientObligations",8000)),exclusions:jsonLines(text(formData,"exclusions",8000)),dependencies:jsonLines(text(formData,"dependencies",8000)),approval_requirements:jsonLines(text(formData,"approvalRequirements",8000)),termination_conditions:text(formData,"terminationConditions",4000)||null,confidentiality_requirements:text(formData,"confidentiality",4000)||null,ip_ownership:text(formData,"ipOwnership",4000)||null,data_protection_requirements:text(formData,"dataProtection",4000)||null,special_clauses:jsonLines(text(formData,"specialClauses",8000)),notes:text(formData,"contractNotes",8000)});}

  const resources=[
    {type:"website",name:"Website",url:text(formData,"website",1200)},
    {type:"github",name:"GitHub repository",url:text(formData,"github",1200)},
    {type:"google_drive",name:"Google Drive",url:text(formData,"drive",1200)},
    {type:"figma",name:"Figma",url:text(formData,"figma",1200)},
  ].filter(r=>r.url);
  if(resources.length)await supabase.from("project_resources").insert(resources.map(r=>({organization_id:organizationId,project_id:project.id,resource_type:r.type,name:r.name,url:r.url,status:"connected",source:"project_intake",access_status:"unknown"})));

  const files=formData.getAll("files").filter((item):item is File=>item instanceof File&&item.size>0).slice(0,20);
  if(files.length){
    const service=createServerSupabaseClient();
    if(service){for(const file of files){if(file.size>50*1024*1024)continue;const bytes=Buffer.from(await file.arrayBuffer());const storagePath=`${organizationId}/${project.id}/${randomUUID()}-${safeName(file.name)}`;const uploaded=await service.storage.from("project-files").upload(storagePath,bytes,{contentType:file.type||"application/octet-stream",upsert:false});if(!uploaded.error){const category=text(formData,"fileCategory",80)||"other";await service.from("project_documents").insert({organization_id:organizationId,project_id:project.id,category,file_name:file.name,storage_path:storagePath,mime_type:file.type,byte_size:file.size,checksum:createHash("sha256").update(bytes).digest("hex"),legal_document:["contract","amendment","nda","statement_of_work"].includes(category),uploaded_by_user_id:user.id});}}}
  }
  await supabase.from("audit_events").insert({organization_id:organizationId,actor_type:"user",actor_user_id:user.id,event_type:"project.created",object_type:"project",object_id:project.id,risk_level:"low",payload:{project_code:projectCode,name,human_authority:"Human CEO / Owner",autonomy_mode:autonomyMode,files:files.length}});
  revalidatePath("/projects");redirect(`/projects/operating?project=${project.id}`);
}

export default async function ProjectsPortfolioPage({searchParams}:{searchParams:Promise<{error?:string}>}){
  const query=await searchParams;const {supabase,organizationId}=await ownerContext();
  const [projectsResult,agentsResult,attentionResult]=await Promise.all([
    supabase.from("projects").select("id,project_code,name,description,status,stage,priority,progress_percent,readiness_score,target_date,updated_at,responsible_department,lifecycle_state,overall_project_progress,next_required_action,work_progress,deliverable_progress,implementation_progress,verification_progress,outcome_progress,acceptance_progress,closeout_progress,completion_eligible").eq("organization_id",organizationId).order("priority").order("updated_at",{ascending:false}),
    supabase.from("project_agents").select("project_id,status,assignment_role,agents(agent_code,display_name,name)").eq("organization_id",organizationId),
    supabase.from("project_proposals").select("project_id,status").eq("organization_id",organizationId).in("status",["ready_for_executive","needs_revision"])
  ]);
  const projects=(projectsResult.data??[]) as Project[];const progressSnapshots=await getProjectProgressSnapshots(supabase,organizationId,projects);const projectAgents=(agentsResult.data??[]) as unknown as ProjectAgent[];const attention=(attentionResult.data??[]) as ProjectEntity[];
  const agentsFor=(id:string)=>projectAgents.filter(row=>row.project_id===id&&["assigned","active"].includes(row.status));
  const running=projects.filter(p=>!["COMPLETED","CANCELLED","FAILED","BLOCKED","ON_HOLD"].includes(p.lifecycle_state)).length;const blocked=projects.filter(p=>["BLOCKED","ON_HOLD"].includes(p.lifecycle_state)).length;const completed=projects.filter(p=>p.lifecycle_state==="COMPLETED").length;
  return <main className="command-shell">
    <header className="command-header"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Projects</h1><p className="subtitle">See what RYTHM is working on and what comes next.</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Link className="secondary-button" href="/inbox">Inbox</Link><Link className="secondary-button" href="/home">Ask RYTHM</Link></div></header>
    {query.error?<p className="form-error">{query.error}</p>:null}
    <section className="organization-banner"><div><span>Total projects</span><strong>{projects.length}</strong></div><div><span>Running</span><strong>{running}</strong></div><div><span>Needs attention</span><strong>{attention.length}</strong></div><div><span>Blocked</span><strong>{blocked}</strong></div><div><span>Completed</span><strong>{completed}</strong></div></section>

    <details className="panel panel-wide" style={{marginTop:18}}><summary style={{cursor:"pointer",fontWeight:800}}>Start a project here</summary><div aria-labelledby="project-objective-heading"><div className="panel-heading"><div><p className="label">Delegate an outcome</p><h2 id="project-objective-heading">What should your company accomplish?</h2></div><span className="pill">Start with an objective</span></div><form action={createProject} className="auth-form"><input type="hidden" name="quickStart" value="1"/><label>Objective<textarea name="objective" required minLength={3} maxLength={5000} rows={3} placeholder="Build a landing page for my SaaS product, then show me a preview for review."/></label><button type="submit">Create project</button><p className="security-note">Next, run Project Analysis in the project workspace to get a roadmap, team and required connections. Execution starts only after readiness and approval gates are satisfied.</p></form></div></details>

    <section className="panel panel-wide" style={{marginTop:18}}><details><summary style={{cursor:"pointer",fontWeight:800,fontSize:18}}>Advanced project setup</summary><form action={createProject} className="auth-form" style={{marginTop:18}}>
      <div className="panel-heading"><div><p className="label">1 · Project Identity</p><h2>Outcome and ownership</h2></div><span className="pill">Only name and code are required</span></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><label>Project code<input name="projectCode" required minLength={3} maxLength={40} placeholder="AI-CAREER-SEO"/></label><label>Project name<input name="name" required minLength={3} maxLength={120}/></label><label>Project type<input name="projectType" placeholder="SEO, campaign, product, client delivery…"/></label><label>Priority<select name="priority" defaultValue="3"><option value="1">P1 · Critical</option><option value="2">P2 · High</option><option value="3">P3 · Normal</option><option value="4">P4 · Low</option><option value="5">P5 · Backlog</option></select></label><label>Start date<input type="date" name="startDate"/></label><label>Target completion<input type="date" name="targetDate"/></label><label>Internal owner<input name="internalOwner"/></label><label>Responsible department<input name="responsibleDepartment"/></label><label>Tags<input name="tags" placeholder="SEO, Growth, AI Career"/></label><label>Autonomy<select name="autonomyMode" defaultValue="approval_required"><option value="observe_only">Observe Only</option><option value="approval_required">Approval Required</option><option value="limited_autonomy">Limited Autonomy</option><option value="full_autonomy_within_policy">Full Autonomy Within Policy</option></select></label></div>
      <label>Description<textarea name="description" rows={3}/></label><label>Objective / desired outcome<textarea name="objective" rows={3}/></label><label>Success criteria · one per line<textarea name="successCriteria" rows={3}/></label><label>Constraints · one per line<textarea name="constraints" rows={3}/></label><label>Notes<textarea name="notes" rows={3}/></label>

      <div className="panel-heading" style={{marginTop:24}}><div><p className="label">2 · Client / Counterparty</p><h2>Who receives the work?</h2></div><span className="pill">Optional</span></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><label>Client name<input name="clientName"/></label><label>Legal company name<input name="legalCompanyName"/></label><label>Trading name<input name="tradingName"/></label><label>Client type<input name="clientType"/></label><label>Relationship<select name="relationshipType" defaultValue="other"><option value="internal">Internal</option><option value="b2b_client">B2B Client</option><option value="b2c_customer">B2C Customer</option><option value="partner">Partner</option><option value="vendor">Vendor</option><option value="contractor">Contractor</option><option value="other">Other</option></select></label><label>Contact person<input name="contactPerson"/></label><label>Email<input type="email" name="clientEmail"/></label><label>Phone<input name="clientPhone"/></label><label>Website<input type="url" name="clientWebsite"/></label><label>Country<input name="clientCountry"/></label><label>Billing entity<input name="billingEntity"/></label></div>

      <div className="panel-heading" style={{marginTop:24}}><div><p className="label">3 · Contract & Commercial</p><h2>Commercial boundaries</h2></div><span className="pill">Optional · documents can supply this</span></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><label>Contract number<input name="contractNumber"/></label><label>Start<input type="date" name="contractStartDate"/></label><label>End<input type="date" name="contractEndDate"/></label><label>Contract value<input type="number" min="0" step="0.01" name="contractValue"/></label><label>Currency<input name="currency" placeholder="EUR"/></label><label>Payment terms<input name="paymentTerms"/></label></div>
      <label>Deliverables · one per line<textarea name="deliverables" rows={3}/></label><label>SLA<textarea name="sla" rows={2}/></label><label>Milestones · one per line<textarea name="contractMilestones" rows={3}/></label><label>Our obligations · one per line<textarea name="providerObligations" rows={3}/></label><label>Client obligations · one per line<textarea name="clientObligations" rows={3}/></label><label>Exclusions / dependencies<textarea name="exclusions" rows={2}/><textarea name="dependencies" rows={2}/></label><label>Approval requirements<textarea name="approvalRequirements" rows={2}/></label><label>Termination / confidentiality / IP / data protection<textarea name="terminationConditions" rows={2} placeholder="Termination conditions"/><textarea name="confidentiality" rows={2} placeholder="Confidentiality requirements"/><textarea name="ipOwnership" rows={2} placeholder="IP ownership"/><textarea name="dataProtection" rows={2} placeholder="Data protection requirements"/></label><label>Special clauses · one per line<textarea name="specialClauses" rows={3}/></label><label>Contract notes<textarea name="contractNotes" rows={2}/></label>

      <div className="panel-heading" style={{marginTop:24}}><div><p className="label">4 · Resources & Files</p><h2>Project Knowledge inputs</h2></div><span className="pill">Optional</span></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><label>Website<input type="url" name="website"/></label><label>GitHub repository<input type="url" name="github"/></label><label>Google Drive<input type="url" name="drive"/></label><label>Figma<input type="url" name="figma"/></label><label>File category<select name="fileCategory" defaultValue="other"><option value="contract">Contract</option><option value="amendment">Amendment</option><option value="nda">NDA</option><option value="statement_of_work">Statement of Work</option><option value="client_brief">Client Brief</option><option value="brand_guidelines">Brand Guidelines</option><option value="research">Research</option><option value="analytics">Analytics</option><option value="financial">Financial</option><option value="creative_asset">Creative Asset</option><option value="technical_documentation">Technical Documentation</option><option value="report">Report</option><option value="other">Other</option></select></label><label>Project files<input type="file" name="files" multiple accept=".pdf,.docx,.xlsx,.xls,.csv,.pptx,.txt,.png,.jpg,.jpeg,.webp"/></label></div>
      <button>Create Project</button><p className="security-note">Creation does not start autonomous execution. RYTHM first analyzes readiness, scope, team and required connections. Human CEO authority remains intact.</p>
    </form></details></section>

    <section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">Portfolio</p><h2>All projects</h2></div><span className="pill">{projects.length}</span></div>{projects.length===0?<p className="empty-state">No active projects. Ask RYTHM to start something.</p>:<div className="data-list">{projects.map(project=>{const assignedAgents=agentsFor(project.id);const progress=progressSnapshots.get(project.id)??calculateProjectProgressSnapshot([],0,project.status,project.updated_at);const next=project.next_required_action||progress.nextMilestone||"Project analysis and roadmap";return <Link className="data-row simple-project-row" href={`/projects/operating?project=${project.id}`} key={project.id}><div><strong>{project.name}</strong><span>{project.responsible_department||"RYTHM is forming the team"} · {assignedAgents.find(agent=>agent.assignment_role?.toLowerCase().includes("manager"))?.agents?.display_name||"Manager pending"} · Updated {formatDate(project.updated_at)}</span><small>Next: {next}{progress.awaitingApproval?` · ${progress.awaitingApproval} approval(s) need attention`:""}</small></div><div className="simple-project-status"><span className="pill">{label(project.lifecycle_state||project.status)}</span><strong>{project.lifecycle_state==="COMPLETED"?"Complete":`${project.overall_project_progress}%`}</strong></div></Link>})}</div>}</section>
  </main>;
}
