"use client";
import { useCallback,useEffect,useMemo,useState,type CSSProperties } from "react";
import FilesPanel from "@/components/ai-workspace/FilesPanel";
import WorkspaceResourcePanel from "@/components/ai-workspace/WorkspaceResourcePanel";
import CompanyMemberInviteForm from "@/components/ai-workspace/CompanyMemberInviteForm";

type Mode="auto"|"fast"|"best";
type Profile="normal"|"professional";
type Plugin={key:string;name:string;category:string;status:"Connected"|"Available"|"Coming soon"|"Admin setup required"|"Disabled"};
type Plan={plan_code:string|null;plan_status:string|null;plan_period_start:string|null;plan_period_end:string|null;plan_credit_limit_micros:number|null;plan_request_limit:number|null};
type Session={user:{email:string|null};workspace:{id:string;name:string};defaultProject:{id:string;name:string};projects:Array<{id:string;name:string}>;conversations:Array<{id:string;title:string}>;balanceMicros:string;currency:string;payerType:"personal"|"company";companyRoleLabel:string|null;organization:{id:string;name:string;role:string}|null;plugins:Plugin[];modes:string[];promptProfiles:string[];plan:Plan|null};
type Message={role:"user"|"assistant";content:string};
type View="chat"|"projects"|"knowledge"|"memory"|"files"|"prompts"|"plugins"|"skills"|"usage"|"billing"|"settings";

const nav:Array<{group:string;items:Array<[View,string]>}>=[{group:"CHAT",items:[["chat","Chats"],["projects","Projects"]]},{group:"WORKSPACE",items:[["knowledge","Knowledge"],["memory","Memory"],["files","Files"],["prompts","Saved Prompts"]]},{group:"TOOLS",items:[["plugins","Plugins"],["skills","Skills"]]},{group:"ACCOUNT",items:[["usage","Usage"],["billing","Plan & Billing"],["settings","Settings"]]}];
const panel:CSSProperties={border:"1px solid rgba(148,163,184,.22)",borderRadius:16,background:"rgba(255,255,255,.82)",padding:18};
const BLENDED_USD_PER_MILLION:Record<Mode,number>={fast:.45,auto:4.5,best:18};
function tokenEstimate(micros:string|number,mode:Mode){const usd=Math.max(0,Number(micros))/1_000_000;return Math.max(0,Math.floor((usd/BLENDED_USD_PER_MILLION[mode])*1_000_000));}
function compactTokens(n:number){if(n>=1_000_000)return`${(n/1_000_000).toFixed(n>=10_000_000?0:1)}M`;if(n>=1_000)return`${Math.round(n/1_000)}K`;return String(n);}
function modeLabel(mode:Mode){if(mode==="fast")return"Fast · Luna";if(mode==="auto")return"Smart · Terra";return"Best · Sol";}
function defaultMode(modes:string[]):Mode{return(modes.includes("fast")?"fast":modes.includes("auto")?"auto":modes.includes("best")?"best":"fast") as Mode;}
function currentPlanName(plan:Plan|null){if(plan?.plan_code==="starter")return"Starter";if(plan?.plan_code==="free_trial")return"Free Trial";return"Personal";}

export default function AIWorkspaceClient(){
  const[session,setSession]=useState<Session|null>(null),[error,setError]=useState<string|null>(null),[view,setView]=useState<View>("chat"),[mobileOpen,setMobileOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[messages,setMessages]=useState<Message[]>([]),[prompt,setPrompt]=useState(""),[conversationId,setConversationId]=useState<string|null>(null),[mode,setMode]=useState<Mode>("fast"),[profile,setProfile]=useState<Profile>("normal"),[sending,setSending]=useState(false),[notice,setNotice]=useState<string|null>(null),[upgrade,setUpgrade]=useState<{title:string;copy:string}|null>(null);
  const load=useCallback(async()=>{try{const r=await fetch("/api/ai-workspace/session",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Session unavailable");setSession(j);setError(null);}catch(e){setError(e instanceof Error?e.message:"AI Workspace unavailable");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!session)return;if(!session.modes.includes(mode))setMode(defaultMode(session.modes));if(!session.promptProfiles.includes(profile))setProfile("normal");},[session,mode,profile]);
  const pluginGroups=useMemo(()=>{const m=new Map<string,Plugin[]>();for(const p of session?.plugins??[])m.set(p.category,[...(m.get(p.category)??[]),p]);return[...m.entries()];},[session]);
  const fastRemaining=session?tokenEstimate(session.balanceMicros,"fast"):0;
  const smartRemaining=session?tokenEstimate(session.balanceMicros,"auto"):0;
  function requestMode(next:Mode){if(session?.modes.includes(next)){setMode(next);return;}setUpgrade(next==="auto"?{title:"Unlock Smart mode",copy:"Smart · Terra is not included in your current plan. Starter unlocks Smart mode and a larger monthly token allowance."}:{title:"Higher-capability mode",copy:"Best · Sol is reserved for a higher RYTHM AI plan. View token plans to see the currently available upgrade."});}
  function requestProfile(next:Profile){if(session?.promptProfiles.includes(next)){setProfile(next);return;}setUpgrade({title:"Professional mode is not included",copy:"Professional mode adds a separate prompt-enhancement stage and is not included in Free Trial or Starter. Your current plan remains on Normal mode."});}
  async function send(){if(!session)return;const text=prompt.trim();if(!text||sending)return;const effectiveMode=session.modes.includes(mode)?mode:defaultMode(session.modes);const effectiveProfile=session.promptProfiles.includes(profile)?profile:"normal";if(effectiveMode!==mode)setMode(effectiveMode);if(effectiveProfile!==profile)setProfile(effectiveProfile as Profile);const requestKey=crypto.randomUUID();setPrompt("");setMessages(v=>[...v,{role:"user",content:text}]);setSending(true);setNotice(null);try{const r=await fetch("/api/ai-workspace/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:text,conversationId,mode:effectiveMode,promptProfile:effectiveProfile,requestKey})});const j=await r.json();if(!r.ok){if(j.error==="MODE_NOT_ALLOWED"){setUpgrade({title:"This mode is not in your plan",copy:"Your plan does not include the selected AI mode. Choose an included mode or view token plans."});throw new Error("Please choose a mode included in your plan.");}if(j.error==="INSUFFICIENT_CREDIT_OR_LIMIT"){setUpgrade({title:"Token allowance reached",copy:"You have reached a token, request, or trial limit. Upgrade to Starter for a larger monthly token allowance."});throw new Error("Your current token allowance has been reached.");}throw new Error(j.error||"Request failed");}setConversationId(j.conversationId);setMessages(v=>[...v,{role:"assistant",content:j.message}]);const sourceNote=Array.isArray(j.sources)&&j.sources.length?` · ${j.sources.length} knowledge source(s)`:"";const approxUsed=tokenEstimate(String(j.usage?.totalMicros??0),effectiveMode);setNotice(`≈ ${compactTokens(approxUsed)} token-equivalent used · ${j.routing.model}${sourceNote}`);await load();}catch(e){const message=e instanceof Error?e.message:"Request failed";setMessages(v=>[...v,{role:"assistant",content:message}]);}finally{setSending(false);}}
  if(error)return<main style={{padding:32}}><h1>RYTHM AI</h1><p>{error}</p></main>;
  if(!session)return<main style={{padding:32}} aria-busy="true">Loading RYTHM AI…</main>;
  const simple:Partial<Record<View,{title:string;description:string}>>={usage:{title:"Usage",description:"Token allowance, request limits and payer attribution."},settings:{title:"Settings",description:"Workspace preferences, routing, access and prompt-mode defaults."}};
  const planName=currentPlanName(session.plan);
  const trial=session.plan?.plan_code==="free_trial";
  const starter=session.plan?.plan_code==="starter";
  return <div className={`ai-shell${mobileOpen?" mobile-open":""}`} style={{display:"grid",gridTemplateColumns:collapsed?"76px minmax(0,1fr)":"260px minmax(0,1fr)",minHeight:"calc(100vh - 40px)",background:"linear-gradient(135deg,#f8fafc,#eef2ff 55%,#f8fafc)"}}>
    <button className="ai-mobile-menu" type="button" onClick={()=>setMobileOpen(true)} aria-label="Open AI navigation">Menu</button><button className="ai-backdrop" type="button" aria-label="Close AI navigation" onClick={()=>setMobileOpen(false)}/>
    <aside className="ai-sidebar" aria-label="RYTHM AI navigation" style={{display:"flex",position:"sticky",top:0,height:"100vh",flexDirection:"column",gap:14,padding:14,borderRight:"1px solid rgba(148,163,184,.2)",background:"rgba(15,23,42,.97)",color:"#e5e7eb",zIndex:30}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong>{collapsed?"AI":"RYTHM AI"}</strong><button type="button" onClick={()=>setCollapsed(v=>!v)} style={{background:"transparent",border:0,color:"inherit",cursor:"pointer"}} aria-label={collapsed?"Expand AI sidebar":"Collapse AI sidebar"}>{collapsed?"›":"‹"}</button></div>
      <button type="button" onClick={()=>{setView("chat");setConversationId(null);setMessages([]);setMobileOpen(false);}} style={{border:0,borderRadius:10,padding:11,fontWeight:700,cursor:"pointer"}}>+ {collapsed?"":"New Chat"}</button>
      <div style={{overflowY:"auto",flex:1}}>{nav.map(g=><section key={g.group} style={{marginBottom:14}}><small style={{opacity:.55,display:collapsed?"none":"block",margin:"5px 7px"}}>{g.group}</small>{g.items.map(([key,label])=><button type="button" key={key} onClick={()=>{setView(key);setMobileOpen(false)}} title={collapsed?label:undefined} style={{width:"100%",textAlign:"left",padding:"9px 10px",marginBottom:3,border:0,borderRadius:8,cursor:"pointer",background:view===key?"rgba(255,255,255,.14)":"transparent",color:"inherit"}}>{collapsed?label.slice(0,1):label}</button>)}</section>)}</div>
      <div style={{display:"grid",gap:8,borderTop:"1px solid rgba(255,255,255,.12)",paddingTop:12}}>
        <select value={mode} onChange={e=>requestMode(e.target.value as Mode)} aria-label="AI mode" style={{padding:8,borderRadius:8}}><option value="fast">Fast · Luna{session.modes.includes("fast")?"":" · Upgrade"}</option><option value="auto">Smart · Terra{session.modes.includes("auto")?"":" · Upgrade"}</option><option value="best">Best · Sol{session.modes.includes("best")?"":" · Higher plan"}</option></select>
        <select value={profile} onChange={e=>requestProfile(e.target.value as Profile)} aria-label="Prompt mode" style={{padding:8,borderRadius:8}}><option value="normal">Normal</option><option value="professional">Professional{session.promptProfiles.includes("professional")?"":" · Higher plan"}</option></select>
        {!collapsed?<><strong style={{fontSize:13}}>{session.user.email||"Account"}</strong><small>{planName}{session.payerType==="company"?` · Company funded${session.companyRoleLabel?` · ${session.companyRoleLabel}`:""}`:""}</small><small>{session.modes.includes("auto")?`Remaining ≈ ${compactTokens(fastRemaining)} Fast / ${compactTokens(smartRemaining)} Smart tokens`:`Remaining ≈ ${compactTokens(fastRemaining)} Fast tokens`}</small></>:null}
      </div>
    </aside>
    <main style={{minWidth:0,padding:"clamp(16px,3vw,40px)",maxWidth:1200,width:"100%",margin:"0 auto"}}>
      {view==="chat"?<div style={{height:"calc(100vh - 80px)",display:"grid",gridTemplateRows:"auto 1fr auto",gap:16}}><header><h1 style={{margin:"0 0 6px"}}>RYTHM AI</h1><p style={{margin:0,opacity:.65}}>Governed AI workspace · {session.organization?.name||"Personal"}</p></header><section aria-live="polite" style={{overflowY:"auto",display:"grid",alignContent:"start",gap:12}}>{messages.length===0?<div style={{...panel,maxWidth:680}}><h2 style={{marginTop:0}}>What are you working on?</h2><p style={{marginBottom:0}}>Start a conversation. Your available AI modes and token allowance are enforced by your current plan.</p></div>:messages.map((m,i)=><article key={`${m.role}-${i}`} style={{...panel,maxWidth:820,marginLeft:m.role==="user"?"auto":0,background:m.role==="user"?"#111827":"rgba(255,255,255,.86)",color:m.role==="user"?"white":"inherit",whiteSpace:"pre-wrap"}}>{m.content}</article>)}{sending?<div>RYTHM AI is working…</div>:null}</section><div><div style={{...panel,padding:10,display:"flex",gap:10}}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Message RYTHM AI" rows={3} style={{flex:1,resize:"none",border:0,outline:0,background:"transparent",font:"inherit"}}/><button type="button" onClick={()=>void send()} disabled={sending||!prompt.trim()} style={{alignSelf:"end",border:0,borderRadius:10,padding:"10px 16px",background:"#111827",color:"white",fontWeight:700}}>Send</button></div>{notice?<small style={{display:"block",marginTop:7,opacity:.62}}>{notice}</small>:null}</div></div>:null}
      {view==="projects"?<WorkspaceResourcePanel kind="projects" projectId={session.defaultProject.id}/>:null}{view==="memory"?<WorkspaceResourcePanel kind="memories" projectId={session.defaultProject.id}/>:null}{view==="prompts"?<WorkspaceResourcePanel kind="prompts" projectId={session.defaultProject.id}/>:null}{view==="skills"?<WorkspaceResourcePanel kind="skills" projectId={session.defaultProject.id}/>:null}{view==="files"?<FilesPanel projectId={session.defaultProject.id}/>:null}{view==="knowledge"?<FilesPanel projectId={session.defaultProject.id} knowledge/>:null}
      {view==="plugins"?<><h1>Plugins</h1><p>RYTHM AI uses the same connector and execution gateway as Company Agents and Automation. No provider is shown as connected without a verified RYTHM connection.</p>{pluginGroups.map(([category,plugins])=><section key={category} style={{marginTop:24}}><h2>{category}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}>{plugins.map(p=><article key={p.key} style={panel}><strong>{p.name}</strong><div style={{marginTop:10}}><span style={{fontSize:12,border:"1px solid rgba(148,163,184,.4)",borderRadius:999,padding:"4px 8px"}}>{p.status}</span></div>{p.status==="Admin setup required"||p.status==="Coming soon"||p.status==="Disabled"?<p style={{fontSize:13,opacity:.62}}>No Connect action is shown until a real provider flow is configured.</p>:null}</article>)}</div></section>)}</>:null}
      {view==="billing"?<><h1>Plan & Billing</h1><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:16,maxWidth:900}}><article style={panel}><small style={{fontWeight:800,opacity:.62}}>FREE TRIAL</small><h2 style={{marginBottom:6}}>Try RYTHM AI</h2><strong style={{fontSize:28}}>Free</strong><ul><li>Up to ≈ 110K Fast/Luna token-equivalent</li><li>Maximum 15 AI requests</li><li>7 days</li><li>Normal mode only</li></ul>{trial?<strong>Current plan</strong>:null}</article><article style={{...panel,border:"1px solid #818cf8"}}><small style={{fontWeight:800,color:"#4f46e5"}}>STARTER</small><h2 style={{marginBottom:6}}>RYTHM AI Starter</h2><strong style={{fontSize:28}}>€9.90 <small style={{fontSize:14,fontWeight:500}}>/ month</small></strong><ul><li>Up to ≈ 6.6M Fast/Luna token-equivalent</li><li>or ≈ 660K Smart/Terra token-equivalent</li><li>Shared monthly allowance across included modes</li><li>Fast + Smart</li><li>Normal mode only</li><li>No rollover</li></ul>{starter?<strong>Current plan</strong>:<a href="/billing" style={{display:"inline-block",textDecoration:"none",borderRadius:10,padding:"11px 14px",background:"#111827",color:"white",fontWeight:800}}>Upgrade to Starter</a>}</article></div><p style={{maxWidth:820,opacity:.65,fontSize:13,lineHeight:1.5}}>Token figures are usage estimates based on the model mix used for plan design; actual token capacity varies with input/output ratio, caching, reasoning and model routing. RYTHM enforces the underlying usage budget server-side.</p></>:null}
      {simple[view]?<><h1>{simple[view]?.title}</h1><div style={{...panel,maxWidth:760}}><p style={{marginTop:0}}>{simple[view]?.description}</p>{view==="usage"?<><p><strong>Plan:</strong> {planName}</p><p><strong>Remaining Fast/Luna allowance:</strong> ≈ {compactTokens(fastRemaining)} tokens</p>{session.modes.includes("auto")?<p><strong>Remaining Smart/Terra allowance:</strong> ≈ {compactTokens(smartRemaining)} tokens</p>:null}{session.plan?.plan_request_limit?<p><strong>Plan request cap:</strong> {session.plan.plan_request_limit}</p>:null}{session.plan?.plan_period_end?<p><strong>Period ends:</strong> {new Date(session.plan.plan_period_end).toLocaleDateString()}</p>:null}<p><strong>Payer:</strong> {session.payerType==="company"?`${session.organization?.name??"Company"} wallet`:"Personal plan"}</p></>:null}{view==="settings"&&session.organization?.role==="owner"?<div style={{marginTop:22}}><h2>Company member AI access</h2><p>Invite a member without requiring their own payment method. Assigned AI usage is paid from the company wallet.</p><CompanyMemberInviteForm/></div>:null}</div></>:null}
    </main>
    {upgrade?<div role="dialog" aria-modal="true" aria-labelledby="ai-upgrade-title" style={{position:"fixed",inset:0,zIndex:100,display:"grid",placeItems:"center",padding:20,background:"rgba(15,23,42,.5)"}} onClick={()=>setUpgrade(null)}><div style={{...panel,width:"min(460px,100%)",boxShadow:"0 30px 80px rgba(15,23,42,.28)"}} onClick={e=>e.stopPropagation()}><h2 id="ai-upgrade-title" style={{marginTop:0}}>{upgrade.title}</h2><p style={{lineHeight:1.55}}>{upgrade.copy}</p><div style={{display:"flex",gap:10,justifyContent:"flex-end",flexWrap:"wrap"}}><button type="button" onClick={()=>setUpgrade(null)} style={{border:"1px solid #cbd5e1",background:"white",borderRadius:10,padding:"10px 13px",fontWeight:700}}>Keep current mode</button><button type="button" onClick={()=>{setUpgrade(null);setView("billing")}} style={{border:0,background:"#111827",color:"white",borderRadius:10,padding:"10px 13px",fontWeight:800}}>View token plans</button></div></div></div>:null}
    <style jsx>{`.ai-mobile-menu{display:none;position:fixed;right:18px;bottom:18px;z-index:42;border:0;border-radius:999px;padding:12px 15px;background:#111827;color:white}.ai-backdrop{display:none}@media(max-width:860px){.ai-shell{display:block!important}.ai-mobile-menu{display:block}.ai-sidebar{position:fixed!important;left:0;top:0;width:min(86vw,310px);transform:translateX(-105%);transition:transform .2s ease;box-shadow:0 24px 70px rgba(15,23,42,.32)}.mobile-open .ai-sidebar{transform:translateX(0)}.ai-backdrop{position:fixed;inset:0;z-index:25;border:0;background:rgba(15,23,42,.45)}.mobile-open .ai-backdrop{display:block}}`}</style>
  </div>;
}
