"use client";
import { useState } from "react";
type Message={role:"user"|"assistant";content:string};
export default function GuestAIClient(){ const [active,setActive]=useState(false); const [code,setCode]=useState(""); const [conversationId,setConversationId]=useState<string|null>(null); const [prompt,setPrompt]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  async function activate(){setBusy(true);setError(null);try{const r=await fetch("/api/ai-workspace/guest/activate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Activation failed");setConversationId(j.conversationId);setActive(true);setCode("");}catch(e){setError(e instanceof Error?e.message:"Activation failed");}finally{setBusy(false);}}
  async function send(){const text=prompt.trim();if(!text||busy)return;setPrompt("");setMessages(v=>[...v,{role:"user",content:text}]);setBusy(true);try{const r=await fetch("/api/ai-workspace/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:text,conversationId,mode:"auto",promptProfile:"normal",requestKey:crypto.randomUUID()})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Request failed");setConversationId(j.conversationId);setMessages(v=>[...v,{role:"assistant",content:j.message}]);}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy(false);}}
  async function logout(){await fetch("/api/ai-workspace/guest/logout",{method:"POST"});setActive(false);setMessages([]);setConversationId(null);}
  if(!active)return <main style={{maxWidth:620,margin:"80px auto",padding:24}}><h1>RYTHM AI Guest</h1><p>Enter the one-time Guest Code provided by your RYTHM administrator.</p><input value={code} onChange={e=>setCode(e.target.value)} placeholder="RYTHM-…" style={{width:"100%",padding:12}}/><button onClick={activate} disabled={busy||!code.trim()} style={{marginTop:12,padding:"10px 16px"}}>Activate</button>{error?<p role="alert">{error}</p>:null}</main>;
  return <main style={{maxWidth:860,margin:"40px auto",padding:24}}><header style={{display:"flex",justifyContent:"space-between"}}><div><h1>RYTHM AI Guest</h1><p>Governed guest workspace</p></div><button onClick={logout}>End session</button></header><section style={{minHeight:420,display:"grid",alignContent:"start",gap:10}}>{messages.map((m,i)=><article key={`${m.role}-${i}`} style={{padding:14,border:"1px solid #ddd",borderRadius:12,whiteSpace:"pre-wrap",marginLeft:m.role==="user"?80:0}}>{m.content}</article>)}</section><div style={{display:"flex",gap:8}}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3} style={{flex:1}}/><button onClick={send} disabled={busy||!prompt.trim()}>Send</button></div>{error?<p role="alert">{error}</p>:null}</main>;
}
