import { NextRequest, NextResponse } from "next/server";
import { createAuthServerClient } from "@/lib/supabase/auth-server";
import { assertSameOrigin } from "@/lib/ai-workspace/guest";
import { ensurePersonalWorkspace, serviceClient } from "@/lib/ai-workspace/service";

type Kind="projects"|"memories"|"prompts"|"skills";
function kind(value:string):value is Kind{return ["projects","memories","prompts","skills"].includes(value);}
async function context(){const auth=await createAuthServerClient();const{data:{user}}=await auth.auth.getUser();if(!user)return null;const client=serviceClient();const personal=await ensurePersonalWorkspace(user.id,client);return{user,client,personal};}
export async function GET(_request:NextRequest,{params}:{params:Promise<{kind:string}>}){const {kind:raw}=await params;if(!kind(raw))return NextResponse.json({error:"RESOURCE_NOT_FOUND"},{status:404});const ctx=await context();if(!ctx)return NextResponse.json({error:"AUTH_REQUIRED"},{status:401});const w=ctx.personal.workspace.id;let query;if(raw==="projects")query=ctx.client.from("aiw_projects").select("id,name,description,created_at").eq("workspace_id",w).eq("archived",false).order("created_at");else if(raw==="memories")query=ctx.client.from("aiw_memories").select("id,project_id,scope,title,content,updated_at").eq("workspace_id",w).order("updated_at",{ascending:false});else if(raw==="prompts")query=ctx.client.from("aiw_saved_prompts").select("id,name,content,updated_at").eq("workspace_id",w).order("updated_at",{ascending:false});else query=ctx.client.from("aiw_skills").select("id,version,name,description,instructions,allowed_tools,enabled,created_at").eq("workspace_id",w).order("created_at",{ascending:false});const result=await query;if(result.error)return NextResponse.json({error:"RESOURCE_LOAD_FAILED"},{status:503});return NextResponse.json({items:result.data??[]},{headers:{"cache-control":"no-store"}});}
export async function POST(request:NextRequest,{params}:{params:Promise<{kind:string}>}){const {kind:raw}=await params;if(!kind(raw))return NextResponse.json({error:"RESOURCE_NOT_FOUND"},{status:404});try{assertSameOrigin(request);}catch{return NextResponse.json({error:"ORIGIN_REJECTED"},{status:403});}const ctx=await context();if(!ctx)return NextResponse.json({error:"AUTH_REQUIRED"},{status:401});const body=await request.json() as Record<string,unknown>;const w=ctx.personal.workspace.id;let payload:Record<string,unknown>;let table:string;if(raw==="projects"){const name=String(body.name??"").trim().slice(0,120);if(!name)return NextResponse.json({error:"NAME_REQUIRED"},{status:400});table="aiw_projects";payload={workspace_id:w,name,description:String(body.description??"").trim().slice(0,2000)};}else if(raw==="memories"){const title=String(body.title??"").trim().slice(0,160),content=String(body.content??"").trim().slice(0,12000);if(!title||!content)return NextResponse.json({error:"MEMORY_FIELDS_REQUIRED"},{status:400});table="aiw_memories";payload={workspace_id:w,project_id:body.projectId?String(body.projectId):null,scope:body.projectId?"project":"personal",title,content,source_type:"user",created_by:ctx.user.id};}else if(raw==="prompts"){const name=String(body.name??"").trim().slice(0,120),content=String(body.content??"").trim().slice(0,24000);if(!name||!content)return NextResponse.json({error:"PROMPT_FIELDS_REQUIRED"},{status:400});table="aiw_saved_prompts";payload={workspace_id:w,name,content};}else{const name=String(body.name??"").trim().slice(0,120),instructions=String(body.instructions??"").trim().slice(0,16000);if(!name||!instructions)return NextResponse.json({error:"SKILL_FIELDS_REQUIRED"},{status:400});table="aiw_skills";payload={workspace_id:w,name,description:String(body.description??"").trim().slice(0,2000),instructions,allowed_tools:[],enabled:true};}const inserted=await ctx.client.from(table).insert(payload).select("*").single();if(inserted.error)return NextResponse.json({error:"RESOURCE_CREATE_FAILED"},{status:503});return NextResponse.json({item:inserted.data},{status:201});}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{kind:string}>}){const {kind:raw}=await params;if(!kind(raw))return NextResponse.json({error:"RESOURCE_NOT_FOUND"},{status:404});try{assertSameOrigin(request);}catch{return NextResponse.json({error:"ORIGIN_REJECTED"},{status:403});}const ctx=await context();if(!ctx)return NextResponse.json({error:"AUTH_REQUIRED"},{status:401});const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"ID_REQUIRED"},{status:400});const w=ctx.personal.workspace.id;if(raw==="projects"){const result=await ctx.client.from("aiw_projects").update({archived:true,updated_at:new Date().toISOString()}).eq("id",id).eq("workspace_id",w);if(result.error)return NextResponse.json({error:"RESOURCE_DELETE_FAILED"},{status:503});}else{const table=raw==="memories"?"aiw_memories":raw==="prompts"?"aiw_saved_prompts":"aiw_skills";const result=await ctx.client.from(table).delete().eq("id",id).eq("workspace_id",w);if(result.error)return NextResponse.json({error:"RESOURCE_DELETE_FAILED"},{status:503});}return NextResponse.json({ok:true});}
