import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Consumer Terms | RYTHM Company OS",
  description: "Consumer-specific terms for RYTHM digital services, one-off AI meetings, subscriptions, payment, withdrawal, and statutory remedies.",
  alternates: { canonical: "/consumer-terms" },
};

export default function ConsumerTermsPage() {
  return (
    <main>
      <section className="public-page-hero enterprise-hero">
        <div><p className="marketing-kicker">CONSUMER TERMS</p><h1>Terms for individual consumers purchasing RYTHM digital services.</h1></div>
        <p>Effective 15 August 2026. These Consumer Terms supplement the general Terms of Service when you purchase for purposes outside your trade, business, craft, or profession. Mandatory consumer law always prevails where it gives you stronger rights.</p>
      </section>
      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">TRADER & CONTRACT</p><h2>Your contract is with Tayyebialashti Yaser E.V.</h2><ul><li>RYTHM Company OS is operated by Tayyebialashti Yaser E.V., 1143 Budapest, Gizella út 35, Hungary.</li><li>Tax number: 48332376-1-42. Individual entrepreneur registration number: 58642889.</li><li>The specific service, total consumer price, payment method, duration and start date shown in checkout form part of your contract.</li><li>These terms, the checkout confirmation, the Privacy Policy and the Consumer Rights notice form the general consumer contract framework.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">ELIGIBILITY</p><h2>Consumer purchases require legal capacity.</h2><ul><li>Self-service consumer purchases are intended for adults who can enter a binding contract.</li><li>If you purchase on behalf of a business or for a professional purpose, the business terms rather than these Consumer Terms may apply.</li><li>Account and billing information must be accurate.</li></ul></div>
      </section>
      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">ONE-OFF AI MEETING</p><h2>A single-session purchase is a bounded digital service.</h2><ul><li>The checkout must identify the meeting scope, included AI roles/usage, session or access period, output, total price and when performance begins.</li><li>A one-off meeting does not create a recurring subscription unless checkout clearly says otherwise and you expressly order that subscription.</li><li>If you ask RYTHM to begin performing a paid service during the statutory withdrawal period, checkout must capture the legally required express request and acknowledgement before performance starts.</li><li>Any loss of a withdrawal right due to full performance is only effective where the statutory conditions are satisfied.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">SUBSCRIPTIONS</p><h2>Recurring plans must state renewal and cancellation clearly.</h2><ul><li>Before ordering, checkout must state the billing interval, recurring total price, contract duration, renewal mechanism, minimum commitment if any, and how to terminate.</li><li>RYTHM will not silently turn a one-off purchase into a recurring paid subscription.</li><li>Cancellation stops future renewal according to the displayed billing terms; it does not remove statutory withdrawal, refund, conformity or termination rights.</li><li>Material changes to a continuing digital service remain subject to mandatory consumer rules.</li></ul></div>
      </section>
      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">PRICE & PAYMENT</p><h2>The consumer checkout total controls the amount due.</h2><ul><li>The final checkout must show the total amount payable including applicable VAT/taxes and unavoidable charges before the order is placed.</li><li>Usage-based AI charges may only apply to consumers where the charging method, unit or cap, and resulting payment obligation are disclosed clearly enough before purchase.</li><li>No payment method is treated as accepted until it is actually offered in checkout.</li><li>Payment-card details must be handled by the selected compliant payment provider; RYTHM should not directly store raw card data.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">ORDER BUTTON</p><h2>The final action must unmistakably create the obligation to pay.</h2><ul><li>The final paid-order control will use wording such as “Order with obligation to pay” or an equivalent formulation that is unambiguous under applicable law.</li><li>A generic “Continue”, “Register” or similarly unclear control must not create a consumer payment obligation.</li></ul></div>
      </section>
      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">WITHDRAWAL</p><h2>Statutory withdrawal rights are preserved.</h2><ul><li>Eligible distance service contracts generally have a 14-day withdrawal period beginning on conclusion of the contract.</li><li>Use <Link href="/withdrawal">Withdraw from contract</Link>, send an unequivocal email to <a href="mailto:legal@rythm-os.com">legal@rythm-os.com</a>, or use another legally valid method.</li><li>If you request performance to begin during the withdrawal period, the consequences are governed by mandatory law and the disclosure shown before you order.</li><li>Where a statutory refund is due, it is processed within the applicable legal deadline and by the required method.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">CONFORMITY & REMEDIES</p><h2>Your statutory digital-service remedies remain intact.</h2><ul><li>RYTHM must supply the contracted digital service and necessary updates in conformity with mandatory consumer law.</li><li>If the service is defective or does not conform, you may have rights to correction/bringing into conformity, price reduction, termination and refund depending on the circumstances.</li><li>No “Beta”, AI limitation, warranty disclaimer or limitation-of-liability wording removes rights or remedies that cannot lawfully be excluded for consumers.</li></ul></div>
      </section>
      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">AI OUTPUT</p><h2>AI assistance has limitations, but consumer rights remain.</h2><ul><li>AI-generated output can be inaccurate, incomplete or unsuitable and should be reviewed before consequential use.</li><li>RYTHM does not promise that AI output constitutes professional legal, medical, financial or other regulated advice.</li><li>This product limitation does not excuse a failure to provide the digital service as contracted or remove mandatory legal remedies.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">PRIVACY</p><h2>Personal data remains governed by GDPR and the Privacy Policy.</h2><ul><li>Read the <Link href="/privacy">Privacy Policy</Link> and <Link href="/ai-transparency">AI Transparency notice</Link>.</li><li>Consumer contractual rights concerning non-personal content created or supplied while using a digital service are handled separately from GDPR personal-data rights.</li></ul></div>
      </section>
      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">COMPLAINTS & ADR</p><h2>Contact us first; independent dispute resolution remains available.</h2><ul><li>Consumer complaints: <a href="mailto:support@rythm-os.com">support@rythm-os.com</a> or <a href="mailto:legal@rythm-os.com">legal@rythm-os.com</a>.</li><li>Written complaints are answered in accordance with the statutory Hungarian complaint-handling deadline.</li><li>Consumers may use the competent conciliation body; Budapest Conciliation Board details are listed on the <Link href="/consumer-rights">Consumer Rights</Link> page.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">LAW & JURISDICTION</p><h2>Hungarian law does not take away mandatory protections in your home country.</h2><ul><li>Hungarian law is the default contractual law for RYTHM consumer contracts.</li><li>If mandatory consumer law in your country of habitual residence protects you despite this choice of law, those protections remain unaffected.</li><li>Nothing in these Terms forces a consumer to give up a court or jurisdiction right that applicable law makes mandatory.</li></ul></div>
      </section>
    </main>
  );
}
