import {createHmac,timingSafeEqual} from "node:crypto";
import {NextRequest,NextResponse} from "next/server";
import {createBillingAdminClient} from "@/lib/supabase/billing-admin";
import {redactSecretText} from "@/lib/security/redaction";
export const runtime="nodejs";
function verify(body:string,header:string,secret:string){const parts=header.split(",").map(x=>x.split("="));const t=parts.find(x=>x[0]==="t")?.[1];const sigs=parts.filter(x=>x[0]==="v1").map(x=>x[1]);if(!t||!sigs.length)return false;if(Math.abs(Date.now()/1000-Number(t))>300)return false;const expected=createHmac("sha256",secret).update(`${t}.${body}`).digest("hex");return sigs.some(sig=>{try{return timingSafeEqual(Buffer.from(expected,"hex"),Buffer.from(sig,"hex"));}catch{return false;}});}
const iso=(v:any)=>v?new Date(Number(v)*1000).toISOString():null;
export async function POST(req:NextRequest){const secret=process.env.STRIPE_WEBHOOK_SECRET;const signature=req.headers.get("stripe-signature")??"";const body=await req.text();if(!secret||!verify(body,signature,secret))return NextResponse.json({error:"Invalid webhook signature"},{status:400});const admin=createBillingAdminClient();if(!admin)return NextResponse.json({error:"Billing service unavailable"},{status:503});let event:any;try{event=JSON.parse(body);}catch{return NextResponse.json({error:"Invalid payload"},{status:400});}const obj=event?.data?.object??{};const organizationId=obj?.metadata?.organization_id??obj?.subscription_details?.metadata?.organization_id??null;const inserted=await admin.from("billing_webhook_events").insert({provider:"stripe",provider_event_id:event.id,event_type:event.type,organization_id:organizationId,object_id:obj.id,payload:{id:event.id,type:event.type,created:event.created,object_id:obj.id},processing_status:"processing",attempts:1});if(inserted.error?.code==="23505")return NextResponse.json({received:true,duplicate:true});if(inserted.error)return NextResponse.json({error:"Webhook ledger failure"},{status:500});try{if(event.type==="checkout.session.completed"){const org=obj.metadata?.organization_id??obj.client_reference_id;await admin.from("billing_checkout_sessions").update({status:"complete",updated_at:new Date().toISOString()}).eq("provider_session_id",obj.id);if(org&&obj.customer)await admin.from("billing_accounts").upsert({organization_id:org,provider:"stripe",provider_customer_id:obj.customer,updated_at:new Date().toISOString()},{onConflict:"organization_id"});}
if(event.type.startsWith("customer.subscription.")){const org=obj.metadata?.organization_id;if(org){const status=event.type==="customer.subscription.deleted"?"canceled":obj.status;await admin.from("billing_subscriptions").upsert({organization_id:org,provider:"stripe",provider_subscription_id:obj.id,provider_customer_id:obj.customer,status,currency:obj.currency??"eur",current_period_start:iso(obj.current_period_start),current_period_end:iso(obj.current_period_end),cancel_at_period_end:Boolean(obj.cancel_at_period_end),canceled_at:iso(obj.canceled_at),trial_end:iso(obj.trial_end),latest_provider_invoice_id:typeof obj.latest_invoice==="string"?obj.latest_invoice:obj.latest_invoice?.id??null,metadata:obj.metadata??{},updated_at:new Date().toISOString()},{onConflict:"provider_subscription_id"});}}
if(event.type==="invoice.paid"||event.type==="invoice.payment_failed"){const org=obj.subscription_details?.metadata?.organization_id??obj.parent?.subscription_details?.metadata?.organization_id;const subId=typeof obj.subscription==="string"?obj.subscription:obj.parent?.subscription_details?.subscription;if(org){const {data:sub}=subId?await admin.from("billing_subscriptions").select("id").eq("provider_subscription_id",subId).maybeSingle():{data:null};const pi=typeof obj.payment_intent==="string"?obj.payment_intent:obj.payment_intent?.id??null;await admin.from("billing_payments").upsert({organization_id:org,subscription_id:sub?.id??null,provider:"stripe",provider_payment_intent_id:pi,provider_invoice_id:obj.id,amount:Number(obj.amount_paid??obj.amount_due??0)/100,currency:String(obj.currency??"eur").toUpperCase(),status:event.type==="invoice.paid"?"succeeded":"failed",paid_at:event.type==="invoice.paid"?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:"provider_payment_intent_id"});if(event.type==="invoice.paid"){const amount=Number(obj.amount_paid??0)/100;const existing=await admin.from("finance_transactions").select("id").eq("organization_id",org).eq("provider_payment_id",pi??obj.id).maybeSingle();if(!existing.data&&amount>0)await admin.from("finance_transactions").insert({organization_id:org,transaction_type:"revenue",status:"posted",category:"subscription",description:`Stripe invoice ${obj.number??obj.id}`,amount,currency:String(obj.currency??"eur").toUpperCase(),occurred_on:new Date().toISOString().slice(0,10),counterparty_name:obj.customer_name??null,source_type:"stripe_invoice",provider_payment_id:pi??obj.id});}}}
if(event.type==="charge.refunded"){const pi=typeof obj.payment_intent==="string"?obj.payment_intent:obj.payment_intent?.id;if(pi)await admin.from("billing_payments").update({refunded_amount:Number(obj.amount_refunded??0)/100,status:Number(obj.amount_refunded??0)>=Number(obj.amount??0)?"refunded":"partially_refunded",updated_at:new Date().toISOString()}).eq("provider_payment_intent_id",pi);}
await admin.from("billing_webhook_events").update({processing_status:"processed",processed_at:new Date().toISOString()}).eq("provider_event_id",event.id).eq("provider","stripe");return NextResponse.json({received:true});}catch(e){await admin.from("billing_webhook_events").update({processing_status:"failed",last_error:redactSecretText(e)}).eq("provider_event_id",event.id).eq("provider","stripe");return NextResponse.json({error:"Webhook processing failed"},{status:500});}}
