import type { Metadata } from "next";
import Link from "next/link";
import { createPublicMetadata } from "@/lib/seo/site";

export const metadata: Metadata = createPublicMetadata("/dpa");

export default function DpaPage() {
  return (
    <main>
      <section className="public-page-hero enterprise-hero">
        <div><p className="marketing-kicker">DATA PROCESSING ADDENDUM</p><h1>GDPR processing terms for customer personal data handled by RYTHM.</h1></div>
        <p>Effective 14 August 2026. This Public Beta DPA is intended to apply where a customer acts as controller and Tayyebialashti Yaser E.V. / RYTHM Company OS acts as processor for personal data submitted to the service. A signed enterprise agreement or negotiated DPA controls where it expressly replaces these terms.</p>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">ROLES & INSTRUCTIONS</p><h2>Customer determines the purpose; RYTHM processes on documented instructions.</h2><ul><li>The customer is responsible for determining lawful purposes, legal bases, permitted users, and the categories of personal data submitted to RYTHM.</li><li>RYTHM processes customer personal data only to provide, secure, support, and maintain the contracted service, to follow documented customer configuration and instructions, or where Union or Member State law requires otherwise.</li><li>The Terms, applicable order, product configuration, support instructions, and this DPA together constitute documented processing instructions unless the parties agree otherwise in writing.</li><li>RYTHM will inform the customer if, in its reasonable view, an instruction infringes applicable data-protection law, unless prohibited from doing so by law.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">CONFIDENTIALITY & SECURITY</p><h2>Access is limited to authorized processing.</h2><ul><li>Persons authorized to process customer personal data must be subject to an appropriate duty of confidentiality.</li><li>RYTHM applies technical and organizational measures appropriate to the current Public Beta risk profile, including authenticated access, tenant-aware authorization, database row-level security, protected server-side secrets, audit/event controls, and governed AI execution boundaries.</li><li>Security controls are reviewed as the product, threat model, and customer use cases evolve.</li><li>Customers remain responsible for account hygiene, user permissions, lawful data submission, and selecting an appropriate deployment for sensitive or regulated data.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">SUBPROCESSORS</p><h2>RYTHM may use vetted infrastructure providers.</h2><ul><li>The current Public Beta subprocessor register is maintained at <Link href="/subprocessors">/subprocessors</Link>.</li><li>RYTHM remains responsible for imposing data-protection obligations on subprocessors that are appropriate to the processing they perform on RYTHM's behalf.</li><li>Where an executed order grants a customer advance-notice or objection rights for new subprocessors, those negotiated terms apply.</li><li>Customer-authorized integrations outside the standard RYTHM stack may require a separate data-protection review.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">INTERNATIONAL TRANSFERS</p><h2>Restricted transfers require a lawful transfer mechanism.</h2><ul><li>Where GDPR Chapter V applies to a transfer of customer personal data, RYTHM will rely on an applicable lawful mechanism made available by the relevant processing arrangement, such as an adequacy decision or Standard Contractual Clauses where appropriate.</li><li>Deployment-specific transfer requirements should be reviewed before regulated or highly sensitive workflows are activated.</li><li>RYTHM does not represent that all data remains exclusively within Hungary or the EEA unless an applicable written order expressly provides that commitment.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">DATA-SUBJECT REQUESTS</p><h2>RYTHM assists with applicable GDPR rights requests.</h2><ul><li>Taking into account the nature of processing, RYTHM will provide reasonable assistance to enable the customer to respond to requests for access, correction, deletion, restriction, objection, or portability where the relevant data is processed by RYTHM.</li><li>Requests directed to RYTHM can be submitted through <Link href="/data-requests">Data Requests</Link> or by email to <a href="mailto:privacy@rythm-os.com">privacy@rythm-os.com</a>.</li><li>Identity, organization ownership, and scope may be verified before data is disclosed, exported, corrected, or deleted.</li><li>RYTHM may preserve data where retention is required by applicable law or necessary to establish, exercise, or defend legal claims.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">INCIDENTS</p><h2>Personal-data incidents are escalated without undue delay.</h2><ul><li>RYTHM will notify an affected customer without undue delay after becoming aware of a confirmed personal-data breach involving customer personal data processed by RYTHM, where notification is required to support the customer's GDPR obligations.</li><li>Available information will include the nature of the incident, affected data or systems, likely consequences where known, containment/remediation actions, and a contact for follow-up.</li><li>Notification does not constitute an admission of fault or liability.</li><li>Customers remain responsible for controller-side regulatory and data-subject notifications applicable to their processing.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">RETURN, DELETION & RETENTION</p><h2>Customer data is not retained indefinitely by default.</h2><ul><li>On valid customer instruction or termination, RYTHM will delete or return customer personal data where reasonably available, subject to legal retention duties, security evidence, backup lifecycle, and legitimate legal-claim requirements.</li><li>Operational deletion and export requests are handled through the documented privacy-request workflow.</li><li>Residual backup copies may remain until the applicable backup rotation expires and are not restored into active use except for legitimate recovery purposes.</li><li>Retention periods are reviewed against the data category, service need, risk, and applicable legal obligations.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">AUDIT & ASSISTANCE</p><h2>RYTHM supports reasonable compliance verification.</h2><ul><li>RYTHM will provide information reasonably necessary to demonstrate compliance with the processor obligations applicable to the contracted processing.</li><li>Where proportionate, RYTHM may satisfy audit requests through current security documentation, architecture evidence, policies, logs, questionnaires, or third-party reports before agreeing to intrusive testing.</li><li>On-site or custom audits require reasonable advance notice, confidentiality protections, scope controls, and must not compromise other customers, security, or service availability.</li><li>RYTHM will provide reasonable assistance with DPIAs and supervisory-authority consultation when the processing performed by RYTHM makes such assistance relevant.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">PROCESSING DETAILS</p><h2>Annex A — current Public Beta processing description.</h2><ul><li><strong>Subject matter:</strong> governed AI company/workspace hosting, authentication, organization management, meetings, projects, agents, approvals, support, and enabled AI-assisted operations.</li><li><strong>Duration:</strong> for the customer relationship plus the limited retention and backup lifecycle applicable to the relevant data.</li><li><strong>Nature and purpose:</strong> storage, organization, retrieval, transmission, AI inference when invoked, security logging, support, and deletion/export operations needed to deliver the service.</li><li><strong>Data subjects:</strong> customer users, organization members, customer-authorized contacts, and other individuals whose data the customer lawfully submits.</li><li><strong>Personal-data categories:</strong> identity/contact data, account and membership data, workspace content, meeting/project/agent context, support records, technical/security metadata, and other customer-submitted data permitted by the service.</li><li><strong>Sensitive data:</strong> not approved by default for the Public Beta; customers must obtain an explicit deployment review before intentionally submitting special-category or similarly regulated data.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">TOMS</p><h2>Annex B — baseline technical and organizational measures.</h2><ul><li>Authenticated account access and server-side session validation for protected routes.</li><li>Tenant-aware authorization and database Row Level Security for production application records.</li><li>Server-only handling of privileged service credentials and AI-provider credentials.</li><li>Human-authority boundaries for consequential AI workflows and no default autonomous external action execution.</li><li>Security/audit event infrastructure, operational incident records, and controlled production deployment through source control and CI.</li><li>Ongoing hardening includes authentication abuse controls, API rate limiting, dependency scanning, security headers, backup/restore validation, and formal incident-response testing.</li></ul></div>
      </section>

      <section className="enterprise-contact-section"><div><p className="marketing-kicker">CONTRACTUAL PRIVACY</p><h2>Need an executed or negotiated DPA?</h2><p>For enterprise procurement, regulated processing, or customer-specific security terms, request a signed review before production activation.</p></div><div className="enterprise-contact-card"><h3>Privacy resources</h3><a className="marketing-button" href="mailto:legal@rythm-os.com">Email Legal</a><div className="hero-actions"><Link href="/subprocessors">Subprocessors</Link><Link href="/privacy">Privacy Policy</Link></div></div></section>
    </main>
  );
}
