import type { SupabaseClient } from "@supabase/supabase-js";
import { executeAiRequest } from "@/lib/ai/request-gateway";
import { getRuntimeConfig } from "@/lib/runtime-config";

export type RoadmapTask={key:string;title:string;description:string;priority:number;dependencies:string[];agentId?:string|null;risk:"low"|"medium"|"high"|"critical";requiresApproval:boolean;approvalReason?:string;workWeight:number};
export type RoadmapPhase={id?:string;key:string;order:number;title:string;description:string;milestone:string;weight:number;estimatedDuration:string;deliverables:string[];dependencies:string[];ownerAgentIds:string[];requiredConnections:unknown[];requiredApprovals:unknown[];successCriteria:string[];tasks:RoadmapTask[];status?:string;outcomeProgressPercent?:number|null};
export type ProjectRoadmap={id:string;version:number;status:string;isBaseline:boolean;title:string;summary:string;phases:RoadmapPhase[]};

const list=(v:unknown)=>Array.isArray(v)?v:[];
const str=(v:unknown,f="")=>typeof v==="string"?v:f;
const num=(v:unknown,f=0)=>typeof v==="number"&&Number.isFinite(v)?v:f;
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const cleanJson=(value:string)=>{const s=value.replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/```\s*$/i,"").trim();try{return JSON.parse(s);}catch{const a=s.indexOf("{");const b=s.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1).replace(/,\s*([}\]])/g,"$1"));throw new Error("Roadmap intelligence returned invalid JSON.");}};

function normalizeWeights(phases:RoadmapPhase[]){const total=phases.reduce((s,p)=>s+Math.max(0,p.weight),0);if(!phases.length)return phases;if(total<=0){const each=100/phases.length;return phases.map((p,i)=>({...p,weight:i===phases.length-1?100-each*(phases.length-1):each}));}let used=0;return phases.map((p,i)=>{const weight=i===phases.length-1?100-used:Number(((p.weight/total)*100).toFixed(2));used+=weight;return {...p,weight};});}

export function calculateWeightedRoadmapProgress(phases:Array<{weight:number;progressPercent:number;outcomeProgressPercent?:number|null}>){const total=phases.reduce((s,p)=>s+Math.max(0,p.weight),0);if(!total)return {executionProgress:0,outcomeProgress:null as number|null};const execution=phases.reduce((s,p)=>s+Math.max(0,p.weight)*clamp(p.progressPercent),0)/total;const outcomePhases=phases.filter(p=>p.outcomeProgressPercent!=null);const outcomeWeight=outcomePhases.reduce((s,p)=>s+Math.max(0,p.weight),0);const outcome=outcomeWeight?outcomePhases.reduce((s,p)=>s+Math.max(0,p.weight)*clamp(Number(p.outcomeProgressPercent)),0)/outcomeWeight:null;return {executionProgress:Math.round(execution),outcomeProgress:outcome==null?null:Math.round(outcome)};}

export async function getApprovedProjectRoadmap(supabase:SupabaseClient,organizationId:string,projectId:string):Promise<ProjectRoadmap|null>{
  const roadmap=await supabase.from("project_roadmaps").select("id,version,status,is_baseline,title,summary").eq("organization_id",organizationId).eq("project_id",projectId).eq("status","approved").eq("is_baseline",true).order("version",{ascending:false}).limit(1).maybeSingle();
  if(!roadmap.data)return null;
  const phases=await supabase.from("project_roadmap_phases").select("*").eq("roadmap_id",roadmap.data.id).order("phase_order");
  return {id:roadmap.data.id,version:roadmap.data.version,status:roadmap.data.status,isBaseline:roadmap.data.is_baseline,title:roadmap.data.title,summary:roadmap.data.summary,phases:(phases.data??[]).map((p:any)=>({id:p.id,key:p.phase_key,order:p.phase_order,title:p.title,description:p.description,milestone:p.milestone??"",weight:Number(p.weight),estimatedDuration:p.estimated_duration??"",deliverables:p.deliverables??[],dependencies:p.dependencies??[],ownerAgentIds:p.owner_agent_ids??[],requiredConnections:p.required_connections??[],requiredApprovals:p.required_approvals??[],successCriteria:p.success_criteria??[],tasks:p.tasks??[],status:p.status,outcomeProgressPercent:p.outcome_progress_percent==null?null:Number(p.outcome_progress_percent)}))};
}

export async function getLatestProjectRoadmap(supabase:SupabaseClient,organizationId:string,projectId:string):Promise<ProjectRoadmap|null>{
  const roadmap=await supabase.from("project_roadmaps").select("id,version,status,is_baseline,title,summary").eq("organization_id",organizationId).eq("project_id",projectId).order("version",{ascending:false}).limit(1).maybeSingle();
  if(!roadmap.data)return null;
  const phases=await supabase.from("project_roadmap_phases").select("*").eq("roadmap_id",roadmap.data.id).order("phase_order");
  return {id:roadmap.data.id,version:roadmap.data.version,status:roadmap.data.status,isBaseline:roadmap.data.is_baseline,title:roadmap.data.title,summary:roadmap.data.summary,phases:(phases.data??[]).map((p:any)=>({id:p.id,key:p.phase_key,order:p.phase_order,title:p.title,description:p.description,milestone:p.milestone??"",weight:Number(p.weight),estimatedDuration:p.estimated_duration??"",deliverables:p.deliverables??[],dependencies:p.dependencies??[],ownerAgentIds:p.owner_agent_ids??[],requiredConnections:p.required_connections??[],requiredApprovals:p.required_approvals??[],successCriteria:p.success_criteria??[],tasks:p.tasks??[],status:p.status,outcomeProgressPercent:p.outcome_progress_percent==null?null:Number(p.outcome_progress_percent)}))};
}

export async function createProjectRoadmapDraft(supabase:SupabaseClient,organizationId:string,projectId:string,userId:string){
  const [project,scope,readiness,agents,existing]=await Promise.all([
    supabase.from("projects").select("id,name,project_code,project_type,description,objective,priority,target_date,constraints,success_criteria,autonomy_mode").eq("organization_id",organizationId).eq("id",projectId).single(),
    supabase.from("project_scope_versions").select("*").eq("organization_id",organizationId).eq("project_id",projectId).order("version",{ascending:false}).limit(1).maybeSingle(),
    supabase.from("project_readiness_assessments").select("*").eq("organization_id",organizationId).eq("project_id",projectId).order("created_at",{ascending:false}).limit(1).maybeSingle(),
    supabase.from("project_agents").select("agent_id,assignment_role,status,agents(id,agent_code,display_name,name,role_title,purpose)").eq("organization_id",organizationId).eq("project_id",projectId),
    supabase.from("project_roadmaps").select("version,status,id").eq("organization_id",organizationId).eq("project_id",projectId).order("version",{ascending:false}).limit(1).maybeSingle(),
  ]);
  if(project.error||!project.data)throw new Error("Project not found.");
  if(existing.data&&["draft","in_review"].includes(existing.data.status)){const found=await getLatestProjectRoadmap(supabase,organizationId,projectId);if(found)return found;}
  const config=getRuntimeConfig();if(!config.openAIConfigured||!config.dryRunModel)throw new Error("Roadmap generation requires the configured RYTHM AI Gateway provider.");
  const context={project:project.data,scope:scope.data??null,readiness:readiness.data??null,available_agents:(agents.data??[]).map((r:any)=>{const a=Array.isArray(r.agents)?r.agents[0]:r.agents;return {id:r.agent_id,assignment:r.assignment_role,name:a?.display_name||a?.name,role:a?.role_title,purpose:a?.purpose};})};
  const response=await executeAiRequest({organizationId,actor:{type:"system"},context:{projectId},feature:"internal.unspecified",systemInstructions:"You are the RYTHM Project Roadmap Architect. Build a goal-specific, realistic business roadmap that can become an execution baseline. Do not equate setup tasks with project completion. Long-running outcome work such as SEO monitoring, ranking/indexing validation, campaigns, recruiting pipelines or product adoption must have explicit validation/measurement phases when relevant. Return exactly one JSON object, no markdown.",prompt:`Create the manager-reviewable roadmap for this project. Return {title,summary,phases:[{key,title,description,milestone,weight,estimated_duration,deliverables,dependencies,owner_agent_ids,required_connections,required_approvals,success_criteria,tasks:[{key,title,description,priority,dependencies,agent_id,risk,requires_approval,approval_reason,work_weight}]}]}. Phase weights must represent business work and sum to 100. Task work_weight is relative within its phase. Use only available agent IDs. Do not invent access or claim outcomes already achieved. Context: ${JSON.stringify(context).slice(0,43000)}`,mode:"task",maxOutputTokens:8000,timeoutMs:config.agentTimeoutMs,legacyFallback:{provider:"openai",model:config.dryRunModel,reason:"compatibility"},telemetryPolicy:"required"});
  const raw=cleanJson(response.outputText) as Record<string,unknown>;const phaseRows=list(raw.phases).map((item,index)=>{const p=(item&&typeof item==="object"?item:{}) as Record<string,unknown>;const tasks=list(p.tasks).map((item2,taskIndex)=>{const t=(item2&&typeof item2==="object"?item2:{}) as Record<string,unknown>;return {key:str(t.key,`task-${index+1}-${taskIndex+1}`),title:str(t.title,`Task ${taskIndex+1}`),description:str(t.description),priority:Math.max(1,Math.min(5,Math.round(num(t.priority,3)))),dependencies:list(t.dependencies).map(String),agentId:str(t.agent_id)||null,risk:["low","medium","high","critical"].includes(str(t.risk))?str(t.risk) as RoadmapTask["risk"]:"low",requiresApproval:Boolean(t.requires_approval),approvalReason:str(t.approval_reason),workWeight:Math.max(0.1,num(t.work_weight,1))};});return {key:str(p.key,`phase-${index+1}`),order:index+1,title:str(p.title,`Phase ${index+1}`),description:str(p.description),milestone:str(p.milestone),weight:Math.max(0.01,num(p.weight,1)),estimatedDuration:str(p.estimated_duration),deliverables:list(p.deliverables).map(String),dependencies:list(p.dependencies).map(String),ownerAgentIds:list(p.owner_agent_ids).map(String),requiredConnections:list(p.required_connections),requiredApprovals:list(p.required_approvals),successCriteria:list(p.success_criteria).map(String),tasks} satisfies RoadmapPhase;});
  if(!phaseRows.length)throw new Error("Roadmap generation returned no phases.");
  const phases=normalizeWeights(phaseRows);const version=Number(existing.data?.version??0)+1;
  const inserted=await supabase.from("project_roadmaps").insert({organization_id:organizationId,project_id:projectId,version,title:str(raw.title,`${project.data.name} roadmap`),summary:str(raw.summary,"Manager review required before execution."),status:"in_review",is_baseline:false,generated_from:{ai_correlation_id:response.correlationId,scope_version:scope.data?.version??null,readiness_assessment_id:readiness.data?.id??null},created_by_user_id:userId}).select("id,version,status,is_baseline,title,summary").single();
  if(inserted.error||!inserted.data)throw new Error(inserted.error?.message||"Unable to save project roadmap.");
  const rows=phases.map(p=>({organization_id:organizationId,project_id:projectId,roadmap_id:inserted.data.id,phase_key:p.key,phase_order:p.order,title:p.title,description:p.description,milestone:p.milestone||null,weight:p.weight,status:"not_started",deliverables:p.deliverables,dependencies:p.dependencies,owner_agent_ids:p.ownerAgentIds,estimated_duration:p.estimatedDuration||null,required_connections:p.requiredConnections,required_approvals:p.requiredApprovals,success_criteria:p.successCriteria,tasks:p.tasks}));
  const saved=await supabase.from("project_roadmap_phases").insert(rows).select("*");if(saved.error)throw new Error(saved.error.message);
  await supabase.from("projects").update({stage:"roadmap_review",updated_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("id",projectId);
  await supabase.from("project_activity_events").insert({organization_id:organizationId,project_id:projectId,event_type:"project.roadmap.created",headline:`Roadmap v${version} ready for review`,detail:"Execution has not started. Manager approval is required to establish the project baseline.",importance:"attention",correlation_id:response.correlationId});
  return getLatestProjectRoadmap(supabase,organizationId,projectId);
}

export async function approveProjectRoadmap(supabase:SupabaseClient,organizationId:string,projectId:string,roadmapId:string,userId:string){
  const roadmap=await supabase.from("project_roadmaps").select("id,version,status").eq("organization_id",organizationId).eq("project_id",projectId).eq("id",roadmapId).single();if(roadmap.error||!roadmap.data)throw new Error("Roadmap not found.");
  const phases=await supabase.from("project_roadmap_phases").select("id,weight").eq("roadmap_id",roadmapId);if(phases.error||!(phases.data??[]).length)throw new Error("Roadmap has no phases.");const total=(phases.data??[]).reduce((s:any,p:any)=>s+Number(p.weight),0);if(Math.abs(total-100)>0.1)throw new Error(`Roadmap phase weights must total 100. Current total: ${total}.`);
  await supabase.from("project_roadmaps").update({status:"superseded",is_baseline:false,updated_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("project_id",projectId).eq("status","approved").eq("is_baseline",true).neq("id",roadmapId);
  const approved=await supabase.from("project_roadmaps").update({status:"approved",is_baseline:true,approved_by_user_id:userId,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("project_id",projectId).eq("id",roadmapId).select("id,version").single();if(approved.error)throw new Error(approved.error.message);
  await supabase.from("projects").update({stage:"ready_to_execute",progress_percent:0,updated_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("id",projectId);
  await supabase.from("project_activity_events").insert({organization_id:organizationId,project_id:projectId,event_type:"project.roadmap.approved",headline:`Roadmap v${roadmap.data.version} approved as execution baseline`,detail:"Project execution progress will now be measured against this approved weighted roadmap.",importance:"normal"});
  return getApprovedProjectRoadmap(supabase,organizationId,projectId);
}
