import Link from "next/link";
import { notFound } from "next/navigation";
import { getPlatformAdminContext } from "@/lib/admin/authorization";
import { getCustomer, display, date, product } from "@/lib/admin/customers";
export const dynamic = "force-dynamic";
export default async function CustomerPage({ params }: { params: Promise<{ id: string }> }) {
  if (!await getPlatformAdminContext()) return null;
  const data = await getCustomer((await params).id);
  if (!data) notFound();
  const { company: c, entitlement: e } = data;
  const owner = data.users.find(u => u.user_id === c.owner_user_id);
  const nameOf = (id: string | null) => id ? data.users.find(u => u.user_id === id)?.name || id : "Not recorded";
  const active = data.agents.filter(a => a.agent_status === "enabled" && a.enabled).length;
  const archived = data.agents.filter(a => a.agent_status === "archived").length;
  const sections = ["Overview", "Users", "Agents", "Products", "Integrations", "Usage", ...(data.billing.length ? ["Billing"] : []), "Activity", "Security"];
  return <main className="admin-studio customer-console">
    <section className="admin-hero"><div><Link href="/admin/customers">← Customer companies</Link><p className="admin-kicker">CUSTOMER ACCOUNT / {c.status}</p><h1>{c.name}</h1><p>{c.id}</p></div><span className="admin-status">Read-only platform view</span></section>
    <nav className="customer-section-nav" aria-label="Company details">{sections.map(s => <a href={`#${s.toLowerCase()}`} key={s}>{s}</a>)}</nav>
    <section className="admin-metrics"><article><span>Users</span><strong>{data.users.filter(u => u.membership_status === "active").length}</strong><small>{data.users.length} total memberships</small></article><article><span>Agents</span><strong>{data.agents.length}</strong><small>{active} enabled · {data.agents.length - active - archived} disabled · {archived} archived</small></article><article><span>Integrations</span><strong>{data.integrations.length}</strong><small>{data.integrations.filter(i => i.status === "connected" && i.enabled).length} connected and enabled</small></article><article><span>Product</span><strong>{product(e?.product_code)}</strong><small>{display(e?.plan_code)}</small></article></section>
    <section id="overview" className="admin-panel"><h2>Overview</h2><dl className="customer-facts">{[
      ["Company", c.name], ["Organization ID", c.id], ["Status", c.status], ["Website", c.website_url], ["Country", c.country_code], ["Timezone", c.timezone], ["Owner", owner?.name], ["Owner email", owner?.email], ["Primary email", c.primary_email], ["Phone", c.primary_phone], ["Industry / business type", null], ["Onboarding (owner profile)", owner?.onboarding_status], ["Created", date(c.created_at)], ["Last recorded activity", date(data.last_activity)], ["Mission", c.mission], ["Vision", c.vision]
    ].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{display(value)}</dd></div>)}</dl></section>
    <section id="users" className="admin-panel"><h2>Users</h2><div className="customer-table-scroll"><table className="customer-table"><thead><tr><th>Name / email</th><th>Role</th><th>Membership</th><th>Joined</th></tr></thead><tbody>{data.users.map(u => <tr key={u.user_id}><td>{display(u.name)}<small>{display(u.email)}</small></td><td>{u.role}</td><td>{u.membership_status}</td><td>{date(u.joined_at)}</td></tr>)}</tbody></table></div>{!data.users.length ? <p>No memberships recorded.</p> : null}</section>
    <section id="agents" className="admin-panel"><h2>AI agents</h2><p>Agent changes are made by authorized company owners in their company&apos;s Agent Studio.</p><div className="customer-agent-grid">{data.agents.map(a => <article key={a.id} className="customer-agent"><div><strong>{a.name}</strong><span className="admin-status">{a.agent_status === "paused" ? "Disabled" : a.agent_status}</span></div><p>{a.role_title} · {display(a.department)}</p><p>{a.purpose}</p><dl><dt>Runtime</dt><dd>{display(a.runtime_provider)} / {display(a.runtime_model)}</dd><dt>Created / creator</dt><dd>{date(a.created_at)} · {nameOf(a.creator_id)}</dd><dt>Recorded run cost (USD)</dt><dd>{a.recorded_cost_usd === null ? "Not recorded" : a.recorded_cost_usd.toFixed(4)}</dd><dt>Last run</dt><dd>{date(a.last_activity)}</dd><dt>Capabilities</dt><dd>{a.allowed_tools?.length ? a.allowed_tools.join(", ") : "None configured"}</dd><dt>Authority / risk</dt><dd>{a.authority_level} / {a.risk_ceiling}</dd></dl><small>{a.agent_code} · {a.id}</small></article>)}</div>{!data.agents.length ? <p>No agents have been created for this company.</p> : null}</section>
    <section id="products" className="admin-panel"><h2>Products & entitlements</h2>{e ? <dl className="customer-facts"><div><dt>Product / plan</dt><dd>{product(e.product_code)} / {e.plan_code}</dd></div><div><dt>Recorded status</dt><dd>{e.status}</dd></div><div><dt>Validity</dt><dd>{date(e.starts_at)} → {date(e.ends_at)}</dd></div><div><dt>Agent capacity</dt><dd>{e.max_active_agents}</dd></div><div><dt>Agent Studio</dt><dd>{e.agent_builder_enabled ? "Enabled" : "Disabled"}</dd></div><div><dt>Create / archive</dt><dd>{e.agent_create_enabled ? "Enabled" : "Disabled"} / {e.agent_archive_enabled ? "Enabled" : "Disabled"}</dd></div></dl> : <p>No product entitlement recorded.</p>}<p>Recorded module use: {data.usage.projects} projects · {data.usage.meetings} Boardroom meetings · {data.integrations.length} integration connections · {data.usage.workspace_ai_requests} AI Workspace requests.</p><p>Entitlements describe access. Recorded usage is shown separately below.</p></section>
    <section id="integrations" className="admin-panel"><h2>Integrations</h2><div className="customer-table-scroll"><table className="customer-table"><thead><tr><th>Provider</th><th>Status</th><th>Last verification</th><th>Last health check</th><th>Last error</th></tr></thead><tbody>{data.integrations.map((i, index) => <tr key={`${i.provider_key}-${index}`}><td>{i.display_name}<small>{i.provider_key}</small></td><td>{i.status}{!i.enabled ? " · disabled" : ""}</td><td>{date(i.last_verified_at)}</td><td>{date(i.last_health_check_at)}</td><td>{date(i.last_error_at)}</td></tr>)}</tbody></table></div>{!data.integrations.length ? <p>No integration connections recorded.</p> : null}<p>These are recorded states, not a live provider health check.</p></section>
    <section id="usage" className="admin-panel"><h2>Recorded usage</h2><dl className="customer-facts"><div><dt>Agent runs (all time)</dt><dd>{data.usage.agent_runs}</dd></div><div><dt>AI Workspace requests (all time)</dt><dd>{data.usage.workspace_ai_requests}</dd></div><div><dt>Recorded agent-run cost (USD)</dt><dd>{data.usage.agent_cost_usd === null ? "Not recorded" : data.usage.agent_cost_usd.toFixed(4)}</dd></div><div><dt>Last agent run</dt><dd>{date(data.usage.last_agent_run)}</dd></div></dl><p>Counts cover the named telemetry sources. Zero means no records in that source; it does not imply zero usage across every module.</p></section>
    {data.billing.length ? <section id="billing" className="admin-panel"><h2>Billing subscriptions</h2>{data.billing.map((b, i) => <p key={i}>{b.status} · {b.currency} · {date(b.current_period_start)} → {date(b.current_period_end)}{b.cancel_at_period_end ? " · Cancels at period end" : ""}</p>)}</section> : null}
    <section id="activity" className="admin-panel"><h2>Recent audit activity</h2><p>Latest {data.activity.length} events; administrative reads are included.</p><div className="customer-table-scroll"><table className="customer-table"><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Target</th></tr></thead><tbody>{data.activity.map(a => <tr key={a.id}><td>{date(a.created_at)}</td><td>{a.event_type}</td><td>{a.actor_agent_id ? data.agents.find(agent => agent.id === a.actor_agent_id)?.name ?? a.actor_agent_id : nameOf(a.actor_user_id)}</td><td>{a.object_type}<small>{display(a.object_id)}</small></td></tr>)}</tbody></table></div>{!data.activity.length ? <p>No audit activity recorded.</p> : null}</section>
    <section id="security" className="admin-panel"><h2>Security</h2><p>This view requires the RYTHM platform-admin allowlist. Access is audited, and credentials are excluded. Viewing this company does not switch your active workspace or grant company-owner permissions.</p></section>
  </main>;
}
