import crypto from "node:crypto";
import { NextResponse } from "next/server";
import { isOrganizationEntitlementActive, resolveOrganizationContext } from "@/lib/auth/organization-context";
import {createExecutionServiceClient} from "@/lib/integrations/service-runner";
import {maybeHandleAgentOAuthCallback} from "@/lib/integrations/connections/agent-oauth-callback";

type StatePayload={integrationId:string;userId:string;nonce:string;issuedAt:number};
type TokenResponse={access_token?:string;refresh_token?:string;expires_in?:number;scope?:string;token_type?:string;error?:string;error_description?:string};
const REQUIRED_SCOPES=["User.Read","Mail.Read","Calendars.Read"];
function credentials(){return{clientId:process.env.MICROSOFT_365_CLIENT_ID?.trim()||process.env.MICROSOFT_CLIENT_ID?.trim()||"",clientSecret:process.env.MICROSOFT_365_CLIENT_SECRET?.trim()||process.env.MICROSOFT_CLIENT_SECRET?.trim()||"",tenant:process.env.MICROSOFT_365_TENANT_ID?.trim()||process.env.MICROSOFT_TENANT_ID?.trim()||"common"};}
function verifyState(state:string):StatePayload|null{const {clientSecret}=credentials();if(!clientSecret)return null;const [encoded,sig]=state.split(".");if(!encoded||!sig)return null;const expected=crypto.createHmac("sha256",clientSecret).update(encoded).digest("base64url");const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const p=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8")) as StatePayload;if(!p.integrationId||!p.userId||!p.nonce||!Number.isFinite(p.issuedAt)||Date.now()-p.issuedAt>10*60*1000||p.issuedAt>Date.now()+60000)return null;return p;}catch{return null;}}
function cookieMap(request:Request){const raw=request.headers.get("cookie")??"";return new Map(raw.split(";").map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf("=");return i<0?[v,""]:[v.slice(0,i),decodeURIComponent(v.slice(i+1))];}));}
function finish(request:Request,integrationId:string,key:"message"|"error",message:string){const url=new URL(`/integrations/${integrationId}/setup`,request.url);url.searchParams.set(key,message);const r=NextResponse.redirect(url,303);for(const name of ["rythm_m365_state","rythm_m365_integration","rythm_m365_user","rythm_m365_pkce"])r.cookies.set(name,"",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/api/integrations/microsoft-365",maxAge:0});return r;}

export async function GET(request:Request){
  const agentResponse=await maybeHandleAgentOAuthCallback(request,"microsoft_365");if(agentResponse)return agentResponse;
  const url=new URL(request.url);const code=url.searchParams.get("code")?.trim()||"";const state=url.searchParams.get("state")?.trim()||"";const providerError=url.searchParams.get("error")?.trim();const payload=state?verifyState(state):null;const cookies=cookieMap(request);const integrationId=payload?.integrationId||cookies.get("rythm_m365_integration")||"";
  if(providerError)return finish(request,integrationId,"error",`Microsoft authorization was not completed: ${providerError}`);
  if(!payload||!code||cookies.get("rythm_m365_state")!==state||cookies.get("rythm_m365_integration")!==payload.integrationId||cookies.get("rythm_m365_user")!==payload.userId||!cookies.get("rythm_m365_pkce"))return finish(request,integrationId,"error","Microsoft 365 OAuth state validation failed. Start the connection again from RYTHM.");
  const context=await resolveOrganizationContext();if(!context||context.user.id!==payload.userId||context.role!=="owner"||!isOrganizationEntitlementActive(context.entitlement))return finish(request,payload.integrationId,"error","Your RYTHM session changed during Microsoft authorization. Sign in again and retry.");
  const {data:integration}=await context.supabase.from("organization_integrations").select("id,provider_key").eq("id",payload.integrationId).eq("organization_id",context.organizationId).maybeSingle();if(!integration||integration.provider_key!=="microsoft_365")return finish(request,payload.integrationId,"error","This Microsoft 365 connection is no longer valid.");
  const {clientId,clientSecret,tenant}=credentials();if(!clientId||!clientSecret)return finish(request,payload.integrationId,"error","Microsoft 365 OAuth platform credentials are not configured yet.");
  const redirectUri=`${url.origin}/api/integrations/microsoft-365/callback`;const tokenResponse=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,code,redirect_uri:redirectUri,grant_type:"authorization_code",code_verifier:String(cookies.get("rythm_m365_pkce"))}),cache:"no-store",signal:AbortSignal.timeout(20000)});const tokens=await tokenResponse.json().catch(()=>({})) as TokenResponse;
  if(!tokenResponse.ok||!tokens.access_token)return finish(request,payload.integrationId,"error",`Microsoft token exchange failed${tokens.error?`: ${tokens.error}`:"."}`);if(!tokens.refresh_token)return finish(request,payload.integrationId,"error","Microsoft did not return an offline refresh token. Reconnect and approve access again.");
  const granted=(tokens.scope??"").split(/\s+/).filter(Boolean);if(REQUIRED_SCOPES.some(scope=>!granted.includes(scope)))return finish(request,payload.integrationId,"error","Microsoft did not grant the required read-only identity, mail and calendar permissions.");
  const profileResponse=await fetch("https://graph.microsoft.com/v1.0/me?$select=id,displayName,userPrincipalName,mail",{headers:{Authorization:`Bearer ${tokens.access_token}`},cache:"no-store",signal:AbortSignal.timeout(20000)});if(!profileResponse.ok)return finish(request,payload.integrationId,"error","Microsoft authorized the account, but RYTHM could not verify Microsoft Graph access.");
  const profile=await profileResponse.json().catch(()=>({})) as {id?:string;displayName?:string;userPrincipalName?:string;mail?:string};const accountRef=profile.mail||profile.userPrincipalName||profile.id||null;
  const envelope=JSON.stringify({version:1,provider:"microsoft_365",auth_mode:"oauth",access_token:tokens.access_token,refresh_token:tokens.refresh_token,token_type:tokens.token_type||"Bearer",scope:tokens.scope||granted.join(" "),expires_at:new Date(Date.now()+Math.max(60,Number(tokens.expires_in??3600))*1000).toISOString()});const {error:vaultError}=await createExecutionServiceClient().rpc("store_organization_integration_secret_unverified_v1",{target_integration_id:payload.integrationId,secret_value:envelope});if(vaultError)return finish(request,payload.integrationId,"error",`Microsoft credential could not be stored securely: ${vaultError.message}`);
  const now=new Date().toISOString();await context.supabase.from("integration_resources").upsert({organization_id:context.organizationId,integration_id:payload.integrationId,provider_key:"microsoft_365",resource_type:"microsoft_account",resource_id:String(profile.id??accountRef),resource_name:String(profile.displayName??accountRef??"Microsoft 365 account"),resource_metadata:{user_principal_name:profile.userPrincipalName??null},last_verified_at:now,available:true},{onConflict:"integration_id,resource_type,resource_id"});const {error:updateError}=await context.supabase.from("organization_integrations").update({account_ref:accountRef,auth_type:"oauth",status:"connected",enabled:true,granted_scopes:granted,connected_at:now,last_verified_at:now,last_health_check_at:now,metadata:{verification_result:"verified",oauth_flow:"customer_microsoft_365_v2",credential_format:"oauth_token_envelope_v1",setup_state:"verified",resource_count:1,microsoft_user_id:profile.id??null,microsoft_display_name:profile.displayName??null,readonly:true},updated_at:now}).eq("id",payload.integrationId).eq("organization_id",context.organizationId);if(updateError)return finish(request,payload.integrationId,"error",`Microsoft was authorized, but the connection registry could not be updated: ${updateError.message}`);
  await context.supabase.from("audit_events").insert({organization_id:context.organizationId,actor_type:"user",actor_user_id:context.user.id,event_type:"integration.microsoft_365_connected",object_type:"organization_integration",object_id:payload.integrationId,risk_level:"low",payload:{auth_type:"oauth",scopes:granted,account_ref:accountRef}});
  return finish(request,payload.integrationId,"message","Microsoft 365 connected successfully with verified read-only Microsoft Graph access.");
}
