"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createAuthBrowserClient } from "@/lib/supabase/auth-browser";
import { registerCompanyLibraryDocument } from "../../company-library/actions";

const MAX_FILE_SIZE=15*1024*1024;
function safeFileName(name:string){return name.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(0,160)||"document"}

export default function AgentKnowledgeUploader({organizationId,agentCode,agentName,roleTitle,department}:{organizationId:string;agentCode:string;agentName:string;roleTitle:string;department:string|null}){
  const router=useRouter();const [pending,setPending]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");setError("");const form=event.currentTarget;const data=new FormData(form);const file=data.get("file");if(!(file instanceof File)||!file.size){setError("Choose a knowledge file.");return}if(file.size>MAX_FILE_SIZE){setError("Knowledge files are limited to 15 MB.");return}setPending(true);const supabase=createAuthBrowserClient();const storagePath=`${organizationId}/${crypto.randomUUID()}-${safeFileName(file.name)}`;try{const {error:uploadError}=await supabase.storage.from("company-knowledge").upload(storagePath,file,{cacheControl:"3600",upsert:false,contentType:file.type||"application/octet-stream"});if(uploadError)throw new Error(`Private upload failed: ${uploadError.message}`);try{const result=await registerCompanyLibraryDocument({storagePath,fileName:file.name,mimeType:file.type||"application/octet-stream",fileSize:file.size,title:String(data.get("title")??"").trim()||file.name,category:String(data.get("category")??"general"),confidentiality:"internal",allowedDepartments:department?[department]:[],allowedRoleKeywords:[agentCode,agentName,roleTitle]});setMessage(result.status==="ready"?`Knowledge added to ${agentName} (${result.chunkCount??0} indexed chunks).`:"This file is already registered.");form.reset();router.refresh()}catch(registrationError){await supabase.storage.from("company-knowledge").remove([storagePath]);throw registrationError}}catch(uploadError){setError(uploadError instanceof Error?uploadError.message:"Agent knowledge upload failed.")}finally{setPending(false)}}
  return <form onSubmit={submit} className="auth-form" style={{marginTop:14}}><label>Knowledge file<input name="file" type="file" required accept=".pdf,.docx,.pptx,.xlsx,.xls,.csv,.txt,.md,.json,.xml,application/pdf,text/plain,text/csv,application/json,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/></label><label>Title<input name="title" placeholder="Defaults to the file name" maxLength={180}/></label><label>Category<select name="category" defaultValue="general"><option value="general">General</option><option value="brand">Brand</option><option value="product">Product</option><option value="service">Service</option><option value="process">Process</option><option value="operations">Operations</option><option value="analytics">Analytics</option><option value="finance">Finance</option><option value="sales">Sales</option><option value="legal">Legal</option><option value="website">Website</option><option value="other">Other</option></select></label><p style={{color:"#667085",lineHeight:1.55}}>No prompt is required. The file is ingested through the Company Library pipeline and tagged directly to <strong>{agentCode}</strong>. Company-wide knowledge remains available separately.</p>{message?<p className="form-success" role="status">{message}</p>:null}{error?<p className="form-error" role="alert">{error}</p>:null}<button type="submit" disabled={pending}>{pending?"Uploading and indexing…":"Add knowledge to this Agent"}</button></form>
}
