import crypto from "node:crypto";
import {NextResponse} from "next/server";
import {isOrganizationEntitlementActive,resolveOrganizationContext} from "@/lib/auth/organization-context";
import {discoverGoogleResources,googleProfile} from "@/lib/integrations/connections/providers";
import {createExecutionServiceClient} from "@/lib/integrations/service-runner";
import {maybeHandleAgentOAuthCallback} from "@/lib/integrations/connections/agent-oauth-callback";
const SCOPE="https://www.googleapis.com/auth/analytics.readonly";type Payload={integrationId:string;userId:string;projectId?:string;nonce:string;issuedAt:number};
function credentials(){return{clientId:process.env.GOOGLE_WORKSPACE_CLIENT_ID?.trim()||process.env.GOOGLE_CLIENT_ID?.trim()||"",clientSecret:process.env.GOOGLE_WORKSPACE_CLIENT_SECRET?.trim()||process.env.GOOGLE_CLIENT_SECRET?.trim()||""};}
function canonicalOrigin(request:Request){const explicit=process.env.RYTHM_PUBLIC_APP_ORIGIN?.trim();if(explicit)return new URL(explicit).origin;if(process.env.VERCEL_ENV==="production"||process.env.NODE_ENV==="production")return "https://rythm-os.com";return new URL(request.url).origin;}
function cookies(request:Request){const raw=request.headers.get("cookie")??"";return new Map(raw.split(";").map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf("=");return i<0?[v,""]:[v.slice(0,i),decodeURIComponent(v.slice(i+1))];}));}
function verify(state:string){const {clientSecret}=credentials();const [encoded,sig]=state.split(".");if(!clientSecret||!encoded||!sig)return null;const expected=crypto.createHmac("sha256",clientSecret).update(encoded).digest("base64url");if(Buffer.byteLength(sig)!==Buffer.byteLength(expected)||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;try{const value=JSON.parse(Buffer.from(encoded,"base64url").toString()) as Payload;return value.integrationId&&value.userId&&Date.now()-value.issuedAt<600000?value:null;}catch{return null;}}
function finish(request:Request,id:string,projectId:string|undefined,key:"message"|"error",message:string){const url=new URL(`/integrations/${id}/setup`,canonicalOrigin(request));url.searchParams.set(key,message);if(projectId)url.searchParams.set("project",projectId);const response=NextResponse.redirect(url,303);for(const name of ["rythm_ga_state","rythm_ga_integration","rythm_ga_user","rythm_ga_pkce"])response.cookies.set(name,"",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/api/integrations/google-analytics",maxAge:0});return response;}
export async function GET(request:Request){
  const agentResponse=await maybeHandleAgentOAuthCallback(request,"google_analytics");if(agentResponse)return agentResponse;
  const url=new URL(request.url),state=url.searchParams.get("state")??"",code=url.searchParams.get("code")??"",providerError=url.searchParams.get("error");const payload=verify(state),jar=cookies(request),id=payload?.integrationId||jar.get("rythm_ga_integration")||"";
  if(providerError)return finish(request,id,payload?.projectId,"error",`Google authorization was not completed: ${providerError}`);if(!payload||!code||jar.get("rythm_ga_state")!==state||jar.get("rythm_ga_integration")!==payload.integrationId||jar.get("rythm_ga_user")!==payload.userId||!jar.get("rythm_ga_pkce"))return finish(request,id,payload?.projectId,"error","Google Analytics OAuth state validation failed. Start again from RYTHM.");
  const context=await resolveOrganizationContext();if(!context||context.user.id!==payload.userId||context.role!=="owner"||!isOrganizationEntitlementActive(context.entitlement))return finish(request,id,payload.projectId,"error","Your RYTHM session changed during Google authorization.");const connection=await context.supabase.from("organization_integrations").select("id,provider_key").eq("id",id).eq("organization_id",context.organizationId).maybeSingle();if(!connection.data||connection.data.provider_key!=="google_analytics")return finish(request,id,payload.projectId,"error","This Google Analytics connection is no longer valid.");
  const {clientId,clientSecret}=credentials(),redirectUri=`${canonicalOrigin(request)}/api/integrations/google-analytics/callback`;const tokenResponse=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:redirectUri,grant_type:"authorization_code",code_verifier:String(jar.get("rythm_ga_pkce"))}),cache:"no-store",signal:AbortSignal.timeout(20000)});const tokens=await tokenResponse.json().catch(()=>({})) as {access_token?:string;refresh_token?:string;expires_in?:number;scope?:string;token_type?:string;error?:string};if(!tokenResponse.ok||!tokens.access_token||!tokens.refresh_token)return finish(request,id,payload.projectId,"error",`Google token exchange failed${tokens.error?`: ${tokens.error}`:"."}`);if(!(tokens.scope??"").split(/\s+/).includes(SCOPE))return finish(request,id,payload.projectId,"error","Google did not grant read-only Analytics access.");
  let resources;let profile;try{[resources,profile]=await Promise.all([discoverGoogleResources("google_analytics",tokens.access_token),googleProfile(tokens.access_token)]);}catch{return finish(request,id,payload.projectId,"error","Google authorized the account, but RYTHM could not discover GA4 properties.");}const envelope=JSON.stringify({version:1,provider:"google_analytics",access_token:tokens.access_token,refresh_token:tokens.refresh_token,token_type:tokens.token_type||"Bearer",scope:tokens.scope||SCOPE,expires_at:new Date(Date.now()+Math.max(60,Number(tokens.expires_in??3600))*1000).toISOString()});const stored=await createExecutionServiceClient().rpc("store_organization_integration_secret_unverified_v1",{target_integration_id:id,secret_value:envelope});if(stored.error)return finish(request,id,payload.projectId,"error",`Google credential could not be stored securely: ${stored.error.message}`);
  const now=new Date().toISOString();await context.supabase.from("integration_resources").update({available:false}).eq("integration_id",id).eq("organization_id",context.organizationId);if(resources.length){const saved=await context.supabase.from("integration_resources").upsert(resources.map(resource=>({organization_id:context.organizationId,integration_id:id,provider_key:"google_analytics",resource_type:resource.resourceType,resource_id:resource.resourceId,resource_name:resource.resourceName,resource_metadata:resource.metadata??{},last_verified_at:now,available:true})),{onConflict:"integration_id,resource_type,resource_id"});if(saved.error)return finish(request,id,payload.projectId,"error","GA4 properties were discovered but could not be saved.");}
  const updated=await context.supabase.from("organization_integrations").update({account_ref:String(profile.email??""),auth_type:"oauth",status:"connected",enabled:true,granted_scopes:["read.analytics"],connected_at:now,last_verified_at:now,last_health_check_at:now,metadata:{verification_result:"verified",credential_format:"oauth_token_envelope_v1",resource_count:resources.length,readonly:true},updated_at:now}).eq("id",id).eq("organization_id",context.organizationId);if(updated.error)return finish(request,id,payload.projectId,"error",updated.error.message);await context.supabase.from("audit_events").insert({organization_id:context.organizationId,actor_type:"user",actor_user_id:context.user.id,event_type:"integration.google_analytics_connected",object_type:"organization_integration",object_id:id,risk_level:"low",payload:{resource_count:resources.length,scope:"analytics.readonly",redirect_uri:redirectUri}});return finish(request,id,payload.projectId,"message",`Google Analytics connected. ${resources.length} GA4 ${resources.length===1?"property":"properties"} verified.`);
}
