"use client";
import { useRef,useState } from "react";

type Props={organizations:Array<{id:string;name:string}>};
export default function AIWorkspaceGuestCodeForm({organizations}:Props){
  const [code,setCode]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const codeRef=useRef<HTMLInputElement>(null);
  async function create(event:React.FormEvent<HTMLFormElement>){ event.preventDefault(); setMessage(null); setCode(null); const form=new FormData(event.currentTarget); const dollars=Number(form.get("credit")||0); const response=await fetch("/api/admin/ai-workspace/guest-codes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:form.get("organizationId"),label:form.get("label"),initialCreditMicros:Math.round(dollars*1_000_000),perRequestCapMicros:200000,dailyLimitMicros:500000,monthlyLimitMicros:2_000_000,deviceLimit:1,activationLimit:1})}); const data=await response.json(); if(!response.ok){setMessage(data.error||"Create failed");return;} setCode(data.code); setMessage("Guest Code created. It will only be shown in plaintext here."); }
  async function copy(){ if(!code)return; try{ if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(code);}else throw new Error("clipboard unavailable"); setMessage("Copied"); }catch{ try{ const input=codeRef.current; if(!input)throw new Error(); input.focus(); input.select(); if(!document.execCommand("copy"))throw new Error(); setMessage("Copied"); }catch{ setMessage("Copy failed — select manually"); codeRef.current?.focus(); codeRef.current?.select(); } } }
  return <form onSubmit={create} style={{display:"grid",gap:12,maxWidth:620}}><label>Organization<select name="organizationId" required defaultValue="" style={{display:"block",width:"100%",padding:10}}><option value="" disabled>Select organization</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Label<input name="label" required maxLength={120} placeholder="Launch guest" style={{display:"block",width:"100%",padding:10}}/></label><label>Initial AI credit (USD)<input name="credit" type="number" min="0" max="1000" step="0.01" defaultValue="1" style={{display:"block",width:"100%",padding:10}}/></label><button type="submit">Create Guest Code</button>{code?<div><p><strong>Shown once:</strong></p><div style={{display:"flex",gap:8}}><input ref={codeRef} readOnly value={code} style={{flex:1,padding:10}}/><button type="button" onClick={copy}>Copy</button></div></div>:null}{message?<p role="status">{message}</p>:null}</form>;
}
