'use client';
import {useEffect,useRef,useState} from 'react';
import type {Clarification} from '@/lib/company-core/contract';
type Form={questions:Clarification[];answers:Record<string,unknown>;revision:number;status:string;language:string};
export default function CustomerForm({token}:{token:string}){
 const [form,setForm]=useState<Form|null>(null),[answers,setAnswers]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const lock=useRef(false);
 useEffect(()=>{fetch(`/api/customer-forms/${token}`,{cache:'no-store'}).then(r=>r.json()).then(b=>{if(!b.ok)throw new Error(b.error);setForm(b.form);setAnswers(b.form.answers);}).catch(e=>setNotice(e.message));},[token]);
 async function save(submit:boolean){if(lock.current||!form)return;lock.current=true;setBusy(true);setNotice('Saving…');try{const r=await fetch(`/api/customer-forms/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:form.revision,answers,submit})});const b=await r.json();if(!b.ok)throw new Error(b.error);setForm({...form,revision:b.revision,status:submit?'submitted':form.status});setNotice(submit?'Thank you. Your answers were submitted for review.':'Draft saved. Use the same link to resume.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save.');}finally{lock.current=false;setBusy(false);}}
 async function upload(q:Clarification,file:File){if(lock.current)return;lock.current=true;setBusy(true);setNotice('Uploading…');try{const data=new FormData();data.set('file',file);data.set('questionId',q.id);const r=await fetch(`/api/customer-forms/${token}/files`,{method:'POST',body:data});const b=await r.json();if(!b.ok)throw new Error(b.error);setAnswers(v=>({...v,[q.id]:b.file}));setNotice('Uploaded. Save your draft or submit to retain this answer.');}catch(e){setNotice(e instanceof Error?e.message:'Upload failed.');}finally{lock.current=false;setBusy(false);}}
 return <main style={{maxWidth:720,margin:'32px auto',padding:20}} lang={form?.language??'en'}><h1>Project information</h1><p>Please complete the questions below. You can save and return using this link.</p>{form&&form.status!=='submitted'?<form onSubmit={e=>{e.preventDefault();void save(true);}} style={{display:'grid',gap:20}}>{form.questions.filter(q=>!q.condition||answers[q.condition.questionId]===q.condition.equals).map(q=><fieldset key={q.id} disabled={busy} style={{minWidth:0,border:'1px solid #ddd',borderRadius:10,padding:16}}><legend>{q.question}</legend>{q.input_type==='file'?<><input aria-label={q.question} type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(q,file);}}/>{answers[q.id]?<p>File uploaded.</p>:null}</>:q.input_type==='multi_choice'&&Array.isArray(q.options)?q.options.map(o=><label key={String(o)} style={{display:'block',padding:8}}><input type="checkbox" checked={Array.isArray(answers[q.id])&&(answers[q.id] as unknown[]).includes(o)} onChange={e=>{const v=Array.isArray(answers[q.id])?answers[q.id] as unknown[]:[];setAnswers({...answers,[q.id]:e.target.checked?[...v,o]:v.filter(x=>x!==o)});}}/> {String(o)}</label>):Array.isArray(q.options)&&q.options.length?<select aria-label={q.question} value={String(answers[q.id]??'')} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} style={{width:'100%',padding:12}}><option value="">Select…</option>{q.options.map(o=><option key={String(o)} value={String(o)}>{String(o)}</option>)}<option value="unknown">Unknown</option><option value="provide_later">Provide later</option></select>:<textarea aria-label={q.question} value={String(answers[q.id]??'')} maxLength={10000} rows={3} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} style={{width:'100%',boxSizing:'border-box',padding:12}}/>}</fieldset>)}<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><button type="button" disabled={busy} onClick={()=>save(false)}>Save draft</button><button type="submit" disabled={busy}>{busy?'Saving…':'Submit answers'}</button></div></form>:null}<p role="status">{notice|| (form?.status==='submitted'?'Your answers have been submitted for manager review.':'')}</p></main>;
}
