import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {scoreExecutiveEvaluation,EXECUTIVE_SCENARIOS} from '../lib/company-core/executive-evaluation';
import {validateDelegation,validateAnswers,canWaive,executionDisposition,isAgentAvailable,revisionAllowed,hasMatchingCustomerAnswer} from '../lib/company-core/contract';
import {isSensitiveAnalyticsPath} from '../lib/analytics/sensitive-paths';
async function main(){
assert.equal(isSensitiveAnalyticsPath('/customer-forms/'+ 'a'.repeat(64)),true);
assert.equal(isSensitiveAnalyticsPath('/projects'),false);
assert.equal(hasMatchingCustomerAnswer([{source:'customer_form',answer:'no'}],'yes'),false);
assert.equal(hasMatchingCustomerAnswer([{source:'customer_form',answer:'yes'},{source:'customer_form',answer:'no'}],'yes'),false);
assert.equal(hasMatchingCustomerAnswer([{source:'customer_form',answer:'yes'}],'yes'),true);
const db=new PGlite();
await db.exec(`
create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select null::uuid$$;
create table organizations(id uuid primary key,name text,owner_user_id uuid);
create table agents(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id),agent_code text,name text,role_title text,purpose text,enabled boolean,agent_status text,authority_level integer,risk_ceiling text,external_actions_allowed boolean,system_instructions text,skills jsonb,department_id uuid,reports_to_agent_id uuid,created_at timestamptz default now());
create table departments(id uuid primary key,organization_id uuid,manager_agent_id uuid);
create table projects(id uuid primary key,organization_id uuid,status text,stage text,next_required_action text);
create table role_foundations(id uuid primary key,canonical_role text,version text,status text,last_verified_at timestamptz);
create table agent_role_foundation_bindings(id uuid primary key default gen_random_uuid(),organization_id uuid,agent_id uuid,role_foundation_id uuid,foundation_version text,status text);
insert into role_foundations values(gen_random_uuid(),'Executive Orchestrator & AI Chief of Staff','2','active',now());
create table project_proposals(id uuid primary key,status text);
create table project_roadmaps(id uuid primary key,project_id uuid);
create table company_templates(id uuid primary key);
create table project_clarification_requests(id uuid primary key,organization_id uuid,project_id uuid,question_key text,question text,reason text,input_type text,options jsonb,materiality text,status text,answer jsonb);
create table communication_messages(id uuid primary key);create table communication_threads(id uuid primary key);
create table project_task_runs(id uuid primary key default gen_random_uuid(),organization_id uuid,assigned_agent_id uuid,status text,lease_owner text,lease_expires_at timestamptz,next_attempt_at timestamptz,attempt_count integer,waiting_on_approval_id uuid,error_class text,project_id uuid,execution_id uuid,task_key text,title text,dependencies jsonb,idempotency_key text,input jsonb,action_item_id uuid,roadmap_id uuid,roadmap_phase_id uuid,work_weight numeric,unique(organization_id,idempotency_key));
create table tool_execution_requests(id uuid primary key);
create table approval_requests(id uuid primary key default gen_random_uuid(),organization_id uuid,project_id uuid,status text,subject_type text,subject_id uuid,response_note text,title text,summary text,risk_level text,requested_by_agent_id uuid,conditions jsonb);
create table project_executions(id uuid primary key,organization_id uuid,project_id uuid,status text,execution_no integer);
create table organization_template_installations(id uuid primary key,organization_id uuid,template_key text);
`);
await db.exec(readFileSync('supabase/migrations/20261003175455_shared_company_operating_core.sql','utf8'));
const org='00000000-0000-4000-8000-000000000001', other='00000000-0000-4000-8000-000000000002',project='00000000-0000-4000-8000-000000000003',user='00000000-0000-4000-8000-000000000004',account='00000000-0000-4000-8000-000000000005';
await db.query('insert into auth.users values($1)',[user]);
await db.query('insert into organizations(id,name) values($1,$2),($3,$4)',[org,'Advertising',other,'Software']);
for(const [tenant,template] of [[org,'ready_ai_advertising_agency_v1'],[other,'ready_software_company_v1']]){
 await db.query('insert into organization_template_installations values(gen_random_uuid(),$1,$2)',[tenant,template]);
 const first=await db.query('select ensure_company_operating_core_v1($1) as id',[tenant]);const again=await db.query('select ensure_company_operating_core_v1($1) as id',[tenant]);assert.deepEqual(first.rows,again.rows);
}
assert.equal((await db.query('select * from agent_role_foundation_bindings')).rows.length,2,'both templates reuse the validated shared executive foundation');
await db.query("insert into projects values($1,$2,'planning','planning',null,null,'1.0')",[project,org]);
await db.query(`insert into project_budget_accounts(id,organization_id,project_id,category,currency,period_start,period_end,authorized_ceiling,authorized_by_user_id,authorization_evidence) values($1,$2,$3,'media','EUR',current_date,current_date+30,100,$4,'{"manager":true}')`,[account,org,project,user]);
const reserve=(key:string,amount:number,tenant=org)=>db.query('select reserve_project_budget_v1($1,$2,$3,$4) as id',[tenant,account,key,amount]);
const first=await reserve('one',60);assert.deepEqual(first.rows,(await reserve('one',60)).rows);
await assert.rejects(reserve('one',61),/conflict/);
const concurrent=await Promise.allSettled([reserve('two',40),reserve('three',40)]);assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);
await assert.rejects(reserve('foreign',1,other),/not found/);
await db.query("select reconcile_project_budget_v1($1,$2,'uncertain',null,'{}')",[org,(first.rows[0] as {id:string}).id]);await assert.rejects(reserve('still-committed',1),/ceiling/);
await db.query("select reconcile_project_budget_v1($1,$2,'charged',50,'{\"receipt\":\"test\"}')",[org,(first.rows[0] as {id:string}).id]);await reserve('after-receipt',10);
const q='00000000-0000-4000-8000-000000000006';
await db.query("insert into project_clarification_requests(id,organization_id,project_id,question,status,materiality) values($1,$2,$3,'Scope?','open','required')",[q,org,project]);
await db.query("insert into project_proposals(id,status) values($1,'approved')",[q]);
assert.equal((await db.query("select * from claim_project_proposal_bridge_v1($1,'one')",[q])).rows.length,1);
assert.equal((await db.query("select * from claim_project_proposal_bridge_v1($1,'two')",[q])).rows.length,0,'overlapping scheduler cannot translate the same proposal twice');
const token='a'.repeat(64);
await db.query("insert into project_customer_forms(organization_id,project_id,token_hash,clarification_version,questions,expires_at) values($1,$2,$3,1,$4::jsonb,now()+interval '1 day')",[org,project,token,JSON.stringify([{id:q,question:'Scope?'}])]);
await db.query("select save_project_customer_form_v1($1,0,$2::jsonb,false,'[]')",[token,JSON.stringify({[q]:'Website'})]);
await assert.rejects(db.query("select save_project_customer_form_v1($1,0,'{}',false,'[]')",[token]),/changed/);
await db.query("select save_project_customer_form_v1($1,1,$2::jsonb,true,'[]')",[token,JSON.stringify({[q]:'Website'})]);
await assert.rejects(db.query("select save_project_customer_form_v1($1,2,'{}',true,'[]')",[token]),/unavailable/);
assert.equal((await db.query<{matches:boolean}>('select customer_answer_matches_v1($1,$2,$3,$4::jsonb) as matches',[org,project,q,JSON.stringify('Website')])).rows[0].matches,true);
assert.equal((await db.query<{matches:boolean}>('select customer_answer_matches_v1($1,$2,$3,$4::jsonb) as matches',[org,project,q,JSON.stringify('Changed consent')])).rows[0].matches,false);
assert.equal((await db.query<{matches:boolean}>('select customer_answer_matches_v1($1,$2,$3,$4::jsonb) as matches',[other,project,q,JSON.stringify('Website')])).rows[0].matches,false);
const gap=await db.query('select status from project_clarification_requests where id=$1',[q]);assert.equal((gap.rows[0] as {status:string}).status,'open','customer submissions require manager validation');
const director=(await db.query('select executive_director_agent_id as id from organizations where id=$1',[org])).rows[0] as {id:string};
const sourceTask='00000000-0000-4000-8000-000000000008';
await db.query("insert into project_task_runs(id,organization_id,project_id,assigned_agent_id,status,lease_owner,task_key,input) values($1,$2,$3,$4,'running','test-lease','source','{}')",[sourceTask,org,project,director.id]);
const f1=await db.query("select reserve_company_followup_v1($1,'test-lease','check','Check output','Verify precursor output',$2) as id",[sourceTask,director.id]);
const f2=await db.query("select reserve_company_followup_v1($1,'test-lease','check','Check output','Verify precursor output',$2) as id",[sourceTask,director.id]);assert.deepEqual(f1.rows,f2.rows);
const reservedTask=await db.query('select status,waiting_on_approval_id,dependencies from project_task_runs where id=$1',[(f1.rows[0] as {id:string}).id]);assert.equal((reservedTask.rows[0] as {status:string}).status,'waiting_for_approval');assert.deepEqual((reservedTask.rows[0] as {dependencies:string[]}).dependencies,['source']);
await db.query("update agents set agent_status='paused' where id=$1",[director.id]);await assert.rejects(db.query("select reserve_company_followup_v1($1,'test-lease','paused','x','x',$2)",[sourceTask,director.id]),/unavailable/);await db.query("update agents set agent_status='enabled' where id=$1",[director.id]);
await db.query("update projects set stage='clarification' where id=$1",[project]);
assert.equal((await db.query("select * from claim_company_planning_jobs_v1('planner')")).rows.length,0,'required open questions stop planning');
await db.query("update project_clarification_requests set status='answered' where id=$1",[q]);
assert.equal((await db.query("select * from claim_company_planning_jobs_v1('planner')")).rows.length,1,'manager completion automatically makes planning claimable');
assert.equal((await db.query("select * from claim_company_planning_jobs_v1('duplicate')")).rows.length,0,'planning lease prevents duplicate calls');
await db.query("update company_planning_jobs set lease_expires_at=now()-interval '1 minute',attempts=3");
assert.equal((await db.query("select * from claim_company_planning_jobs_v1('exhausted')")).rows.length,0,'planning retries bounded');
await db.query('select reconcile_company_obligations_v1()');
assert.ok((await db.query("select * from project_operating_obligations where obligation_key=$1",['task:'+sourceTask])).rows.length);
const conditional='00000000-0000-4000-8000-000000000009';
await db.query("insert into approval_requests(id,organization_id,project_id,status,subject_type,subject_id,decision_kind) values($1,$2,$3,'pending','project_task',$4,'conditional')",[conditional,org,project,sourceTask]);
await db.query("update project_task_runs set status='queued',waiting_on_approval_id=null where id=$1",[sourceTask]);
await db.query("update approval_requests set status='approved' where id=$1",[conditional]);
assert.equal((await db.query<{status:string}>('select status from project_task_runs where id=$1',[sourceTask])).rows[0].status,'waiting_for_data','conditional gate holds a task even after an earlier trigger removed its waiting approval pointer');
const definitive='00000000-0000-4000-8000-000000000007';
await db.query("insert into approval_requests(id,organization_id,project_id,status,subject_type,subject_id,decision_kind) values($1,$2,$3,'pending','campaign',$1,'definitive')",[definitive,org,project]);
await db.query("update approval_requests set status='rejected',response_note='Do not use this channel' where id=$1",[definitive]);
const decision=await db.query("select evidence->>'decision_kind' as kind from project_operating_obligations where obligation_key=$1",['approval:'+definitive]);assert.equal((decision.rows[0] as {kind:string}).kind,'definitive');
const policies=await db.query("select relname,relrowsecurity from pg_class where relname in ('project_customer_forms','project_budget_accounts','project_operating_obligations')");assert.ok(policies.rows.every((r:any)=>r.relrowsecurity));
await db.exec('set role authenticated');await assert.rejects(db.query('select * from project_customer_forms'),/permission denied/);await assert.rejects(db.query('select reserve_project_budget_v1($1,$2,$3,1)',[org,account,'blocked']),/permission denied/);await db.exec('reset role');
validateDelegation([{key:'a',dependencies:[],agentId:'agent'},{key:'b',dependencies:['a'],agentId:'agent'}],new Set(['agent']));
assert.throws(()=>validateDelegation([{key:'a',dependencies:['b'],agentId:'agent'},{key:'b',dependencies:['a'],agentId:'agent'}],new Set(['agent'])),/cycle/);
assert.throws(()=>validateDelegation([{key:'a',dependencies:['missing'],agentId:'agent'}],new Set(['agent'])),/Missing/);
assert.throws(()=>validateDelegation([{key:'a',dependencies:[],agentId:'foreign'}],new Set(['agent'])),/available/);
assert.equal(isAgentAvailable({id:'a',enabled:true,agent_status:'paused'}),false);
assert.equal(revisionAllowed('definitive'),false);assert.equal(revisionAllowed('cost'),true);
assert.equal(executionDisposition(true,0,0,0,0),'needs_connection');assert.equal(executionDisposition(true,1,0,0,0),'capability_unavailable');assert.equal(executionDisposition(true,1,1,0,0),'needs_execution_review');assert.equal(executionDisposition(false,0,0,0,0),'no_external_action');
const question={id:'q',question:'Consent',reason:'Required',input_type:'select',options:['yes','no'],materiality:'required',omission_permitted:true,consent_required:true};
assert.equal(canWaive(question),false);assert.ok(validateAnswers([question],{q:'unknown'},true).length);assert.ok(validateAnswers([question],{q:'invalid'},true).length);assert.equal(validateAnswers([question],{q:'yes'},true).length,0);
for(const scenario of EXECUTIVE_SCENARIOS){assert.equal(scoreExecutiveEvaluation(scenario.key,{action:scenario.expected,owner:'Executive Director',next_action:'Review decision',spend_authorized:false,external_action_executed:false}).passed,true);assert.equal(scoreExecutiveEvaluation(scenario.key,{action:'spend',spend_authorized:true}).passed,false);}
await db.close();console.log('Shared company core: synthetic SQL ownership, forms, manager review, concurrency, idempotency, budget reconciliation, RLS, dependency and status scenarios passed. No live external actions tested.');

}
main().catch(e=>{console.error(e);process.exit(1);});
