import {readFileSync} from "node:fs";
const read=(path:string)=>readFileSync(path,"utf8");
const expect=(body:string,value:string,label:string)=>{if(!body.includes(value))throw new Error(`${label}: missing ${value}`);};
const expectPattern=(body:string,pattern:RegExp,label:string)=>{if(!pattern.test(body))throw new Error(`${label}: pattern ${pattern} not found`);};
const migration=read("supabase/migrations/20260915103000_customer_connection_platform_phase1.sql");
for(const state of ["not_started","setup_required","authorizing","verifying","connected","needs_attention","reauth_required","revoked","error","disconnected"])expect(migration,`'${state}'`,"truthful lifecycle");
for(const table of ["integration_resources","integration_setup_sessions","project_connection_bindings"])expect(migration,`public.${table}`,"connection model");
expect(migration,"Connected requires a verified provider credential","database fake-success guard");
expect(migration,"store_organization_integration_secret_unverified_v1","Vault storage without fake success");
expect(migration,"metadata->>'verification_result'","verified transition invariant");
for(const field of ["setup_plan","provider_key","connection_id","project_id","resource_requirement","current_step","step_status","user_action_required","human_takeover_reason","resume_token_hash","provider_context","verification_result"])expect(migration,field,"Phase 2-ready setup interface");
const providers=read("lib/integrations/adapters/customer-connections.ts");for(const provider of ["github","vercel","supabase","cloudflare","ahrefs"])expect(providers,`\"${provider}\"`,`${provider} adapter`);for(const method of ["verifyCredential","discoverResources","healthCheck"])expect(providers,method,"provider adapter contract");expect(providers,"https://api.ahrefs.com/v3/subscription-info/limits-and-usage","Ahrefs zero-unit verification endpoint");expect(providers,"api_key_expiration_date","Ahrefs credential expiry evidence");
const setup=read("app/(app)/integrations/[id]/setup/page.tsx");for(const provider of ["google_search_console","google_analytics","google_workspace","microsoft_365"])expect(setup,provider,`${provider} OAuth setup`);expect(setup,'target="_blank"',"new-tab OAuth");expect(setup,"integration_resources","resource discovery picker");expect(setup,"bindCustomerProjectResource","project binding");
const customer=read("app/(app)/integrations/customer-actions.ts");expectPattern(customer,/status\s*:\s*["']setup_required["']/,"local row is not connected");expect(customer,"adapter.verifyCredential(secret)","token verified before connected");expectPattern(customer,/binding_status\s*:\s*["']verified["']/,"verified project binding");expect(customer,"disconnectCustomerConnection","disconnect lifecycle");
const binding=read("app/api/projects/connections/route.ts");expect(binding,'metadata?.verification_result!=="verified"',"API provider verification guard");expect(binding,"integration_resources","API discovered-resource guard");
for(const route of ["google-search-console","google-analytics","microsoft-365"]){const start=read(`app/api/integrations/${route}/connect/route.ts`);const callback=read(`app/api/integrations/${route}/callback/route.ts`);expect(start,"code_challenge","PKCE start");expect(callback,"code_verifier","PKCE callback");expect(start,"authorization_started_at","authorization timestamp");}
const guide=read("app/(app)/integrations/integration-setup-guide.tsx");for(const value of ["sessionStorage","Show me where","Back","Next","Security checkpoint"])expect(guide,value,"persistent guide");
const roadmap=read("app/api/projects/roadmap/route.ts");expect(roadmap,"connectionDependencies","roadmap connection dependency");expect(roadmap,'completion_requires:\"verified_provider_and_bound_resource\"',"roadmap truthful completion");
console.log("Customer Connection Platform Phase 1 architecture and regression validation passed.");