import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "node:fs";
import { buildCompanyChart, type ChartAgent } from "../lib/company-chart";
import CompanyChart from "../components/company-branding/CompanyChart";
(globalThis as typeof globalThis & { React: typeof React }).React = React;
const departments = [{id:"creative",name:"Creative",manager_agent_id:"a"},{id:"accounts",name:"Accounts"}];
const agents: ChartAgent[] = [{id:"a",name:"Director",role_title:"Creative director",department_id:"creative",reports_to_agent_id:null,agent_status:"enabled"},{id:"b",name:"Designer",role_title:"Visual designer",department_id:"creative",reports_to_agent_id:"a",agent_status:"paused"},{id:"c",name:"Strategist",role_title:"Account strategy",department_id:"accounts",reports_to_agent_id:"a",agent_status:"enabled"}];
const members=[{user_id:"human",display_name:"Human CEO",job_title:"CEO",role:"owner",department_id:null,membership_status:"active"}];
const graph=buildCompanyChart(departments,agents,members);
assert.equal(graph.nodes.length,4); assert.equal(graph.edges.length,2);
assert.ok(graph.nodes.find(n=>n.id==="b")!.y>graph.nodes.find(n=>n.id==="a")!.y);
assert.equal(graph.nodes.find(n=>n.id==="human:human")!.reportsTo,"Not recorded");
assert.equal(graph.nodes.find(n=>n.id==="b")!.manager,"Director");
assert.equal(graph.nodes.find(n=>n.id==="c")!.reportsTo,"Director");
assert.equal(buildCompanyChart([],[],[]).nodes.length,0);
assert.equal(buildCompanyChart([],[],[{...members[0],membership_status:"removed"}]).nodes.length,0);
const invalid=buildCompanyChart([],agents.map((a,i)=>({...a,reports_to_agent_id:i===0?"b":i===1?"a":"missing"})),[]);
assert.equal(invalid.nodes.length,3);assert.equal(invalid.issues,3);
assert.ok(invalid.nodes.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y)));
const html=renderToStaticMarkup(<CompanyChart departments={departments} agents={agents} members={members}><form><input defaultValue="preserved form"/></form></CompanyChart>);
assert.match(html,/aria-pressed="true">Visual chart/);assert.match(html,/Cards &amp; edit/);assert.match(html,/markerEnd|marker-end/);assert.match(html,/preserved form/);assert.match(html,/hidden=""/);
const page=readFileSync("app/(app)/company/page.tsx","utf8");
assert.equal((page.match(/<details /g)||[]).length,4);assert.equal((page.match(/id="hybrid-org-chart" open/g)||[]).length,1);
for(const action of ["updateCompanyProfile","createDepartment","createTeam","inviteMember","updateMember","updateAgentStructure","updateAgentCost"])assert.ok(page.includes(`action={${action}}`));
const shell=readFileSync("components/app-shell/AppShell.tsx","utf8");assert.doesNotMatch(shell,/workspace-identity-slot|workspace-identity-bar/);assert.match(shell,/WorkspaceCompanyBadge/);
const badge=readFileSync("components/company-branding/WorkspaceCompanyBadge.tsx","utf8");assert.doesNotMatch(badge,/userName|userEmail|activeRole/);
console.log("PASS chart topology, departments, cross-department reporting, humans, cycles, unknown managers, accessible default view, collapsed sections, preserved forms and company-only header");
