import assert from "node:assert/strict";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { GOOGLE_OAUTH_REFRESH_BOUNDARY } from "../lib/company-bootstrap/direct-execution-boundary";
import { CONNECTION_AGENT_OAUTH_BOUNDARY } from "../lib/integrations/connection-agent-direct-boundary";
import { CONNECTION_PLATFORM_DIRECT_BOUNDARIES } from "../lib/integrations/connection-platform-direct-boundary";
import { DIRECT_EXECUTION_INVENTORY } from "../lib/integrations/direct-execution-inventory";
function files(root:string):string[]{return readdirSync(root).flatMap(name=>{const path=join(root,name);if(name==="node_modules"||name===".next"||name===".git")return[];return statSync(path).isDirectory()?files(path):[path];});}
const sourceFiles=[...files("app"),...files("lib"),...files("components")].filter(path=>/\.(ts|tsx)$/.test(path)); const connectionPlatformPaths=CONNECTION_PLATFORM_DIRECT_BOUNDARIES.map(item=>item.path);
assert.deepEqual(connectionPlatformPaths.sort(),["lib/integrations/connections/github-app.ts","lib/integrations/connections/github-customer-oauth.ts","lib/integrations/connections/platform-oauth.ts","lib/integrations/connections/provider-credentials.ts"].sort(),"Core connection control-plane fetch boundaries must remain explicitly inventoried.");
const sameOriginUiBoundaries=["components/ai-workspace/AIWorkspaceClient.tsx","components/ai-workspace/GuestAIClient.tsx","components/ai-workspace/FilesPanel.tsx","components/ai-workspace/WorkspaceResourcePanel.tsx","components/admin/AIWorkspaceGuestCodeForm.tsx"];
const fetchBoundaries=new Set(["app/(app)/agents/[code]/benchmark/BenchmarkConsole.tsx","app/(app)/meetings/room/DeliberationConsole.tsx","app/(app)/readiness/ExecuteValidationButton.tsx","app/(app)/integrations/connection-flight-deck.tsx","components/integrations/ConnectionAgentDock.tsx","app/api/2nya-nailart/book/route.ts","app/api/2nya-nailart/media-health/route.ts","app/api/integrations/google-workspace/callback/route.ts","app/api/integrations/google-analytics/callback/route.ts","app/api/integrations/google-search-console/callback/route.ts","app/api/integrations/microsoft-365/callback/route.ts","app/api/integrations/github/callback/route.ts","app/api/integrations/vercel/callback/route.ts","app/api/integrations/supabase/callback/route.ts","app/api/integrations/cloudflare/callback/route.ts","app/api/meetings/continue-detached/route.ts","components/app-shell/BoardroomFocusBridge.tsx","components/communication/CommunicationDeliveryDock.tsx","components/consumer-withdrawal-form.tsx","components/project-pulse/ProjectPulse.tsx","components/projects/project-governance-controls.tsx","components/projects/project-live-operations.tsx","components/projects/project-os-controls.tsx","components/projects/ProjectExecutiveSignalEnhancer.tsx","components/projects/approval-decision-discussion.tsx",...sameOriginUiBoundaries,"lib/ai/agent-provider.ts","lib/analytics/public-events.ts","lib/billing/stripe-rest.ts",GOOGLE_OAUTH_REFRESH_BOUNDARY.path,"lib/integrations/adapters/http.ts","lib/integrations/adapters/customer-connections.ts",CONNECTION_AGENT_OAUTH_BOUNDARY.path,...connectionPlatformPaths,"lib/integrations/computer-use/runtime.ts"]);
const allFetchFiles=sourceFiles.filter(path=>/\bfetch\s*\(/.test(readFileSync(path,"utf8"))).map(path=>relative(".",path)); assert.deepEqual(allFetchFiles.filter(path=>!fetchBoundaries.has(path)),[],"Every new fetch boundary must be explicitly classified by the Phase 2 guard.");
for(const path of sameOriginUiBoundaries){const source=readFileSync(path,"utf8");assert.doesNotMatch(source,/fetch\s*\(\s*["'`]https?:\/\//,`${path} must call same-origin RYTHM APIs only.`);assert.doesNotMatch(source,/(api\.openai\.com|api\.anthropic\.com|generativelanguage\.googleapis\.com|api\.stripe\.com)/i,`${path} must never call providers directly.`);}
assert.match(readFileSync("components/ai-workspace/AIWorkspaceClient.tsx","utf8"),/fetch\(\"\/api\/ai-workspace\//); assert.match(readFileSync("components/ai-workspace/GuestAIClient.tsx","utf8"),/fetch\(\"\/api\/ai-workspace\//); assert.match(readFileSync("components/ai-workspace/FilesPanel.tsx","utf8"),/fetch\(\"\/api\/ai-workspace\/files/); assert.match(readFileSync("components/ai-workspace/WorkspaceResourcePanel.tsx","utf8"),/fetch\(`\/api\/ai-workspace\/resources\//); assert.match(readFileSync("components/admin/AIWorkspaceGuestCodeForm.tsx","utf8"),/fetch\(\"\/api\/admin\/ai-workspace\//);
const directPatterns=[/fetch\s*\(\s*["'`]https:\/\//,/new\s+OpenAI\s*\(/,/api\.anthropic\.com/,/generativelanguage\.googleapis\.com/,/stripePost\s*\(/,/await\s+fetch\s*\(url/]; const discovered=sourceFiles.filter(path=>{const source=readFileSync(path,"utf8");return directPatterns.some(pattern=>pattern.test(source));}).map(path=>relative(".",path)); const inventoried=new Set([...DIRECT_EXECUTION_INVENTORY.map(item=>item.path),...connectionPlatformPaths,GOOGLE_OAUTH_REFRESH_BOUNDARY.path,CONNECTION_AGENT_OAUTH_BOUNDARY.path,"app/api/2nya-nailart/book/route.ts"]); const unknown=discovered.filter(path=>!path.startsWith("lib/integrations/adapters/")&&!inventoried.has(path)); assert.deepEqual(unknown,[],`Unknown direct provider/external execution paths: ${unknown.join(", ")}`);
const computerUseBoundary=DIRECT_EXECUTION_INVENTORY.find(item=>item.path==="lib/integrations/computer-use/runtime.ts");assert.ok(computerUseBoundary,"Computer Use boundary must remain explicitly inventoried.");assert.equal(computerUseBoundary.disposition,"platform_control_boundary");assert.match(computerUseBoundary.scope,/connection setup control-plane/i);assert.match(computerUseBoundary.reason,/not authority to execute business actions/i);assert.match(computerUseBoundary.reviewPoint,/credential-handling/i);
assert.equal(CONNECTION_AGENT_OAUTH_BOUNDARY.disposition,"platform_control_boundary");assert.match(CONNECTION_AGENT_OAUTH_BOUNDARY.scope,/Human-authorized OAuth code exchange/i);assert.match(CONNECTION_AGENT_OAUTH_BOUNDARY.reason,/cannot execute business actions/i);assert.match(CONNECTION_AGENT_OAUTH_BOUNDARY.reviewPoint,/Human Takeover/i);assert.equal(GOOGLE_OAUTH_REFRESH_BOUNDARY.disposition,"platform_control_boundary");assert.match(GOOGLE_OAUTH_REFRESH_BOUNDARY.scope,/OAuth access-token refresh/);assert.match(GOOGLE_OAUTH_REFRESH_BOUNDARY.reason,/cannot perform Gmail or Calendar business actions/);
assert.equal(CONNECTION_PLATFORM_DIRECT_BOUNDARIES.length,4);for(const boundary of CONNECTION_PLATFORM_DIRECT_BOUNDARIES){assert.equal(boundary.disposition,"platform_control_boundary");assert.ok(boundary.owner&&boundary.scope&&boundary.risk&&boundary.reason&&boundary.migrationPlan&&boundary.reviewPoint,`Incomplete connection-platform boundary: ${boundary.path}`);assert.match(boundary.reason,/(does not grant|cannot authorize|does not choose)/i,`Connection-platform boundary must explicitly deny operational authority: ${boundary.path}`);}
const directSdkPattern=/from\s+["'](?:stripe|resend|@octokit\/rest|googleapis|@microsoft\/microsoft-graph-client|nodemailer|playwright|puppeteer|axios|got|ky)["']/;assert.deepEqual(sourceFiles.filter(path=>directSdkPattern.test(readFileSync(path,"utf8"))),[],"Direct integration SDK imports are prohibited outside registered adapters.");for(const exception of DIRECT_EXECUTION_INVENTORY.filter(item=>item.disposition==="temporary_exception")){assert.ok(exception.owner&&exception.scope&&exception.risk&&exception.reason&&exception.migrationPlan&&exception.reviewPoint,`Incomplete temporary exception: ${exception.path}`);}
const outbound=readFileSync("app/api/communication/outbound/resend/route.ts","utf8");assert.match(outbound,/requestToolExecution/);assert.doesNotMatch(outbound,/fetch\s*\(\s*["'`]https:\/\//);const ci=readFileSync(".github/workflows/ci.yml","utf8");assert.match(ci,/test:phase2:direct-guard/);console.log(`Phase 2 direct execution guard passed (${discovered.length} classified provider boundaries, ${allFetchFiles.length} explicit fetch boundaries; 0 unknown).`);
