import fs from "node:fs";
import path from "node:path";

const root=process.cwd();
const read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");
const requireFile=(file:string)=>{if(!fs.existsSync(path.join(root,file)))throw new Error(`Missing ${file}`);return read(file);};
const requireText=(content:string,text:string,label:string)=>{if(!content.includes(text))throw new Error(`${label}: missing ${text}`);};

const migration=requireFile("supabase/migrations/20260912203000_project_operating_system.sql");
const compat=requireFile("supabase/migrations/20260912204000_project_os_compatibility.sql");
const scheduler=requireFile("supabase/migrations/20260912205000_project_os_scheduler_hardening.sql");
const databaseScheduler=requireFile("supabase/migrations/20260912206000_project_os_database_scheduler.sql");
const meetingMigration=requireFile("supabase/migrations/20260912207000_project_os_autonomous_meetings.sql");
const knowledgeMigration=requireFile("supabase/migrations/20260912208000_project_os_knowledge_ingestion.sql");
const proposalMigration=requireFile("supabase/migrations/20260912209000_project_os_proposal_governance.sql");
const terminalMigration=requireFile("supabase/migrations/20260912210000_project_os_terminal_reconciliation.sql");
const engine=requireFile("lib/projects/project-operating-system.ts");
const knowledgeWorker=requireFile("lib/projects/project-knowledge.ts");
const meetingWorker=requireFile("lib/projects/project-autonomous-meetings.ts");
const proposalWorker=requireFile("lib/projects/project-proposal-execution.ts");
const toolWorker=requireFile("lib/projects/project-tool-execution.ts");
const intake=requireFile("app/(app)/projects/page.tsx");
const dashboard=requireFile("app/(app)/projects/operating/page.tsx");
const analyzeRoute=requireFile("app/api/projects/analyze/route.ts");
const connectionRoute=requireFile("app/api/projects/connections/route.ts");
const vercel=requireFile("vercel.json");
const authRoutes=["app/api/projects/analyze/route.ts","app/api/projects/run/route.ts","app/api/projects/files/route.ts","app/api/projects/connections/route.ts","app/api/projects/control/route.ts"].map(requireFile);
const dispatcher=requireFile("app/api/projects/dispatch/route.ts");

for(const table of ["project_clients","project_contracts","project_documents","project_connection_bindings","project_readiness_assessments","project_clarification_requests","project_scope_versions","project_executions","project_task_runs","project_proposals","project_decision_memory","project_agent_capacity","project_activity_events","project_health_events"])requireText(migration,`public.${table}`,"schema");
requireText(migration,"resume_project_tasks_after_approval_v1","approval auto-resume");
requireText(migration,"resume_project_tasks_after_connection_v1","connection auto-resume");
requireText(migration,"service_role","worker-only RPC boundary");
requireText(compat,"computer.use","reusable computer-use contract");
requireText(compat,"requires_cloud_provider,enabled","computer-use provider gate");
requireText(compat,"true,false","computer-use must remain disabled without provider");
requireText(scheduler,"for update of tr skip locked","concurrency-safe claiming");
requireText(scheduler,"Every declared dependency must exist","missing dependency fail-closed");
requireText(scheduler,"enforce_project_agent_capacity_v1","cross-project capacity guard");
requireText(scheduler,"refresh_project_execution_health_v1","heartbeat health monitor");
requireText(databaseScheduler,"pg_cron","database scheduler");
requireText(databaseScheduler,"pg_net","database HTTP dispatcher");
requireText(databaseScheduler,"vault.create_secret","scheduler secret storage");
requireText(databaseScheduler,"configure_project_os_scheduler_v1","explicit scheduler activation");
requireText(databaseScheduler,"*/%s * * * *","database scheduler cadence");
requireText(meetingMigration,"project_autonomous_meeting_jobs","durable autonomous meeting jobs");
requireText(meetingMigration,"claim_project_autonomous_meeting_jobs_v1","autonomous meeting claim");
requireText(meetingMigration,"recover_stale_project_autonomous_meeting_jobs_v1","autonomous meeting crash recovery");
requireText(meetingMigration,"AUTONOMOUS","autonomous meeting involvement mode");
requireText(knowledgeMigration,"project_document_chunks","durable project file knowledge chunks");
requireText(knowledgeMigration,"claim_project_document_ingestions_v1","document ingestion claim");
requireText(knowledgeMigration,"recover_stale_project_document_ingestions_v1","document ingestion recovery");
requireText(knowledgeMigration,"for update of d skip locked","document ingestion concurrency safety");
requireText(proposalMigration,"ensure_project_proposal_continuation_v1","proposal continuation reservation");
requireText(proposalMigration,"sync_project_proposal_approval_v1","proposal approval convergence");
requireText(proposalMigration,"project_decision_memory","proposal decision memory");
requireText(proposalMigration,"approved_by_human_ceo","human authorization context");
requireText(terminalMigration,"reconcile_project_execution_terminal_states_v1","terminal execution reconciliation");
requireText(terminalMigration,"completed','cancelled","cancelled work terminal semantics");
requireText(knowledgeWorker,"extractCompanyDocument","existing company extraction pipeline reuse");
requireText(knowledgeWorker,"chunkCompanyDocument","project knowledge chunking");
requireText(knowledgeWorker,"project_context_documents","project knowledge context materialization");
requireText(knowledgeWorker,"project_document_chunks","project knowledge search chunks");
requireText(knowledgeWorker,"redactSecretText","knowledge worker error redaction");
requireText(meetingWorker,"boardroom.deliberation","existing Boardroom deliberation reuse");
requireText(meetingWorker,"boardroom.summary","existing Boardroom synthesis reuse");
requireText(meetingWorker,"project_decision_memory","meeting decision memory");
requireText(meetingWorker,"project_task_runs","meeting action handoff");
requireText(meetingWorker,"project_context_documents","meeting knowledge feedback");
requireText(proposalWorker,"requestToolExecution","proposal execution must reuse canonical Integration & Execution Gateway");
requireText(proposalWorker,"project_connection_bindings","proposal execution must be project-connection scoped");
requireText(proposalWorker,"permission_match_confidence","proposal-to-capability mapping must fail closed on ambiguity");
requireText(proposalWorker,"decided_by_user_id","proposal execution must retain accountable Human CEO identity");
requireText(proposalWorker,"idempotencyKey","proposal execution must be idempotent");
requireText(proposalWorker,'bridge_status:"retrying"',"proposal execution retry visibility");
requireText(toolWorker,"syncToolExecutionApproval","canonical tool approval sync");
requireText(toolWorker,"executeApprovedToolRequest","canonical Integration & Execution Gateway execution");
requireText(toolWorker,'["waiting_approval","approved","authorized"]',"approval-to-execution queue");
requireText(toolWorker,'"simulated"',"simulation must never be treated as a real external side effect");
requireText(toolWorker,"reconcileDispatchedProjectProposals","immediate proposal policy convergence");
requireText(engine,"executeAiRequest","AI Request Gateway reuse");
requireText(engine,"organization_integrations","company-level connection reuse");
requireText(engine,"project_connection_bindings","project-scoped connections");
requireText(engine,"project_context_documents","shared Project Knowledge reuse");
requireText(engine,"approval_requests","Human CEO approval reuse");
requireText(engine,"project_proposals","proactive proposal path");
requireText(engine,"recover_stale_project_task_runs_v1","restart recovery");
requireText(analyzeRoute,"dispatchProjectKnowledge","analysis consumes indexed project files");
requireText(analyzeRoute,'from("project_agents").insert',"recommended project team materialization");
requireText(analyzeRoute,'from("project_agent_capacity").insert',"recommended team capacity materialization");
requireText(connectionRoute,"project_context_documents","confirmed connections feed Project Knowledge");
requireText(connectionRoute,"capabilities:requested","connection knowledge must expose only confirmed capability keys");
requireText(intake,"Client / Counterparty","rich intake client section");
requireText(intake,"Contract & Commercial","rich intake contract section");
requireText(intake,'name="files" multiple',"multi-file intake");
requireText(dashboard,"Execution Readiness","readiness UX");
requireText(dashboard,"Executive Inbox","executive attention UX");
requireText(dashboard,"persisted server-side","offline execution UX");
if(vercel.includes('"path": "/api/projects/dispatch"'))throw new Error("Frequent project dispatch must not rely on Vercel Hobby Cron.");
for(const route of authRoutes){requireText(route,"resolveOwnerApiOrganizationContext","owner authorization");requireText(route,"organizationId","tenant scope");}
requireText(dispatcher,"CRON_SECRET","scheduler authentication");
requireText(dispatcher,"refresh_project_execution_health_v1","scheduler health refresh");
requireText(dispatcher,"recover_stale_project_autonomous_meeting_jobs_v1","scheduler meeting recovery");
requireText(dispatcher,"dispatchProjectKnowledge","durable background knowledge ingestion");
requireText(dispatcher,"dispatchProjectWork","durable background task execution");
requireText(dispatcher,"dispatchAutonomousProjectMeetings","durable background meetings");
requireText(dispatcher,"dispatchApprovedProjectProposalActions","approved proposal bridge dispatch");
requireText(dispatcher,"reconcileDispatchedProjectProposals","proposal policy convergence before task claim");
requireText(dispatcher,"dispatchApprovedProjectToolExecutions","approval auto-execution");
requireText(dispatcher,"reconcile_project_execution_terminal_states_v1","terminal-state reconciliation dispatch");

if(engine.includes("setInterval(")||engine.includes("window.")||engine.includes("localStorage"))throw new Error("Background execution must not depend on frontend/in-memory browser runtime.");
if(knowledgeWorker.includes("setInterval(")||knowledgeWorker.includes("window.")||knowledgeWorker.includes("localStorage"))throw new Error("Project Knowledge ingestion must not depend on frontend/in-memory browser runtime.");
if(proposalWorker.includes("window.")||proposalWorker.includes("localStorage"))throw new Error("Proposal execution must be server-side and browser-independent.");
if(meetingWorker.includes("cookie")||meetingWorker.includes("after("))throw new Error("Autonomous project meetings must not depend on browser cookies or request-lifetime continuations.");
if(dashboard.includes("Watch Live")||dashboard.includes("Take Control"))throw new Error("Computer-use live controls must not be exposed before a real cloud provider exists.");
console.log("Project Operating System static architecture validation passed.");
