import Link from "next/link";
import { redirect } from "next/navigation";
import { createAuthServerClient } from "@/lib/supabase/auth-server";
import { getProjectOperatingTimeline, getProjectRelationships, refreshProjectWorkflowState, type EntityRelationship, type WorkflowTimelineItem } from "@/lib/workflow/server";
import { getProjectProgressSnapshot } from "@/lib/projects/project-progress";
import { ProjectOsControls } from "@/components/projects/project-os-controls";
import { ProjectGovernanceControls } from "@/components/projects/project-governance-controls";

export const dynamic="force-dynamic";
type View="overview"|"live"|"agents"|"tasks"|"approvals"|"actions"|"files"|"activity";
type Props={searchParams:Promise<{project?:string;view?:string;taskStatus?:string;taskAgent?:string}>};
const views:Array<{key:View;label:string}>=[{key:"overview",label:"Overview"},{key:"live",label:"Live AI"},{key:"agents",label:"Agents"},{key:"tasks",label:"Tasks"},{key:"approvals",label:"Approvals"},{key:"actions",label:"Actions"},{key:"files",label:"Files"},{key:"activity",label:"Activity"}];
const label=(value:string)=>value.replaceAll("_"," ").replaceAll("."," · ");
const formatDate=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"No activity yet";
function payloadSummary(item:WorkflowTimelineItem){const p=item.payload??{};const explicit=[p.event_label,p.label,p.reason,p.next_step,p.after_state].find(v=>typeof v==="string"&&v.trim());return typeof explicit==="string"?explicit:label(item.event_type);}
function destinationForRelationship(edge:EntityRelationship,projectId:string){const c=[edge.source_type,edge.target_type];if(c.includes("meeting")||c.includes("meeting_session")||c.includes("decision")||c.includes("legal_review"))return "/meetings/room";if(c.includes("action_item"))return `/actions?project=${projectId}`;if(c.includes("memory_record"))return "/memory";return `/projects/operating?project=${projectId}&view=overview`;}
async function ownerContext(){const supabase=await createAuthServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:membership}=await supabase.from("organization_members").select("organization_id,role").eq("user_id",user.id).eq("role","owner").maybeSingle();if(!membership)redirect("/login?error=Owner%20authorization%20required.");return{supabase,organizationId:membership.organization_id as string};}

export default async function ProjectOperatingPage({searchParams}:Props){
  const params=await searchParams;const activeView=views.some(v=>v.key===params.view)?params.view as View:"overview";const {supabase,organizationId}=await ownerContext();
  let query=supabase.from("projects").select("*").eq("organization_id",organizationId);query=params.project?query.eq("id",params.project):query.order("priority").limit(1);const {data:project}=await query.maybeSingle();
  if(!project)return <main className="command-shell"><section className="panel"><h1>Project operating view unavailable</h1><Link className="secondary-button" href="/projects">Back to Projects</Link></section></main>;
  let workflowState=project.workflow_state??"INTAKE";try{workflowState=await refreshProjectWorkflowState(supabase,project.id,{entityType:"ui",reason:"Project Operating System convergence"});}catch{}
  const [client,contract,documents,resources,bindings,readiness,clarifications,scope,execution,tasks,team,proposals,activity,health,integrations,capabilities,timeline,relationships,meetings,decisions,approvals,projectActions]=await Promise.all([
    supabase.from("project_clients").select("*").eq("project_id",project.id).maybeSingle(),
    supabase.from("project_contracts").select("*").eq("project_id",project.id).maybeSingle(),
    supabase.from("project_documents").select("id,category,file_name,mime_type,byte_size,extraction_status,legal_document,created_at").eq("project_id",project.id).order("created_at",{ascending:false}),
    supabase.from("project_resources").select("*").eq("project_id",project.id).order("created_at"),
    supabase.from("project_connection_bindings").select("*").eq("project_id",project.id).order("created_at"),
    supabase.from("project_readiness_assessments").select("*").eq("project_id",project.id).order("created_at",{ascending:false}).limit(1).maybeSingle(),
    supabase.from("project_clarification_requests").select("id,question,reason,input_type,options,materiality,status").eq("project_id",project.id).eq("status","open").order("created_at"),
    supabase.from("project_scope_versions").select("*").eq("project_id",project.id).order("version",{ascending:false}).limit(1).maybeSingle(),
    supabase.from("project_executions").select("*").eq("project_id",project.id).order("execution_no",{ascending:false}).limit(1).maybeSingle(),
    supabase.from("project_task_runs").select("id,execution_id,task_key,title,status,priority,assigned_agent_id,attempt_count,max_attempts,error_class,error_message,started_at,completed_at,updated_at,agents(agent_code,display_name,name)").eq("project_id",project.id).order("priority").order("created_at"),
    supabase.from("project_agents").select("assignment_role,status,authority_scope,agents(id,agent_code,display_name,name,role_title)").eq("project_id",project.id),
    supabase.from("project_proposals").select("*").eq("project_id",project.id).order("created_at",{ascending:false}),
    supabase.from("project_activity_events").select("*").eq("project_id",project.id).order("created_at",{ascending:false}).limit(60),
    supabase.from("project_health_events").select("*").eq("project_id",project.id).eq("status","open").order("detected_at",{ascending:false}),
    supabase.from("organization_integrations").select("id,provider_key,display_name,status").eq("organization_id",organizationId).order("provider_key"),
    supabase.from("integration_capabilities").select("provider_key,capability_key,description,risk_level,default_approval_mode").eq("enabled",true),
    getProjectOperatingTimeline(supabase,project.id,40),getProjectRelationships(supabase,project.id),
    supabase.from("meetings").select("id",{count:"exact",head:true}).eq("project_id",project.id),supabase.from("decisions").select("id",{count:"exact",head:true}).eq("project_id",project.id),supabase.from("approval_requests").select("id,status,title,summary,risk_level,created_at",{count:"exact"}).eq("project_id",project.id),
    supabase.from("action_items").select("id,title,status,priority,updated_at,assigned_agent_id").eq("project_id",project.id).order("updated_at",{ascending:false}),
  ]);
  const openClarifications=clarifications.data??[];const latestReadiness=readiness.data;const latestScope=scope.data;const latestExecution=execution.data;const allTaskRows=tasks.data??[];
  const taskRows=latestExecution?allTaskRows.filter((task:any)=>task.execution_id===latestExecution.id):allTaskRows;
  const proposalRows=proposals.data??[];const attention=proposalRows.filter((p:any)=>["ready_for_executive","needs_revision","internal_review"].includes(p.status));const pendingApprovalRows=(approvals.data??[]).filter((a:any)=>a.status==="pending");
  const progress=await getProjectProgressSnapshot(supabase,organizationId,{id:project.id,status:project.status,updated_at:activity.data?.[0]?.created_at??project.updated_at});
  const agents=team.data??[];const activeAgents=agents.filter((a:any)=>["active","assigned"].includes(a.status));
  const canRun=Number(project.readiness_score??0)>=50&&openClarifications.filter((c:any)=>c.materiality==="required").length===0&&!latestExecution?.status?.match(/^(queued|running|paused)$/);
  const selectedStatus=params.taskStatus??"all",selectedAgent=params.taskAgent??"all";
  const filteredTasks=taskRows.filter((task:any)=>(selectedStatus==="all"||task.status===selectedStatus)&&(selectedAgent==="all"||task.assigned_agent_id===selectedAgent));
  const navCount=(view:View)=>view==="agents"?agents.length:view==="tasks"?taskRows.length:view==="approvals"?pendingApprovalRows.length:view==="actions"?(projectActions.data?.length??0):view==="files"?(documents.data?.length??0):view==="activity"?(activity.data?.length??0):null;
  return <main className="command-shell">
    <header className="command-header"><div><p className="eyebrow">RYTHM PROJECT MISSION CONTROL · {project.project_code}</p><h1>{project.name}</h1><p className="subtitle">{project.objective||project.description||"Governed autonomous project."}</p></div><div className="project-header-actions"><Link className="secondary-button" href="/projects">All Projects</Link><Link className="secondary-button" href="/attention">Your Attention</Link><Link className="secondary-button" href="/meetings/room">Boardroom</Link></div></header>
    <nav className="project-subnav" aria-label="Project workspace">{views.map(view=><Link key={view.key} aria-current={activeView===view.key?"page":undefined} className={activeView===view.key?"active":""} href={`/projects/operating?project=${project.id}&view=${view.key}`}>{view.label}{navCount(view.key)!=null?<span>{navCount(view.key)}</span>:null}</Link>)}</nav>
    <section className="organization-banner project-mission-summary"><div><span>Status</span><strong>{label(project.status)}</strong></div><div><span>Roadmap progress</span><strong>{progress.hasApprovedRoadmap?`${progress.progressPercent}%`:"Not baselined"}</strong></div><div><span>Execution Readiness</span><strong>{latestReadiness?.execution_readiness??project.readiness_score??0}%</strong></div><div><span>Tasks</span><strong>{progress.completedTasks}/{progress.totalTasks}</strong></div><div><span>Agents</span><strong>{activeAgents.length}</strong></div><div><span>Approvals</span><strong>{progress.awaitingApproval}</strong></div><div><span>Attention</span><strong>{attention.length+pendingApprovalRows.length}</strong></div><div><span>Heartbeat</span><strong>{formatDate(latestExecution?.last_heartbeat_at??project.last_heartbeat_at)}</strong></div></section>
    <ProjectOsControls projectId={project.id} canRun={canRun} status={latestExecution?.status??project.stage} showLiveOperations={activeView==="live"||activeView==="approvals"} liveMode={activeView==="approvals"?"approvals":"full"} showFileUpload={activeView==="files"}/>

    <section className="panel executive-inbox-compact"><div className="panel-heading"><div><p className="label">Executive Inbox</p><h2>{attention.length+pendingApprovalRows.length?`${attention.length+pendingApprovalRows.length} decision${attention.length+pendingApprovalRows.length===1?"":"s"} need attention`:"No executive decision pending"}</h2></div><Link className="secondary-button" href={`/projects/operating?project=${project.id}&view=approvals`}>Review approvals</Link></div>{attention.slice(0,3).map((p:any)=><div className="data-row" key={p.id}><div><strong>{p.title}</strong><span>{p.executive_summary}</span></div><span className="pill">{p.risk_level}</span></div>)}</section>

    {activeView==="overview"?<>
      <ProjectGovernanceControls projectId={project.id} projectStatus={project.status} clarifications={openClarifications as any} connections={(integrations.data??[]) as any} capabilities={(capabilities.data??[]) as any} latestScope={latestScope?{id:latestScope.id,status:latestScope.status}:null}/>
      <section className="executive-grid project-view-panel"><article className="panel"><div className="panel-heading"><div><p className="label">Execution Readiness</p><h2>{latestReadiness?.execution_readiness??project.readiness_score??0}% ready</h2></div><span className="pill">Inputs and dependencies</span></div><p className="subtitle">Readiness measures context, scope, integrations, team, clarifications and evidence. It does not represent completed work.</p>{latestReadiness?<div className="data-list"><div className="data-row"><div><strong>Project understanding</strong><span>{latestReadiness.project_understanding}%</span></div></div><div className="data-row"><div><strong>Contract understanding</strong><span>{latestReadiness.contract_understanding}%</span></div></div><div className="data-row"><div><strong>Connections</strong><span>{latestReadiness.connections_available}/{latestReadiness.connections_total}</span></div></div><div className="data-row"><div><strong>Team readiness</strong><span>{latestReadiness.team_readiness}%</span></div></div></div>:<p className="subtitle">Run Project Analysis to create readiness, scope, team and connection recommendations.</p>}</article><article className="panel"><div className="panel-heading"><div><p className="label">Roadmap Progress</p><h2>{progress.hasApprovedRoadmap?`${progress.progressPercent}% complete`:"Not baselined"}</h2></div><span className="pill">{progress.hasApprovedRoadmap?`roadmap v${progress.roadmapVersion}`:"manager approval required"}</span></div><div className="project-progress-track"><span style={{width:`${progress.hasApprovedRoadmap?progress.progressPercent:0}%`}}/></div><div className="project-card-metrics"><div><span>Task count</span><strong>{progress.completedTasks}/{progress.totalTasks}</strong></div><div><span>Task completion</span><strong>{progress.taskCompletionPercent}%</strong></div><div><span>Current phase</span><strong>{progress.currentPhase??"—"}</strong></div><div><span>Outcome progress</span><strong>{progress.outcomeProgressPercent==null?"Pending evidence":`${progress.outcomeProgressPercent}%`}</strong></div><div><span>Awaiting approval</span><strong>{progress.awaitingApproval}</strong></div><div><span>Blocked / failed</span><strong>{progress.blockedTasks+progress.failedTasks}</strong></div></div><p className="security-note">Roadmap progress is weighted against the manager-approved baseline. Raw task count is informational only. Execution is persisted server-side.</p></article></section>
      <section className="executive-grid project-view-panel"><article className="panel"><div className="panel-heading"><div><p className="label">Client</p><h2>{client.data?.client_name??"Internal / not specified"}</h2></div></div><p className="subtitle">{client.data?.legal_company_name||client.data?.country||"No external counterparty was provided."}</p></article><article className="panel"><div className="panel-heading"><div><p className="label">Contract</p><h2>{contract.data?.contract_number||"No structured contract"}</h2></div><span className="pill">{contract.data?.legal_review_status??"not requested"}</span></div><p className="subtitle">{contract.data?.contract_value!=null?`${contract.data.contract_value} ${contract.data.currency||""}`:"Commercial terms can be supplied through Project Knowledge."}</p></article></section>
      <section className="panel project-view-panel"><div className="panel-heading"><div><p className="label">Scope</p><h2>{latestScope?`Version ${latestScope.version}`:"Awaiting analysis"}</h2></div>{latestScope?<span className="pill">{latestScope.status}</span>:null}</div>{latestScope?<div className="executive-grid"><div><strong>Included</strong><ul>{(latestScope.included??[]).map((v:any,i:number)=><li key={i}>{String(v)}</li>)}</ul></div><div><strong>Excluded</strong><ul>{(latestScope.excluded??[]).map((v:any,i:number)=><li key={i}>{String(v)}</li>)}</ul></div><div><strong>Deliverables</strong><ul>{(latestScope.deliverables??[]).map((v:any,i:number)=><li key={i}>{String(v)}</li>)}</ul></div><div><strong>Success criteria</strong><ul>{(latestScope.success_criteria??[]).map((v:any,i:number)=><li key={i}>{String(v)}</li>)}</ul></div></div>:<p className="subtitle">Scope is generated from objective, files, resources and clarifications.</p>}</section>
      <section className="panel project-view-panel"><div className="project-card-metrics"><div><span>Meetings</span><strong>{meetings.count??0}</strong></div><div><span>Decisions</span><strong>{decisions.count??0}</strong></div><div><span>Approvals</span><strong>{approvals.count??0}</strong></div><div><span>Workflow state</span><strong>{label(workflowState)}</strong></div><div><span>Open health events</span><strong>{health.data?.length??0}</strong></div><div><span>Last activity</span><strong>{formatDate(progress.lastActivityAt)}</strong></div></div></section>
    </>:null}

    {activeView==="agents"?<section className="panel project-view-panel"><div className="panel-heading"><div><p className="label">Project-only team</p><h2>Assigned AI specialists</h2></div><span className="pill">{agents.length} agents</span></div><div className="data-list">{agents.map((row:any)=>{const agent=Array.isArray(row.agents)?row.agents[0]:row.agents;return <div className="data-row" key={agent?.id??row.assignment_role}><div><strong>{agent?.display_name||agent?.name||"Agent"}</strong><span>{agent?.role_title||row.assignment_role} · {agent?.agent_code||"AI"}</span></div><span className="pill">{row.status}</span></div>})}{!agents.length?<p className="subtitle">The project team forms after analysis.</p>:null}</div></section>:null}

    {activeView==="tasks"?<section className="panel project-view-panel"><div className="panel-heading"><div><p className="label">Execution graph</p><h2>Project tasks</h2></div><span className="pill">{filteredTasks.length}/{taskRows.length}</span></div><form method="get" className="project-task-filters"><input type="hidden" name="project" value={project.id}/><input type="hidden" name="view" value="tasks"/><label>Status<select name="taskStatus" defaultValue={selectedStatus}><option value="all">All statuses</option>{[...new Set(taskRows.map((task:any)=>task.status))].map(status=><option key={status} value={status}>{label(status)}</option>)}</select></label><label>Agent<select name="taskAgent" defaultValue={selectedAgent}><option value="all">All agents</option>{agents.map((row:any)=>{const agent=Array.isArray(row.agents)?row.agents[0]:row.agents;return <option key={agent?.id??row.assignment_role} value={agent?.id}>{agent?.display_name||agent?.name||row.assignment_role}</option>})}</select></label><button>Apply filters</button></form><div className="data-list">{filteredTasks.map((task:any)=><div className="data-row" key={task.id}><div><strong>{task.title}</strong><span>{task.agents?.agent_code??"Unassigned"} · attempt {task.attempt_count}/{task.max_attempts}{task.error_message?` · ${task.error_message}`:""}</span></div><span className="pill">{label(task.status)}</span></div>)}</div></section>:null}

    {activeView==="approvals"?<section className="panel project-view-panel"><div className="panel-heading"><div><p className="label">Approval policy</p><h2>Human CEO authority</h2></div><span className="pill">{pendingApprovalRows.length} pending</span></div><p className="subtitle">Approval notes are optional unless policy requires them. Rejections require a reason. Only the affected workstream is blocked; independent tasks continue.</p></section>:null}

    {activeView==="actions"?<section className="panel project-view-panel"><div className="panel-heading"><div><p className="label">Project actions</p><h2>Execution handoffs</h2></div><Link className="secondary-button" href={`/actions?project=${project.id}`}>Open action workspace</Link></div><div className="data-list">{(projectActions.data??[]).map((action:any)=><Link className="data-row" href={`/actions?project=${project.id}&action=${action.id}`} key={action.id}><div><strong>{action.title}</strong><span>Priority {action.priority} · updated {formatDate(action.updated_at)}</span></div><span className="pill">{label(action.status)}</span></Link>)}</div></section>:null}

    {activeView==="files"?<section className="panel project-view-panel"><div className="panel-heading"><div><p className="label">Project Knowledge</p><h2>Files, resources and scoped connections</h2></div><span className="pill">{(documents.data??[]).length+(resources.data??[]).length+(bindings.data??[]).length} items</span></div><div className="project-card-metrics"><div><span>Files</span><strong>{documents.data?.length??0}</strong></div><div><span>Resources</span><strong>{resources.data?.length??0}</strong></div><div><span>Connections</span><strong>{bindings.data?.length??0}</strong></div></div><div className="data-list">{(documents.data??[]).map((document:any)=><div className="data-row" key={document.id}><div><strong>{document.file_name}</strong><span>{label(document.category)} · {document.extraction_status} · {formatDate(document.created_at)}</span></div>{document.legal_document?<span className="pill">Legal</span>:null}</div>)}{(resources.data??[]).map((resource:any)=><div className="data-row" key={resource.id}><div><strong>{resource.name}</strong><span>{resource.resource_type} · {resource.access_status}</span></div></div>)}{(bindings.data??[]).map((binding:any)=><div className="data-row" key={binding.id}><div><strong>{binding.display_name}</strong><span>{binding.resource_type} · {binding.resource_ref}</span></div><span className="pill">{binding.access_status}</span></div>)}</div></section>:null}

    {activeView==="activity"?<section className="executive-grid project-view-panel"><article className="panel panel-wide"><div className="panel-heading"><div><p className="label">Activity</p><h2>Readable project timeline</h2></div><span className="pill">{activity.data?.length??0} recent</span></div><div className="data-list">{(activity.data??[]).map((event:any)=><div className="data-row" key={event.id}><div><strong>{event.headline}</strong><span>{event.detail||label(event.event_type)} · {formatDate(event.created_at)}</span></div><span className="pill">{event.importance}</span></div>)}</div></article><article className="panel"><div className="panel-heading"><div><p className="label">Governed history</p><h2>Connected records</h2></div><span className="pill">{relationships.length}</span></div><div className="data-list">{timeline.slice(0,12).map(item=><div className="data-row" key={`${item.timeline_source}-${item.id}`}><div><strong>{payloadSummary(item)}</strong><span>{formatDate(item.occurred_at)}</span></div></div>)}{relationships.slice(0,8).map(edge=><Link className="data-row" href={destinationForRelationship(edge,project.id)} key={edge.id}><div><strong>{label(edge.relationship_type)}</strong><span>{label(edge.source_type)} → {label(edge.target_type)}</span></div></Link>)}</div></article></section>:null}
  </main>;
}