import type { Metadata } from "next";
import Link from "next/link";
import { createPublicMetadata } from "@/lib/seo/site";

export const metadata: Metadata = createPublicMetadata("/terms");

export default function TermsPage() {
  return (
    <main>
      <section className="public-page-hero enterprise-hero">
        <div><p className="marketing-kicker">TERMS OF SERVICE</p><h1>Terms for using RYTHM Company OS during the Public Beta.</h1></div>
        <p>Effective 14 August 2026. These Terms govern access to the public website, Demo, account areas, and paid or assisted Public Beta services unless a signed order or enterprise agreement states otherwise.</p>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">PROVIDER</p><h2>Who provides RYTHM.</h2><ul><li>RYTHM Company OS is operated by Tayyebialashti Yaser E.V., an individual entrepreneur (e.v.) registered in Hungary.</li><li>Business address: 1143 Budapest, Gizella út 35, Hungary.</li><li>Hungarian tax number: 48332376-1-42.</li><li>Legal contact: <a href="mailto:legal@rythm-os.com">legal@rythm-os.com</a>.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">BUSINESS USE</p><h2>Public Beta is primarily for professional use.</h2><ul><li>You must be legally able to enter into these Terms and, if acting for an organization, have authority to bind or act for it.</li><li>Paid Public Beta offers are primarily intended for business, professional, organizational, or entrepreneurial use.</li><li>If you are acting as a consumer rather than for a business or professional purpose, do not purchase a paid plan until consumer-specific terms are made available; contact <a href="mailto:legal@rythm-os.com">legal@rythm-os.com</a> first.</li><li>Availability in a country does not mean every feature, integration, regulated use case, or payment method is available there.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">BETA STATUS</p><h2>Features can change while the product matures.</h2><ul><li>RYTHM is a Public Beta. Features, limits, interfaces, models, integrations, and commercial packaging may change.</li><li>Beta features may contain defects, interruptions, incomplete documentation, or evolving behavior.</li><li>RYTHM may modify, pause, or withdraw Beta capabilities where needed for security, reliability, legal compliance, or product development.</li><li>Material changes affecting paid commitments will be handled consistently with the applicable order or mandatory law.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">ACCOUNTS & ORGANIZATIONS</p><h2>Keep account access controlled.</h2><ul><li>Account information must be accurate and kept current.</li><li>You are responsible for maintaining the security of your password, email account, sessions, and authorized users.</li><li>Do not share one-time authentication links, tokens, API keys, or credentials.</li><li>Organization owners are responsible for deciding who may join, what data may be submitted, and what governed permissions are granted.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">AI & HUMAN AUTHORITY</p><h2>AI output is not a substitute for accountable human judgment.</h2><ul><li>RYTHM can generate analyses, recommendations, drafts, meeting contributions, plans, and other AI-assisted outputs.</li><li>AI outputs may be incomplete, inaccurate, outdated, or unsuitable for a particular purpose and must be reviewed by an appropriately qualified human where consequences matter.</li><li>RYTHM governance features are designed to preserve human authority boundaries, but customers remain responsible for their decisions, approvals, deployment choices, and external actions.</li><li>Do not use RYTHM as the sole basis for legal, medical, safety-critical, regulated, or other high-stakes decisions without appropriate professional review and an approved deployment context.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">YOUR CONTENT</p><h2>You retain responsibility for submitted content.</h2><ul><li>You retain rights you already hold in content you submit.</li><li>You grant RYTHM and its service providers the limited rights necessary to host, process, transmit, transform, and display that content solely to provide, secure, support, and improve the contracted service as permitted by applicable law and the Privacy Policy.</li><li>Where RYTHM processes customer personal data on behalf of a customer as processor, the <Link href="/dpa">Data Processing Addendum</Link> applies alongside these Terms unless a signed agreement expressly replaces it.</li><li>You must have the rights and lawful basis needed to submit content, including personal or third-party information.</li><li>Do not submit special-category, regulated, highly sensitive, export-controlled, or third-party confidential data unless the deployment has been expressly reviewed for that use.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">ACCEPTABLE USE</p><h2>Do not use RYTHM to harm people, systems, or rights.</h2><ul><li>Do not attempt unauthorized access, privilege escalation, security bypass, credential theft, malware distribution, denial of service, or abuse of platform limits.</li><li>Do not use the service to violate applicable law, intellectual-property rights, privacy rights, confidentiality duties, sanctions, or contractual restrictions.</li><li>Do not misrepresent AI output as independent human professional judgment where that distinction matters.</li><li>RYTHM may restrict or suspend access where reasonably necessary to address abuse, security risk, non-payment, legal obligations, or material breach.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">PUBLIC DEMO</p><h2>The Demo is synthetic and read-only.</h2><ul><li>Nova Commerce and other public Demo content are synthetic examples for product education.</li><li>The Demo does not provide access to production tenant data or real external actions.</li><li>Do not enter confidential, personal, or production data into public Demo surfaces.</li><li>Demo availability does not create a paid subscription or production organization.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">COMMERCIAL TERMS</p><h2>Paid access follows the applicable offer or order.</h2><ul><li>Pricing, billing period, taxes, usage charges, activation requirements, cancellation terms, and any refund rights are defined by the applicable offer, invoice, checkout, or signed order.</li><li>During the Paid Public Beta, commercial activation may remain pending until payment or invoice confirmation is completed.</li><li>Enterprise deployments may require security, data, integration, and scope review before activation.</li><li>If a signed order conflicts with these general Terms, the signed order controls for that conflict.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">INTELLECTUAL PROPERTY</p><h2>RYTHM technology and brand remain protected.</h2><ul><li>RYTHM software, product design, documentation, branding, trademarks, original templates, and other proprietary materials remain owned by their respective rights holders.</li><li>Access to the service does not transfer ownership of RYTHM technology or grant rights to copy, reverse engineer, resell, or create competing derivative implementations except where mandatory law expressly permits otherwise.</li><li>Feedback may be used to improve RYTHM without an obligation to compensate the person providing it, provided no confidential information is intentionally disclosed as feedback.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">AVAILABILITY & THIRD PARTIES</p><h2>Some capabilities depend on external providers.</h2><ul><li>RYTHM relies on third-party infrastructure, authentication, hosting, email, AI-model, networking, and other services.</li><li>The current processors that may handle customer personal data are described in the <Link href="/subprocessors">Subprocessor Register</Link>.</li><li>Service interruptions or provider changes can affect availability or functionality.</li><li>Integrations may have separate third-party terms and permissions.</li><li>Support paths and current security boundaries are described on the Support and Trust Center pages.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">WARRANTIES & LIABILITY</p><h2>Beta use requires appropriate business judgment.</h2><ul><li>To the maximum extent permitted by applicable law, Beta services are provided on an “as available” basis without a promise that every feature will be uninterrupted or error-free.</li><li>To the maximum extent permitted by applicable law, RYTHM is not responsible for indirect or consequential loss caused by unreviewed AI output, customer-controlled external actions, unsupported uses, or failures of third-party services.</li><li>Nothing in these Terms excludes or limits liability that cannot legally be excluded or limited.</li><li>Paid enterprise orders may contain additional service levels, warranties, indemnities, or liability terms.</li></ul></div>
      </section>

      <section className="marketing-section enterprise-model">
        <div className="enterprise-capabilities"><p className="marketing-kicker">GOVERNING LAW</p><h2>Hungarian law is the default contractual framework.</h2><ul><li>Unless a signed order states otherwise, these Terms are governed by the laws of Hungary, excluding conflict-of-law rules.</li><li>Disputes should first be raised through <a href="mailto:legal@rythm-os.com">legal@rythm-os.com</a> so the parties can attempt a good-faith resolution.</li><li>Where jurisdiction can validly be agreed, competent courts in Budapest, Hungary will have jurisdiction.</li><li>Mandatory rights or jurisdiction rules that cannot lawfully be waived remain unaffected.</li></ul></div>
        <div className="enterprise-capabilities"><p className="marketing-kicker">CHANGES</p><h2>Terms may evolve with the Public Beta.</h2><ul><li>Updated Terms will be published with a new effective date.</li><li>Material changes affecting existing paid customers will be communicated where required by contract or law.</li><li>Continued use after an effective update is subject to applicable notice and acceptance requirements.</li></ul></div>
      </section>

      <section className="enterprise-contact-section"><div><p className="marketing-kicker">LEGAL CONTACT</p><h2>Need contractual clarification?</h2><p>For enterprise orders, regulated use cases, data-processing terms, or jurisdiction-specific requirements, request review before deployment.</p></div><div className="enterprise-contact-card"><h3>Legal resources</h3><a className="marketing-button" href="mailto:legal@rythm-os.com">Email Legal</a><div className="hero-actions"><Link href="/legal">Legal Notice</Link><Link href="/privacy">Privacy Policy</Link><Link href="/dpa">DPA</Link></div></div></section>
    </main>
  );
}
