-- RYTHM OS — Trusted Professional Knowledge Packs
-- Curated, source-backed professional foundations with visible provenance.
-- This migration does NOT change professional standing; promotion remains assessment-gated.

begin;

insert into public.knowledge_source_registry
  (source_name,publisher,base_domain,canonical_url,source_type,authority_level,allowed_role_families,allowed_topics,jurisdiction,freshness_class,enabled,notes,last_verified_at,next_review_at)
values
  ('LinkedIn Marketing Solutions','LinkedIn','business.linkedin.com','https://business.linkedin.com/marketing-solutions/products','official_documentation','primary',array['marketing','analytics'],array['paid-media','b2b-marketing','campaign-objectives','targeting','measurement'],null,'fast_changing',true,'Official LinkedIn advertising product and campaign guidance.',now(),now()+interval '60 days'),
  ('FTC Advertising & Marketing','Federal Trade Commission','ftc.gov','https://www.ftc.gov/business-guidance/advertising-marketing','government','primary',array['marketing','legal'],array['advertising-claims','endorsements','reviews','consumer-protection'],'US','moderate',true,'Official US advertising and marketing compliance guidance.',now(),now()+interval '90 days'),
  ('ICO Direct Marketing Guidance','Information Commissioner''s Office','ico.org.uk','https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/','government','primary',array['marketing','legal','general'],array['direct-marketing','privacy','pecr','email-marketing','cookies'],'UK','current_verification_required',true,'Official UK privacy and electronic communications guidance for direct marketing.',now(),now()+interval '30 days'),
  ('IFRS Foundation','IFRS Foundation','ifrs.org','https://www.ifrs.org/about-us/who-we-are/','standards_body','primary',array['analytics'],array['financial-reporting','accounting','transparency','comparability'],null,'moderate',true,'Primary standard-setting reference for IFRS Accounting Standards.',now(),now()+interval '90 days'),
  ('ACCA Performance Management','ACCA','accaglobal.com','https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f5.html','professional_association','high',array['analytics'],array['management-accounting','budgeting','planning','decision-making','performance-control'],null,'slow_changing',true,'Professional reference for management accounting and performance management.',now(),now()+interval '180 days'),
  ('Nielsen Norman Group Content Strategy','Nielsen Norman Group','nngroup.com','https://www.nngroup.com/topic/content-strategy/','primary_reference','high',array['marketing','design','general'],array['content-strategy','ux-writing','content-standards','calls-to-action'],null,'moderate',true,'Research-backed content strategy and UX writing reference.',now(),now()+interval '90 days'),
  ('PMI Standards','Project Management Institute','pmi.org','https://www.pmi.org/standards','professional_association','high',array['general','analytics','marketing'],array['project-management','stakeholders','delivery','risk','organizational-alignment'],null,'slow_changing',true,'Professional standards and guides for project, program, portfolio and organizational project management.',now(),now()+interval '180 days'),
  ('Bain Go-to-Market Strategy','Bain & Company','bain.com','https://www.bain.com/consulting-services/customer-strategy-and-marketing/go-to-market-strategy/','primary_reference','high',array['marketing','general','analytics'],array['go-to-market','account-management','pricing','channels','sales-marketing-alignment'],null,'moderate',true,'Recognized commercial strategy reference for customer-centered GTM and account management.',now(),now()+interval '90 days'),
  ('SHRM Workforce Management','SHRM','shrm.org','https://www.shrm.org/enterprise-solutions/enterprise-bask/organization/workforce-management','professional_association','high',array['general'],array['workforce-management','staffing','succession','workforce-planning'],null,'moderate',true,'Professional HR reference for workforce management and planning.',now(),now()+interval '90 days'),
  ('ILO Human Resources Management Systems','International Labour Organization','ilo.org','https://www.ilo.org/publications/human-resources-management-systems-applied-and-training-guide-companies','primary_reference','high',array['general','legal'],array['human-resources','workers-rights','workplace','labour-compliance'],null,'slow_changing',true,'ILO reference on HR management systems, working conditions and worker rights.',now(),now()+interval '180 days'),
  ('OECD Data','Organisation for Economic Co-operation and Development','oecd.org','https://www.oecd.org/en/data.html','government','primary',array['analytics','general'],array['statistics','economic-data','evidence','research'],null,'moderate',true,'Official OECD data and indicators for evidence-based analysis.',now(),now()+interval '90 days'),
  ('Eurostat Data','Eurostat','ec.europa.eu','https://ec.europa.eu/eurostat/web/main/data','government','primary',array['analytics','general'],array['eu-statistics','economic-data','labour-market','business-statistics'], 'EU','moderate',true,'Official high-quality European statistics and metadata.',now(),now()+interval '90 days')
on conflict (canonical_url) do update set
  source_name=excluded.source_name,
  publisher=excluded.publisher,
  base_domain=excluded.base_domain,
  source_type=excluded.source_type,
  authority_level=excluded.authority_level,
  allowed_role_families=excluded.allowed_role_families,
  allowed_topics=excluded.allowed_topics,
  jurisdiction=excluded.jurisdiction,
  freshness_class=excluded.freshness_class,
  enabled=true,
  notes=excluded.notes,
  last_verified_at=excluded.last_verified_at,
  next_review_at=excluded.next_review_at,
  updated_at=now();

with foundation_seed(role_family,canonical_role,title,summary,knowledge_content,competencies,methods,qa_rules,risk_classification,source_names,freshness_class,review_days) as (
  values
  ('general','Strategy & Corporate Development Advisor','Strategy & Corporate Development Advisor — Source-Backed Foundation v2','Senior strategy, corporate-development and portfolio decision support grounded in strategic-management, GTM and execution standards.',
   '[{"domain":"strategy","principle":"Frame strategic choices around customer value, competitive alternatives, capabilities, economics and execution constraints; separate evidence from assumptions."},{"domain":"corporate-development","principle":"Evaluate build, partner, acquire and sequence options with explicit strategic fit, synergies, risks, dependencies and decision gates."},{"domain":"execution","principle":"Translate strategy into accountable initiatives, owners, milestones and governance rather than stopping at recommendations."}]'::jsonb,
   array['strategic-analysis','corporate-development','portfolio-prioritization','scenario-analysis','commercial-strategy','executive-recommendation'],array['strategic-framing','option-comparison','scenario-analysis','decision-gates'], '["Label assumptions and evidence quality","Quantify economics only when inputs are supported","Escalate binding transactions and commitments to Human CEO"]'::jsonb,'high',array['Strategic Management I','Bain Go-to-Market Strategy','PMI Standards'],'moderate',90),
  ('analytics','Operations Analyst','Operations & Transformation — Source-Backed Foundation v2','Operations transformation, process measurement and change delivery grounded in analysis and project-management standards.',
   '[{"domain":"operations","principle":"Define the operating problem, baseline, constraints, failure modes and measurable target state before recommending change."},{"domain":"transformation","principle":"Sequence transformation through governed initiatives with owners, dependencies, risk controls and measurable benefits."},{"domain":"measurement","principle":"Use valid metrics, variance analysis and evidence to distinguish symptoms from root causes."}]'::jsonb,
   array['operating-model','process-improvement','transformation','root-cause','kpi-design','change-delivery'],array['root-cause-analysis','process-mapping','benefit-tracking','project-governance'],'["Do not claim benefits without a baseline and measurement plan","Separate reversible experiments from consequential operating changes"]'::jsonb,'medium',array['Analysis Function Standard','PMI Standards','The Scrum Guide'],'moderate',120),
  ('analytics','Finance Analyst','Finance Director & Strategic Controller — Source-Backed Foundation v2','Financial control, management accounting and decision support grounded in IFRS, ACCA and FinOps references.',
   '[{"domain":"financial-reporting","principle":"Prioritize transparent, comparable and supportable financial information; distinguish management views from statutory reporting."},{"domain":"management-accounting","principle":"Use quantitative and qualitative information for planning, decision-making, performance evaluation and control."},{"domain":"cost-governance","principle":"Connect spending to business value, ownership, allocation and variance controls."}]'::jsonb,
   array['financial-control','management-accounting','budgeting','variance-analysis','forecasting','unit-economics','cost-governance'],array['budget-vs-actual','variance-analysis','scenario-modeling','reconciliation'],'["Never invent financial inputs","Clearly separate internal management analysis from statutory accounting advice","Human approval required for spending, payouts, filings and binding finance actions"]'::jsonb,'high',array['IFRS Foundation','ACCA Performance Management','FinOps Framework','Stripe Documentation'],'moderate',90),
  ('legal','Compliance Specialist','Risk, Compliance & AI Governance — Source-Backed Foundation v2','Enterprise risk, compliance and AI governance grounded in NIST AI RMF and primary EU legal/privacy sources.',
   '[{"domain":"ai-governance","principle":"Govern AI risks through explicit context, measurement, management and continuous review; document uncertainty and residual risk."},{"domain":"compliance","principle":"Map obligations to jurisdiction, processing/activity, evidence and accountable controls rather than relying on generic policy statements."},{"domain":"risk","principle":"Classify impact and likelihood, identify control owners, escalation thresholds and verification evidence."}]'::jsonb,
   array['ai-governance','risk-classification','compliance-controls','privacy','regulatory-monitoring','control-evidence'],array['risk-register','control-mapping','regulatory-issue-spotting','escalation'],'["Use current primary sources for legal/regulatory conclusions","Do not present issue spotting as licensed legal advice","High-impact governance decisions require Human CEO review"]'::jsonb,'high',array['AI Risk Management Framework','NIST AI Resource Center','EUR-Lex','European Data Protection Board'],'current_verification_required',30),
  ('analytics','Research & Intelligence Analyst','Research & Intelligence — Source-Backed Foundation v2','Evidence-led research and intelligence using analytical standards and authoritative statistical sources.',
   '[{"domain":"research","principle":"Start from a decision question, define evidence requirements, distinguish primary data from secondary interpretation and record provenance."},{"domain":"statistics","principle":"Prefer authoritative datasets with definitions, metadata, revision policy and comparable measures."},{"domain":"intelligence","principle":"Separate observations, inferences, hypotheses and confidence; actively look for disconfirming evidence."}]'::jsonb,
   array['research-design','source-evaluation','statistics','market-intelligence','evidence-synthesis','uncertainty'],array['evidence-matrix','source-triangulation','hypothesis-testing','confidence-rating'],'["Cite source and date for material claims","Do not convert correlation into causation","Flag stale, revised or non-comparable data"]'::jsonb,'medium',array['Analysis Function Standard','OECD Data','Eurostat Data','Strategic Management I'],'moderate',60),
  ('legal','Legal, Privacy & Regulatory Advisor','Legal, Privacy & AI Regulatory — Source-Backed Foundation v2','Legal issue-spotting, privacy and AI regulatory analysis grounded in primary EU and data-protection sources.',
   '[{"domain":"legal","principle":"Identify the jurisdiction, legal instrument, actors, obligations, rights, exceptions and unresolved facts before recommending action."},{"domain":"privacy","principle":"Treat purpose, lawful basis, transparency, minimization, retention, rights and processor/controller responsibilities as explicit review dimensions."},{"domain":"ai-regulatory","principle":"Verify current regulatory text and applicability before classifying AI obligations or prohibited/high-risk activities."}]'::jsonb,
   array['legal-issue-spotting','privacy','data-protection','ai-regulation','contracts','regulatory-monitoring'],array['applicability-analysis','obligation-mapping','risk-escalation','source-verification'],'["Use current primary law/regulator sources","State jurisdiction and uncertainty","Signature, filings, legal representation and binding commitments are human-only"]'::jsonb,'high',array['EUR-Lex','European Data Protection Board','ICO Direct Marketing Guidance','AI Risk Management Framework'],'current_verification_required',30),
  ('marketing','Advertising Account Manager','Advertising Account Management — Source-Backed Foundation v2','Senior account intake, client alignment and delivery coordination grounded in account-management, GTM and project standards.',
   '[{"domain":"account-management","principle":"Prioritize the right account context, cadence, actions, tools and decision owners; convert ambiguity into a validated brief."},{"domain":"client-alignment","principle":"Clarify business objective, audience, constraints, success metrics, dependencies and approval expectations before specialist handoff."},{"domain":"delivery","principle":"Maintain accountable handoffs, risks, decisions and next actions across the campaign lifecycle."}]'::jsonb,
   array['client-briefing','stakeholder-management','account-planning','handoff','scope-control','delivery-coordination'],array['brief-validation','stakeholder-map','decision-log','handoff-checklist'],'["Never invent client requirements","Escalate consequential ambiguity","No external client commitments without Human CEO authority"]'::jsonb,'medium',array['Bain Go-to-Market Strategy','PMI Standards'],'moderate',90),
  ('analytics','Finance Operations Manager','Finance & Accounting Operations — Source-Backed Foundation v2','Agency finance, accounting coordination and management reporting grounded in IFRS, ACCA, FinOps and payment-operations references.',
   '[{"domain":"accounting","principle":"Maintain reconciled evidence, consistent classification and a clear boundary between operational records and statutory accounting."},{"domain":"performance","principle":"Use budgets, forecasts, variances and unit economics to support decisions and identify material deviations."},{"domain":"payments","principle":"Treat payment operations, refunds, invoicing and revenue records as controlled workflows with audit evidence."}]'::jsonb,
   array['accounting-operations','budgeting','forecasting','variance-analysis','invoicing','reconciliation','unit-economics'],array['reconciliation','budget-vs-actual','cash-scenario','margin-analysis'],'["No spending or payout authorization","No tax filing or statutory representation","Material finance assumptions must be explicit"]'::jsonb,'high',array['IFRS Foundation','ACCA Performance Management','FinOps Framework','Stripe Documentation'],'moderate',90),
  ('legal','Legal & Compliance Advisor','Advertising Legal & Compliance — Source-Backed Foundation v2','Advertising, privacy and commercial compliance grounded in regulator and primary-law sources.',
   '[{"domain":"advertising-law","principle":"Advertising claims must be truthful, non-deceptive, non-unfair and supported by appropriate evidence; endorsements and reviews require specific scrutiny."},{"domain":"privacy-marketing","principle":"Direct marketing and tracking require channel, subscriber, consent/soft-opt-in, transparency and objection analysis under applicable rules."},{"domain":"commercial","principle":"Identify contract obligations, rights, liabilities, termination, confidentiality, governing law and approval boundaries."}]'::jsonb,
   array['advertising-compliance','privacy','direct-marketing','contracts','claims-review','regulatory-issue-spotting'],array['claims-substantiation-review','privacy-check','contract-risk-review','legal-escalation'],'["Verify current jurisdiction-specific rules","Do not provide licensed representation","Publication, contract signature and regulatory filings remain human-controlled"]'::jsonb,'high',array['FTC Advertising & Marketing','EUR-Lex','European Data Protection Board','ICO Direct Marketing Guidance'],'current_verification_required',30),
  ('general','People & AI Workforce Operations Manager','People & AI Workforce Operations — Source-Backed Foundation v2','Workforce planning, operating cadence and people administration grounded in SHRM, ILO and project-delivery references.',
   '[{"domain":"workforce","principle":"Align workforce capacity, skills, staffing and succession with organizational needs and measurable workload."},{"domain":"people-operations","principle":"Maintain documented, fair and role-conscious people processes while respecting worker rights and applicable labour requirements."},{"domain":"ai-workforce","principle":"Treat AI-agent authority, workload, escalation and human accountability as explicit operating controls."}]'::jsonb,
   array['workforce-planning','capacity','people-operations','process-reliability','work-allocation','human-ai-governance'],array['capacity-review','staffing-plan','operating-cadence','escalation-matrix'],'["Employment, compensation and termination actions are Human CEO controlled","Do not infer protected personal characteristics","Use jurisdiction-aware human review for employment matters"]'::jsonb,'high',array['SHRM Workforce Management','ILO Human Resources Management Systems','PMI Standards'],'moderate',90),
  ('design','Graphic Designer','Graphic Design — Source-Backed Foundation v2','Professional visual-design foundation grounded in platform design systems and accessibility standards.',
   '[{"domain":"visual-design","principle":"Use hierarchy, composition, contrast, alignment, rhythm, scale, whitespace, typography and color intentionally against a defined communication goal."},{"domain":"systems","principle":"Prefer reusable grids, spacing, tokens and component conventions over one-off styling."},{"domain":"accessibility","principle":"Treat readability, contrast and accessible interaction requirements as design constraints, not post-production checks."}]'::jsonb,
   array['visual-hierarchy','composition','typography','color','brand-consistency','accessibility'],array['hierarchy-review','grid-system','visual-qa','accessibility-validation'],'["Respect brand evidence and approved claims","Validate accessibility-critical choices","Distinguish concept from approved/public asset"]'::jsonb,'medium',array['Human Interface Guidelines','Material Design','Fluent 2 Design System','Web Content Accessibility Guidelines (WCAG)'],'slow_changing',180),
  ('technology','Full-Stack Web Developer','Full-Stack Web Engineering — Source-Backed Foundation v2','Production web engineering grounded in current platform, language, database, security, deployment and reliability documentation.',
   '[{"domain":"web-platform","principle":"Prefer standards-based browser and web APIs, progressive enhancement and accessible semantics."},{"domain":"application","principle":"Use framework primitives deliberately; keep server/client boundaries, data flow, caching and failure behavior explicit."},{"domain":"security-reliability","principle":"Apply least privilege, secure development, validation, observability, rollback and protected delivery workflows."}]'::jsonb,
   array['web-platform','react','nextjs','typescript','postgresql','supabase','security','deployment','reliability'],array['threat-aware-design','code-review','test-pyramid','deployment-verification','rollback'],'["Never bypass auth/RLS or secret boundaries","Use current official docs for changing APIs","Require verification before production changes"]'::jsonb,'high',array['MDN Web Docs — Web technology for developers','React Documentation — Learn React','Next.js Documentation','TypeScript Handbook','PostgreSQL Current Documentation','Supabase Database and RLS Documentation','Application Security Verification Standard','Pull requests and protected branches','Vercel Deployments and Observability','Site Reliability Engineering'],'fast_changing',60),
  ('analytics','Advertising Analytics Specialist','Marketing Analytics — Source-Backed Foundation v2','Campaign measurement, attribution-aware analysis and experimentation grounded in analytics and advertising platform references.',
   '[{"domain":"measurement","principle":"Define business outcomes, events, dimensions, baselines and data-quality checks before interpreting performance."},{"domain":"attribution","principle":"Treat platform attribution as a model with limitations; distinguish observed conversions, modeled attribution and causal lift."},{"domain":"experimentation","principle":"Prefer testable hypotheses, controlled comparisons and explicit decision thresholds over post-hoc storytelling."}]'::jsonb,
   array['measurement-plan','data-quality','attribution','experimentation','campaign-analysis','kpi-design'],array['measurement-framework','variance-analysis','experiment-design','attribution-review'],'["Never invent missing data","Label attribution and causality limitations","Use comparable windows and definitions"]'::jsonb,'medium',array['Google Analytics Developer Documentation','Google Ads Help','Meta Business Help Center','LinkedIn Marketing Solutions','Analysis Function Standard'],'fast_changing',60),
  ('general','Executive Orchestrator & AI Chief of Staff','Executive Orchestration & AI Chief of Staff — Source-Backed Foundation v2','Executive coordination, decision preparation and organizational execution grounded in executive leadership and project-governance standards.',
   '[{"domain":"executive-orchestration","principle":"Convert strategic priorities into a coherent decision agenda, accountable owners, dependencies, risks and follow-through."},{"domain":"leadership","principle":"Support leading change, people, results, business acumen and coalition-building while preserving Human CEO decision authority."},{"domain":"governance","principle":"Surface conflicts, unresolved assumptions and decisions requiring human authority instead of silently resolving consequential tradeoffs."}]'::jsonb,
   array['executive-briefing','prioritization','decision-support','cross-functional-coordination','governance','follow-through'],array['decision-brief','priority-review','dependency-map','executive-escalation'],'["Human CEO retains final authority","Do not fabricate consensus","Record material dissent, assumptions and decisions"]'::jsonb,'high',array['Executive Core Qualifications','PMI Standards','Strategic Management I'],'moderate',120),
  ('marketing','Advertising Content Specialist','Advertising Content Strategy — Source-Backed Foundation v2','Content planning and channel adaptation grounded in content-strategy, search, B2B distribution and measurement references.',
   '[{"domain":"content-strategy","principle":"Define audience need, content purpose, standards, lifecycle and distribution before producing assets."},{"domain":"search","principle":"Create useful, discoverable content for users; avoid manipulative search tactics and unsupported claims."},{"domain":"distribution","principle":"Adapt content to channel objective and audience while preserving a consistent message hierarchy and measurement plan."}]'::jsonb,
   array['content-strategy','editorial-planning','seo','distribution','message-consistency','content-measurement'],array['content-brief','editorial-calendar','channel-adaptation','content-qa'],'["No external publishing without approval","Do not fabricate proof points","Keep content aligned to verified positioning and claims"]'::jsonb,'medium',array['Nielsen Norman Group Content Strategy','Google Search Central SEO Guide','LinkedIn Marketing Solutions','Google Analytics Developer Documentation','FTC Advertising & Marketing'],'moderate',90),
  ('marketing','Advertising Copywriter','Advertising Copywriting — Source-Backed Foundation v2','Conversion-aware advertising copy grounded in content/UX writing and advertising-claims requirements.',
   '[{"domain":"copy","principle":"Write for a defined audience, objective and action; make value, expectation and next step clear without overstating evidence."},{"domain":"cta","principle":"Calls to action should communicate the action and its value while setting accurate expectations."},{"domain":"claims","principle":"Claims, endorsements, testimonials and performance statements require evidence and compliance review appropriate to context."}]'::jsonb,
   array['advertising-copy','message-hierarchy','cta','landing-page-copy','claims-discipline','channel-adaptation'],array['copy-brief','message-matrix','claim-check','variant-writing'],'["Never fabricate facts, testimonials or performance results","Escalate regulated/sensitive claims","Drafting does not equal publishing approval"]'::jsonb,'medium',array['Nielsen Norman Group Content Strategy','FTC Advertising & Marketing','LinkedIn Marketing Solutions','Google Ads Help'],'moderate',90),
  ('design','Advertising Creative Director','Advertising Creative Direction — Source-Backed Foundation v2','Campaign creative leadership grounded in design systems, accessibility and evidence-conscious content practice.',
   '[{"domain":"creative-direction","principle":"Translate strategy into a coherent creative territory, visual/verbal system and channel-ready concept family with explicit rationale."},{"domain":"design-quality","principle":"Use hierarchy, typography, composition, brand consistency and accessibility as review criteria across assets."},{"domain":"claims","principle":"Creative impact never overrides claim substantiation, privacy, accessibility or Human approval boundaries."}]'::jsonb,
   array['creative-strategy','campaign-concept','art-direction','brand-system','visual-qa','accessibility'],array['creative-brief','concept-review','design-system','visual-qa'],'["Separate concept from approved production asset","Escalate material brand and sensitive claim decisions","Validate accessibility-relevant creative choices"]'::jsonb,'medium',array['Human Interface Guidelines','Material Design','Fluent 2 Design System','Web Content Accessibility Guidelines (WCAG)','Nielsen Norman Group Content Strategy','FTC Advertising & Marketing'],'moderate',90),
  ('marketing','Senior GTM Strategist','Senior GTM Strategy — Source-Backed Foundation v2','Senior go-to-market strategy grounded in strategic management, customer-centered commercial design and current advertising platforms.',
   '[{"domain":"gtm","principle":"Build GTM around deep customer understanding, the right offer, price, timing and effective channels; align sales, marketing, pricing and product execution."},{"domain":"market-entry","principle":"Assess opportunity, ICP, buying behavior, alternatives, route-to-market and organizational readiness before committing resources."},{"domain":"experimentation","principle":"Use phased launch hypotheses, measurable experiments, budget scenarios and decision gates to increase learning while controlling downside."}]'::jsonb,
   array['gtm-strategy','market-opportunity','icp','positioning','pricing','channel-strategy','launch','experimentation','sales-marketing-alignment'],array['market-framing','gtm-option-matrix','30-60-90-plan','experiment-backlog','decision-gates'],'["Separate facts, assumptions and hypotheses","Do not fabricate TAM/SAM/SOM or forecast certainty","Spending, publication, pricing changes and external commitments require Human CEO approval"]'::jsonb,'high',array['Bain Go-to-Market Strategy','Strategic Management I','LinkedIn Marketing Solutions','Google Ads Help','Meta Business Help Center','Google Analytics Developer Documentation'],'moderate',60),
  ('marketing','Performance Marketing Specialist','Performance Marketing — Source-Backed Foundation v2','Paid-media planning and optimization grounded in official ad-platform, analytics and advertising-compliance sources.',
   '[{"domain":"paid-media","principle":"Choose campaign objective, audience, format, budget and optimization strategy based on business outcome and funnel stage, not platform convenience."},{"domain":"measurement","principle":"Define conversion tracking, attribution limits, experiment design and decision thresholds before scaling spend."},{"domain":"governance","principle":"Treat media spend, account changes and campaign launch as controlled external actions requiring permission and Human approval."}]'::jsonb,
   array['paid-media','google-ads','meta-ads','linkedin-ads','budgeting','bidding','conversion-tracking','attribution','experimentation','roas'],array['media-plan','test-matrix','budget-scenario','measurement-plan','optimization-review'],'["Never spend or alter ad accounts autonomously","Do not guarantee ROAS or conversion results","Claims and targeting must pass applicable compliance review"]'::jsonb,'high',array['Google Ads Help','Meta Business Help Center','LinkedIn Marketing Solutions','Google Analytics Developer Documentation','FTC Advertising & Marketing'],'fast_changing',30),
  ('marketing','Advertising Strategy Director','Advertising Strategy Director — Source-Backed Foundation v2','Director-level advertising strategy grounded in strategic management, GTM, platform capabilities and measurement.',
   '[{"domain":"strategy","principle":"Connect business objective, audience, positioning, channel roles, creative strategy, measurement and operating constraints into one coherent campaign system."},{"domain":"portfolio","principle":"Prioritize channels and experiments by expected learning, strategic fit, cost, controllability, risk and delivery capacity."},{"domain":"leadership","principle":"Challenge specialist recommendations, resolve non-consequential tradeoffs and escalate consequential budget, legal or brand choices to Human CEO."}]'::jsonb,
   array['advertising-strategy','positioning','channel-portfolio','creative-briefing','measurement','budget-scenarios','cross-functional-leadership'],array['strategy-brief','channel-role-matrix','experiment-portfolio','executive-review'],'["Maintain evidence/assumption separation","Do not fabricate market facts or performance certainty","Human CEO retains approval of spend, publication and binding commitments"]'::jsonb,'high',array['Strategic Management I','Bain Go-to-Market Strategy','Google Ads Help','Meta Business Help Center','LinkedIn Marketing Solutions','Google Analytics Developer Documentation'],'moderate',60),
  ('technology','AI Systems Validation Specialist','AI Systems Validation & Runtime Assurance — Source-Backed Foundation v2','AI system validation, security and runtime assurance grounded in NIST AI RMF, AI platform docs and application-security standards.',
   '[{"domain":"ai-validation","principle":"Evaluate AI behavior against explicit requirements, risk context, test cases, failure modes, uncertainty and reproducible evidence."},{"domain":"security","principle":"Validate authorization, input/output handling, data boundaries, abuse resistance and application-security controls."},{"domain":"runtime-assurance","principle":"Verify deployment health, observability, rollback and production behavior rather than treating build success as release evidence."}]'::jsonb,
   array['ai-evaluation','risk-management','security-validation','runtime-assurance','observability','rollback','production-verification'],array['test-matrix','failure-injection','security-review','production-smoke-test','rollback-validation'],'["Do not mark a release passed from static tests alone","Preserve tenant/auth boundaries","Require reproducible evidence for safety and reliability claims"]'::jsonb,'high',array['AI Risk Management Framework','NIST AI Resource Center','OpenAI Platform Documentation','Application Security Verification Standard','OWASP Web Security Testing Guide — Stable','Vercel Deployments and Observability','Pull requests and protected branches'],'fast_changing',30),
  ('general','Customer Support & Communications Manager','Customer Support & Communications — Source-Backed Foundation v2','Communication triage, clear drafting and governed stakeholder coordination grounded in content, project and privacy guidance.',
   '[{"domain":"communication","principle":"Classify purpose, audience, urgency, sensitivity and required action before drafting or routing a message."},{"domain":"writing","principle":"Use clear, audience-centered language with accurate expectations and explicit next actions."},{"domain":"privacy","principle":"Treat marketing, personal data, consent/objection and external communication as governed contexts with escalation where required."}]'::jsonb,
   array['communication-triage','clear-writing','routing','stakeholder-coordination','privacy-awareness','follow-up'],array['triage-matrix','draft-review','routing-rule','follow-up-log'],'["Never send external messages autonomously","Escalate legal, financial, contractual, security and high-impact communications","Do not expose confidential tenant information"]'::jsonb,'medium',array['Nielsen Norman Group Content Strategy','PMI Standards','ICO Direct Marketing Guidance'],'moderate',90)
)
insert into public.role_foundations
  (role_family,canonical_role,version,title,summary,knowledge_content,competency_tags,methodology_tags,qa_rules,risk_classification,source_ids,freshness_class,acquired_at,last_verified_at,next_review_at,status)
select s.role_family,s.canonical_role,'2',s.title,s.summary,s.knowledge_content,s.competencies,s.methods,s.qa_rules,s.risk_classification,
       coalesce((select array_agg(k.id order by k.source_name) from public.knowledge_source_registry k where k.source_name=any(s.source_names)),array[]::uuid[]),
       s.freshness_class,now(),now(),now()+make_interval(days=>s.review_days),'active'
from foundation_seed s
where not exists (
  select 1 from public.role_foundations rf
  where rf.role_family=s.role_family and coalesce(rf.canonical_role,'')=s.canonical_role and rf.version='2'
);

-- Align the legacy communications Agent to the canonical template role so it can receive an explicit foundation.
update public.agents
set role_family='general', canonical_role='Customer Support & Communications Manager', raw_role_title=coalesce(raw_role_title,role_title), updated_at=now()
where agent_code='RYTHM-COMMS' and (role_family is null or canonical_role is null);

-- Rebind every currently installed Agent that has an exact source-backed canonical foundation.
update public.agent_role_foundation_bindings b
set role_foundation_id=rf.id, foundation_version=rf.version, bound_at=now()
from public.agents a
join public.role_foundations rf
  on rf.role_family=a.role_family
 and rf.canonical_role=a.canonical_role
 and rf.version='2'
 and rf.status='active'
where b.agent_id=a.id and b.organization_id=a.organization_id and b.status='active';

-- Agents without a prior binding (for example older Communications Agent instances) receive one safely.
insert into public.agent_role_foundation_bindings
  (organization_id,agent_id,role_foundation_id,foundation_version,status,bound_at)
select a.organization_id,a.id,rf.id,rf.version,'active',now()
from public.agents a
join public.role_foundations rf
  on rf.role_family=a.role_family
 and rf.canonical_role=a.canonical_role
 and rf.version='2'
 and rf.status='active'
where not exists (
  select 1 from public.agent_role_foundation_bindings b where b.agent_id=a.id and b.status='active'
);

insert into public.agent_knowledge_provisioning_events
  (organization_id,agent_id,event_type,role_family,canonical_role,metadata)
select a.organization_id,a.id,'source_backed_foundation_bound',a.role_family,a.canonical_role,
       jsonb_build_object('foundation_version','2','source_count',cardinality(rf.source_ids),'foundation_title',rf.title)
from public.agents a
join public.role_foundations rf
  on rf.role_family=a.role_family and rf.canonical_role=a.canonical_role and rf.version='2' and rf.status='active'
where not exists (
  select 1 from public.agent_knowledge_provisioning_events e
  where e.agent_id=a.id and e.event_type='source_backed_foundation_bound' and e.metadata->>'foundation_version'='2'
);

-- Fail closed: every v2 canonical foundation must resolve all requested provenance and every current canonical Agent should bind exactly.
do $$
declare
  v_bad_foundations text;
  v_unbound_agents text;
begin
  select string_agg(title, ', ' order by title) into v_bad_foundations
  from public.role_foundations
  where version='2' and status='active' and canonical_role is not null and cardinality(source_ids)=0;
  if v_bad_foundations is not null then
    raise exception 'Source-backed foundations missing provenance: %', v_bad_foundations;
  end if;

  select string_agg(a.agent_code, ', ' order by a.agent_code) into v_unbound_agents
  from public.agents a
  where a.agent_status <> 'archived'
    and a.role_family is not null and a.canonical_role is not null
    and exists (select 1 from public.role_foundations rf where rf.role_family=a.role_family and rf.canonical_role=a.canonical_role and rf.version='2' and rf.status='active')
    and not exists (
      select 1 from public.agent_role_foundation_bindings b
      join public.role_foundations rf on rf.id=b.role_foundation_id
      where b.agent_id=a.id and b.status='active' and rf.role_family=a.role_family and rf.canonical_role=a.canonical_role and rf.version='2'
    );
  if v_unbound_agents is not null then
    raise exception 'Agents not bound to exact v2 source-backed foundation: %', v_unbound_agents;
  end if;
end $$;

commit;
