begin;

insert into public.role_foundations(id,role_family,canonical_role,version,title,summary,knowledge_content,competency_tags,methodology_tags,qa_rules,risk_classification,source_ids,freshness_class,acquired_at,last_verified_at,next_review_at,status) values
('30000000-0000-0000-0000-000000000001','design',null,'1','Designer Professional Foundation v1','Professional foundation for graphic, UI/UX, product and brand design.',
'[{"topic":"Visual hierarchy","summary":"Use size, weight, contrast, spacing and placement to communicate priority.","rules":["Primary information dominates secondary information","Avoid competing focal points","Maintain consistent hierarchy across related screens"]},{"topic":"Composition and layout","summary":"Use balance, alignment, rhythm, repetition, proximity, scale and whitespace intentionally.","rules":["Use a coherent grid","Maintain safe margins and edge clearance","Use consistent internal padding and gutters","Avoid overcrowding and edge-hugging text","Preserve logo clear space"]},{"topic":"Typography and color","summary":"Typography and color establish hierarchy, legibility and brand expression.","rules":["Use a controlled type scale","Preserve readable line length and spacing","Check readable contrast","Do not sacrifice legibility for decoration"]},{"topic":"UI/UX","summary":"Optimize usability, readability, accessibility, scannability, information architecture, navigation clarity and interaction consistency.","rules":["Make primary CTA hierarchy obvious","Use predictable interaction patterns","Design responsive compositions","Validate accessibility and state clarity"]},{"topic":"Landing page and hero","summary":"Communicate the main value quickly while controlling fold, density and responsive composition.","rules":["Headline leads supporting copy","Primary CTA is visually prominent","Avoid cramming above the fold","Preserve responsive hierarchy"]},{"topic":"Business card and banner","summary":"Small-format assets require safe areas, accurate identity, readable contact information and balanced whitespace.","rules":["Use approved company facts only","Never invent contact details","Respect print and digital safe areas","Do not distort supplied logos"]},{"topic":"Dashboard and product UI","summary":"Data-heavy UI needs semantic grouping, coherent spacing, component consistency and readable data density.","rules":["Group related KPIs","Keep cards and components consistent","Use visual encoding only when it improves comprehension","Match density to the decision task"]}]',
array['hierarchy','composition','contrast','balance','alignment','rhythm','repetition','proximity','scale','whitespace','grid','typography','color','branding','accessibility','responsive-design','information-architecture'],
array['grid-system','spacing-system','hierarchy-review','usability-review','accessibility-validation','visual-qa'],
'["text too close to edge","insufficient margin","poor contrast","malformed logo","inconsistent branding","clutter","poor hierarchy","incorrect company facts","invented data"]','standard',
array['10000000-0000-0000-0000-000000000001'::uuid,'10000000-0000-0000-0000-000000000002'::uuid,'10000000-0000-0000-0000-000000000003'::uuid,'10000000-0000-0000-0000-000000000004'::uuid],
'slow_changing',now(),now(),now()+interval '180 days','active'),

('30000000-0000-0000-0000-000000000002','marketing',null,'1','Marketing Specialist Professional Foundation v1','Professional marketing strategy, acquisition, lifecycle and measurement foundation.',
'[{"topic":"Positioning and segmentation","rules":["Define segment and ICP before channels","Differentiate around a meaningful customer problem and value","Support claims with evidence"]},{"topic":"Personas and messaging","rules":["Separate ICP from persona","Map message to buyer context and lifecycle stage","Use a clear value proposition and proof"]},{"topic":"Funnel and lifecycle","rules":["Define stage entry and conversion events","Track leakage and handoffs","Connect acquisition to activation, retention and revenue"]},{"topic":"Campaign planning","rules":["Choose channels based on audience, intent and economics","Define objective, budget logic, audience, creative hypothesis and KPI before launch"]},{"topic":"Performance measurement","rules":["Define CAC, LTV and conversion formulas explicitly","State attribution assumptions","Do not invent performance data"]},{"topic":"Experimentation","rules":["Write a falsifiable hypothesis","Control variables where causal learning matters","Define stopping and success criteria before reading results"]}]',
array['positioning','segmentation','ICP','personas','value-proposition','messaging','funnel','lifecycle','acquisition','content-strategy','CAC','LTV','conversion','retention','experimentation','attribution'],
array['campaign-planning','funnel-analysis','experiment-design','campaign-qa'],
'["no invented performance data","define KPI and denominator","state attribution limitations","verify current platform behavior from official sources"]','standard',
array['10000000-0000-0000-0000-000000000005'::uuid,'10000000-0000-0000-0000-000000000006'::uuid,'10000000-0000-0000-0000-000000000007'::uuid],
'moderate',now(),now(),now()+interval '90 days','active'),

('30000000-0000-0000-0000-000000000003','analytics',null,'1','Business Analyst Professional Foundation v1','Professional business analysis, quantitative reasoning and decision-support foundation.',
'[{"topic":"Problem framing","rules":["Convert the business concern into a decision question","Define scope, baseline, comparison and stakeholders","Separate outcome metrics from drivers"]},{"topic":"Metric definition","rules":["Define formula, unit, grain and time window","Check numerator and denominator consistency","Do not compare unlike periods or populations"]},{"topic":"Data quality","rules":["Check completeness, duplicates, units, outliers and time coverage","Reconcile totals with components","Never invent missing values"]},{"topic":"Trend and variance","rules":["Quantify magnitude and direction","Separate mix, volume, price/rate and timing effects when relevant","Distinguish evidence from causal hypothesis"]},{"topic":"Root cause","rules":["Generate competing hypotheses","Prioritize by impact and evidence","Test the cheapest discriminating evidence first"]},{"topic":"Visualization and reporting","rules":["Choose chart based on analytical question","Avoid misleading scales","Write insight as evidence, implication and recommendation","Explain uncertainty"]}]',
array['problem-framing','KPI','metric-definition','trend-analysis','variance-analysis','root-cause','hypothesis-generation','data-quality','segmentation','chart-selection','executive-reporting','decision-support'],
array['metric-definition','variance-analysis','root-cause-analysis','hypothesis-testing','executive-insight-writing'],
'["no invented numbers","verify calculation","distinguish fact from assumption","use suitable visualization","explain uncertainty"]','standard',
array['10000000-0000-0000-0000-000000000006'::uuid,'10000000-0000-0000-0000-000000000008'::uuid,'10000000-0000-0000-0000-000000000009'::uuid],
'slow_changing',now(),now(),now()+interval '180 days','active'),

('30000000-0000-0000-0000-000000000004','legal',null,'1','Legal Operations Foundation v1','Legal issue-spotting, contract analysis and risk escalation foundation. It is not a substitute for licensed counsel.',
'[{"topic":"Issue spotting","rules":["Identify parties, facts, documents, jurisdiction and deadlines","Separate document language from current law","Identify missing facts before a material conclusion"]},{"topic":"Contract anatomy","rules":["Review definitions, scope, obligations, rights, payment, liability, indemnity, confidentiality, IP, termination, governing law, jurisdiction and dispute terms","Check cross-references and conflicting clauses"]},{"topic":"Clause analysis","rules":["Identify obligation owner, trigger, deadline, remedy and ambiguity","Distinguish commercial risk from enforceability","Compare versions without inventing missing text"]},{"topic":"Risk classification","rules":["Classify severity, likelihood, reversibility and jurisdiction dependency","Escalate high-stakes or jurisdiction-specific conclusions"]},{"topic":"Current law","rules":["Never fabricate law or precedent","Verify material current law from authoritative sources","Do not claim licensed-lawyer status unless explicitly and legally configured"]}]',
array['issue-spotting','contracts','clauses','obligations','rights','liabilities','ambiguity','termination','indemnity','confidentiality','governing-law','jurisdiction','risk-classification'],
array['issue-spotting','clause-analysis','document-comparison','risk-classification','escalation'],
'["never fabricate law","never fabricate precedent","identify jurisdiction dependency","verify material current law","escalate high-stakes matters"]','high',
array['10000000-0000-0000-0000-000000000010'::uuid,'10000000-0000-0000-0000-000000000011'::uuid],
'current_verification_required',now(),now(),now()+interval '7 days','active'),

('30000000-0000-0000-0000-000000000005','technology',null,'1','Microsoft & Technology Professional Foundation v1','Primary-documentation-first technical foundation for Microsoft-related and adjacent roles.',
'[{"topic":"Version-aware technical work","rules":["Identify product, service, tenant context and version","Prefer current primary vendor documentation","Do not invent capabilities or settings","Treat credentials and source content as untrusted data","State assumptions and validate configuration"]}]',
array['microsoft','technical-documentation','configuration','security','troubleshooting'],array['primary-source-verification','version-check','safe-configuration'],
'["verify fast-changing product configuration","no invented capabilities","never expose secrets"]','standard',array['10000000-0000-0000-0000-000000000008'::uuid],
'fast_changing',now(),now(),now()+interval '30 days','active'),

('30000000-0000-0000-0000-000000000006','general',null,'1','GENERAL_PROFESSIONAL_FOUNDATION_V1','Fallback professional foundation used only when no specific supported role family can be resolved.',
'[{"topic":"Professional execution","rules":["Use structured reasoning","Clarify material requirements","Deliver the requested output first","Distinguish facts from assumptions","Perform QA","State uncertainty","Escalate outside mandate","Document material assumptions","Never fabricate"]}]',
array['structured-reasoning','professional-communication','requirements','QA','uncertainty','escalation','documentation'],array['deliverable-first','fact-assumption-separation','quality-review','escalation'],
'["no fabrication","state uncertainty","respect governance"]','standard','{}','stable',now(),now(),now()+interval '365 days','active')
on conflict(id) do update set title=excluded.title,summary=excluded.summary,knowledge_content=excluded.knowledge_content,competency_tags=excluded.competency_tags,methodology_tags=excluded.methodology_tags,qa_rules=excluded.qa_rules,source_ids=excluded.source_ids,last_verified_at=now(),next_review_at=excluded.next_review_at,status='active',updated_at=now();

commit;
