-- RYTHM OS — Phase 3 Google Workspace bootstrap read catalog.
-- These capabilities are read-only and isolated from existing Calendar write / Email send paths.

insert into public.integration_tool_registry (
  tool_id,
  integration_key,
  name,
  version,
  category,
  metadata,
  adapter_version,
  enabled,
  kill_switch,
  updated_at
) values (
  'google_workspace.bootstrap',
  'google_workspace',
  'Google Workspace Company Bootstrap',
  '3.0.0-pilot',
  'company_bootstrap',
  jsonb_build_object(
    'phase', 3,
    'pilot', 'gmail_google_calendar',
    'read_only', true,
    'raw_email_bodies', false,
    'attachments', false
  ),
  'google_workspace-bootstrap-v1',
  true,
  false,
  now()
)
on conflict (tool_id) do update set
  integration_key = excluded.integration_key,
  name = excluded.name,
  version = excluded.version,
  category = excluded.category,
  metadata = excluded.metadata,
  adapter_version = excluded.adapter_version,
  enabled = excluded.enabled,
  updated_at = now();

insert into public.integration_capabilities (
  provider_key,
  capability_key,
  risk_level,
  default_approval_mode,
  description,
  tool_id,
  operation,
  internal_external,
  read_write,
  external_side_effect,
  financial_impact,
  data_sensitivity,
  risk_ceiling,
  reversibility,
  required_agent_permissions,
  required_user_permissions,
  required_scopes,
  idempotency_supported,
  timeout_ms,
  retry_policy,
  rate_limits,
  adapter_version,
  rollback_supported,
  enabled,
  kill_switch
) values
(
  'google_workspace',
  'gmail.bootstrap.read',
  'low',
  'autonomous',
  'Read bounded Gmail message metadata for Human CEO initiated Company Auto-Bootstrap. No message bodies or attachments.',
  'google_workspace.bootstrap',
  'gmail.bootstrap.read',
  'external',
  'read',
  false,
  false,
  'confidential',
  'low',
  'not_applicable',
  array['read_email_metadata']::text[],
  array['read']::text[],
  array['gmail.readonly']::text[],
  true,
  20000,
  '{"maxAttempts":3,"baseDelayMs":200,"maxDelayMs":1500}'::jsonb,
  '{"userPerHour":20,"organizationPerHour":100,"agentPerHour":20,"integrationPerHour":100,"operationPerHour":50}'::jsonb,
  'google_workspace-bootstrap-v1',
  false,
  true,
  false
),
(
  'google_workspace',
  'calendar.bootstrap.read',
  'low',
  'autonomous',
  'Read bounded Google Calendar event metadata for Human CEO initiated Company Auto-Bootstrap. Descriptions and locations are excluded.',
  'google_workspace.bootstrap',
  'calendar.bootstrap.read',
  'external',
  'read',
  false,
  false,
  'confidential',
  'low',
  'not_applicable',
  array['read_calendar_metadata']::text[],
  array['read']::text[],
  array['calendar.readonly']::text[],
  true,
  20000,
  '{"maxAttempts":3,"baseDelayMs":200,"maxDelayMs":1500}'::jsonb,
  '{"userPerHour":20,"organizationPerHour":100,"agentPerHour":20,"integrationPerHour":100,"operationPerHour":50}'::jsonb,
  'google_workspace-bootstrap-v1',
  false,
  true,
  false
)
on conflict (provider_key, capability_key) do update set
  risk_level = excluded.risk_level,
  default_approval_mode = excluded.default_approval_mode,
  description = excluded.description,
  tool_id = excluded.tool_id,
  operation = excluded.operation,
  internal_external = excluded.internal_external,
  read_write = excluded.read_write,
  external_side_effect = excluded.external_side_effect,
  financial_impact = excluded.financial_impact,
  data_sensitivity = excluded.data_sensitivity,
  risk_ceiling = excluded.risk_ceiling,
  reversibility = excluded.reversibility,
  required_agent_permissions = excluded.required_agent_permissions,
  required_user_permissions = excluded.required_user_permissions,
  required_scopes = excluded.required_scopes,
  idempotency_supported = excluded.idempotency_supported,
  timeout_ms = excluded.timeout_ms,
  retry_policy = excluded.retry_policy,
  rate_limits = excluded.rate_limits,
  adapter_version = excluded.adapter_version,
  rollback_supported = excluded.rollback_supported,
  enabled = excluded.enabled,
  kill_switch = excluded.kill_switch;
