insert into public.integration_providers (
  provider_key,
  display_name,
  category,
  supports_oauth,
  supports_token,
  enabled,
  version,
  allowed_environments,
  kill_switch,
  setup_availability,
  connection_adapter_key,
  resource_discovery_supported,
  setup_plan,
  ai_setup_enabled,
  ai_setup_rollout,
  browser_playbook_ready,
  updated_at
) values (
  'bing_webmaster',
  'Bing Webmaster Tools',
  'seo_search',
  true,
  false,
  true,
  '1.0.0',
  array['production','preview']::text[],
  false,
  'available',
  'bing_webmaster',
  true,
  '{}'::jsonb,
  false,
  'off',
  false,
  now()
)
on conflict (provider_key) do update set
  display_name = excluded.display_name,
  category = excluded.category,
  supports_oauth = excluded.supports_oauth,
  supports_token = excluded.supports_token,
  enabled = excluded.enabled,
  version = excluded.version,
  allowed_environments = excluded.allowed_environments,
  kill_switch = excluded.kill_switch,
  setup_availability = excluded.setup_availability,
  connection_adapter_key = excluded.connection_adapter_key,
  resource_discovery_supported = excluded.resource_discovery_supported,
  updated_at = now();

insert into public.integration_capabilities (
  provider_key,
  capability_key,
  risk_level,
  default_approval_mode,
  description,
  internal_external,
  read_write,
  external_side_effect,
  financial_impact,
  data_sensitivity,
  risk_ceiling,
  reversibility,
  required_agent_permissions,
  required_user_permissions,
  required_scopes,
  idempotency_supported,
  timeout_ms,
  retry_policy,
  rate_limits,
  adapter_version,
  rollback_supported,
  enabled,
  kill_switch
) values (
  'bing_webmaster',
  'read.bing_webmaster',
  'low',
  'autonomous',
  'Read verified Bing Webmaster sites and SEO/search performance data',
  'external',
  'read',
  false,
  false,
  'internal',
  'low',
  'not_applicable',
  array[]::text[],
  array[]::text[],
  array['Webmaster.read']::text[],
  true,
  15000,
  '{"maxDelayMs":1000,"baseDelayMs":100,"maxAttempts":1}'::jsonb,
  '{}'::jsonb,
  'oauth-v1',
  false,
  true,
  false
)
on conflict (provider_key, capability_key) do update set
  risk_level = excluded.risk_level,
  default_approval_mode = excluded.default_approval_mode,
  description = excluded.description,
  required_scopes = excluded.required_scopes,
  enabled = true,
  kill_switch = false;
