import Link from "next/link";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createAuthServerClient } from "@/lib/supabase/auth-server";
import DeliberationConsole from "./DeliberationConsole";
import SessionPreparationForm,{MeetingDraftCleanup} from "./SessionPreparationForm";

export const dynamic="force-dynamic";

type Agent={id:string;agent_code:string;display_name:string|null;name:string;role_title:string;avatar_url:string|null;presence_status:string;purpose:string|null;work_style:string|null;enabled:boolean};
type Meeting={id:string;project_id:string|null;title:string;purpose:string;status:string;agenda:unknown;created_at:string};
type Session={id:string;meeting_id:string;project_id:string|null;status:string;decision_question:string;language:string;max_rounds:number;budget_cap_usd:number;recommendation:string|null;decision_options:unknown;synthesis:string|null;error_message:string|null;estimated_cost_usd:number};
type Participant={agent_id:string;seat_order:number;session_role:string;agents:Agent|Agent[]|null};
type Message={id:string;turn_index:number;round_no:number;message_type:string;content:string;agent_id:string|null;agents:Pick<Agent,"agent_code"|"display_name"|"name"|"role_title">|Pick<Agent,"agent_code"|"display_name"|"name"|"role_title">[]|null};
type LegalDecisionReview={outcome:string|null;executive_note:string|null;risk_summary:string|null;conditions:unknown;licensed_counsel_required:boolean};
type Props={searchParams:Promise<{meeting?:string;session?:string;project?:string;message?:string;error?:string}>};

const CUSTOM_CEO_OPTION="__custom_ceo_decision__";
const list=(value:unknown)=>Array.isArray(value)?value.map(String):[];
const joinedAgent=<T,>(value:T|T[]|null):T|null=>Array.isArray(value)?value[0]??null:value;

async function ownerContext(){
  const supabase=await createAuthServerClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect("/login");
  const {data:membership}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("role","owner").maybeSingle();
  if(!membership)redirect("/login?error=Owner%20authorization%20required.");
  return{supabase,user,organizationId:membership.organization_id as string};
}

async function prepareSession(formData:FormData){
  "use server";
  const {supabase,user,organizationId}=await ownerContext();
  const meetingId=String(formData.get("meetingId")??"");
  const decisionQuestion=String(formData.get("decisionQuestion")??"").trim();
  const language=String(formData.get("language")??"English").trim()||"English";
  const rounds=Math.max(1,Math.min(3,Number(formData.get("rounds")??2)));
  const budget=Math.max(0,Math.min(10,Number(formData.get("budgetCapUsd")??1.5)));
  const requestedAgentIds=formData.getAll("agentIds").map(String).filter(Boolean);
  if(!meetingId||decisionQuestion.length<10||requestedAgentIds.length<2)redirect(`/meetings/room?meeting=${meetingId}&error=${encodeURIComponent("Select at least two enabled Agents and provide a decision question. Your draft is preserved on this device.")}`);
  const {data:meeting}=await supabase.from("meetings").select("id,project_id,status").eq("id",meetingId).eq("organization_id",organizationId).maybeSingle();
  if(!meeting)redirect("/meetings/room?error=Meeting%20not%20found.");
  if(["completed","cancelled"].includes(meeting.status))redirect(`/meetings/room?meeting=${meetingId}&error=${encodeURIComponent("Completed or cancelled meetings cannot start a new Agent session.")}`);
  const {data:agents}=await supabase.from("agents").select("id,agent_code,enabled").eq("organization_id",organizationId).in("id",requestedAgentIds);
  const selected=agents??[];const valid=selected.filter(a=>a.agent_code!=="T-001"&&a.enabled);
  if(selected.length!==requestedAgentIds.length||valid.length!==requestedAgentIds.length)redirect(`/meetings/room?meeting=${meetingId}&error=${encodeURIComponent("Paused or unavailable Agents cannot be authorized. Your draft is preserved.")}`);
  if(!valid.some(a=>a.agent_code==="B-001"))redirect(`/meetings/room?meeting=${meetingId}&error=${encodeURIComponent("Enabled B-001 Executive Orchestrator is required for governed synthesis. Your draft is preserved.")}`);
  const {data:session,error}=await supabase.from("meeting_agent_sessions").insert({organization_id:organizationId,meeting_id:meetingId,project_id:meeting.project_id,status:"ready",decision_question:decisionQuestion,language,max_rounds:rounds,budget_cap_usd:budget,external_research_allowed:false}).select("id").single();
  if(error||!session)redirect(`/meetings/room?meeting=${meetingId}&error=${encodeURIComponent("Agent session could not be created. Refresh and retry; your draft is preserved.")}`);
  const ordered=valid.sort((a,b)=>requestedAgentIds.indexOf(a.id)-requestedAgentIds.indexOf(b.id));
  const {error:participantError}=await supabase.from("meeting_agent_participants").insert(ordered.map((a,index)=>({session_id:session.id,organization_id:organizationId,agent_id:a.id,seat_order:index+1,session_role:a.agent_code==="B-001"?"synthesizer":"advisor",explicitly_authorized_by_ceo:true})));
  if(participantError){await supabase.from("meeting_agent_sessions").delete().eq("id",session.id).eq("organization_id",organizationId).eq("status","ready");redirect(`/meetings/room?meeting=${meetingId}&error=${encodeURIComponent("Selected Agents could not be authorized. Your draft is preserved.")}`);}
  await supabase.from("audit_events").insert({organization_id:organizationId,actor_type:"user",actor_user_id:user.id,event_type:"meeting.agent_session_prepared",object_type:"meeting",object_id:meetingId,risk_level:"medium",payload:{session_id:session.id,agents:ordered.map(a=>a.agent_code),rounds,budget_cap_usd:budget,external_actions:false,external_research:false,enabled_agents_only:true}});
  revalidatePath("/meetings/room");redirect(`/meetings/room?meeting=${meetingId}&session=${session.id}&message=${encodeURIComponent("Multi-Agent session prepared. Start the meeting when ready.")}`);
}

async function startMeeting(formData:FormData){
  "use server";
  const {supabase,user,organizationId}=await ownerContext();const meetingId=String(formData.get("meetingId")??"");const sessionId=String(formData.get("sessionId")??"");const now=new Date().toISOString();
  const {data:meeting}=await supabase.from("meetings").select("id,status,title").eq("id",meetingId).eq("organization_id",organizationId).maybeSingle();
  if(!meeting||!["draft","scheduled"].includes(meeting.status))redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=This%20meeting%20cannot%20be%20started.`);
  const {data:session}=await supabase.from("meeting_agent_sessions").select("id,status").eq("id",sessionId).eq("meeting_id",meetingId).eq("organization_id",organizationId).maybeSingle();
  if(!session||session.status!=="ready")redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=The%20governed%20Agent%20session%20is%20not%20ready.`);
  const {data:rows}=await supabase.from("meeting_agent_participants").select("agent_id,agents(agent_code,enabled)").eq("session_id",sessionId).eq("organization_id",organizationId).eq("explicitly_authorized_by_ceo",true);
  const participantAgents=(rows??[]).map(r=>joinedAgent(r.agents as {agent_code:string;enabled:boolean}|{agent_code:string;enabled:boolean}[]|null)).filter((a):a is {agent_code:string;enabled:boolean}=>Boolean(a));
  if(participantAgents.length<2||participantAgents.some(a=>!a.enabled)||!participantAgents.some(a=>a.agent_code==="B-001"&&a.enabled))redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("Meeting start blocked. At least two enabled Agents including B-001 are required.")}`);
  const {error}=await supabase.from("meetings").update({status:"running",started_at:now}).eq("id",meetingId).eq("organization_id",organizationId).in("status",["draft","scheduled"]);
  if(error)redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=Meeting%20could%20not%20be%20started.`);
  await supabase.from("audit_events").insert({organization_id:organizationId,actor_type:"user",actor_user_id:user.id,event_type:"meeting.started",object_type:"meeting",object_id:meetingId,risk_level:"low",payload:{title:meeting.title,multi_agent_session_id:sessionId,human_chair:true,enabled_agents_verified:true}});
  revalidatePath("/meetings/room");revalidatePath("/meetings");redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&message=${encodeURIComponent("Meeting started. Human CEO has chair control.")}`);
}

async function recordCeoDecision(formData:FormData){
  "use server";
  const {supabase,organizationId}=await ownerContext();const meetingId=String(formData.get("meetingId")??"");const sessionId=String(formData.get("sessionId")??"");const selectedOptionKey=String(formData.get("selectedOption")??"").trim();const customDecision=String(formData.get("customDecision")??"").trim();const rationale=String(formData.get("rationale")??"").trim();const riskLevel=String(formData.get("riskLevel")??"medium");const isCustomDecision=selectedOptionKey===CUSTOM_CEO_OPTION;
  if(!selectedOptionKey||rationale.length<3||!["low","medium","high","critical"].includes(riskLevel))redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=Select%20a%20decision%20option%20and%20enter%20CEO%20rationale.`);
  if(isCustomDecision&&(customDecision.length<10||customDecision.length>2000))redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("Enter a custom Human CEO decision between 10 and 2000 characters.")}`);
  const {data:meeting}=await supabase.from("meetings").select("id,status,title,project_id").eq("id",meetingId).eq("organization_id",organizationId).maybeSingle();if(!meeting||meeting.status!=="completed")redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("The Human CEO / Chair must explicitly close the meeting first.")}`);
  const {data:session}=await supabase.from("meeting_agent_sessions").select("id,project_id,status,decision_question,decision_options,recommendation,synthesis,legal_triage_status,legal_triage_reason").eq("id",sessionId).eq("meeting_id",meetingId).eq("organization_id",organizationId).maybeSingle();if(!session||session.status!=="completed")redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=The%20latest%20Agent%20synthesis%20must%20finish%20first.`);if(session.legal_triage_status==="pending")redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("Legal relevance triage must finish before the final CEO decision.")}`);
  let legalReview:LegalDecisionReview|null=null;if(session.legal_triage_status==="recommended"){const result=await supabase.from("meeting_legal_reviews").select("outcome,executive_note,risk_summary,conditions,licensed_counsel_required,status").eq("session_id",sessionId).eq("organization_id",organizationId).eq("status","completed").order("created_at",{ascending:false}).limit(1).maybeSingle();legalReview=result.data as LegalDecisionReview|null;if(!legalReview)redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("Complete the A-106 AI Legal Review before recording the final CEO decision.")}`);if(legalReview.licensed_counsel_required||legalReview.outcome==="LICENSED_COUNSEL_REQUIRED")redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("Licensed counsel review is required before finalization.")}`);if(legalReview.outcome==="RISK_IDENTIFIED"&&!['high','critical'].includes(riskLevel))redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=${encodeURIComponent("Material legal risk requires High or Critical decision risk.")}`);}
  const options=list(session.decision_options);if(!isCustomDecision&&!options.includes(selectedOptionKey))redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=The%20selected%20option%20is%20not%20part%20of%20the%20meeting%20package.`);const selectedOption=isCustomDecision?`Custom Human CEO Decision: ${customDecision}`:selectedOptionKey;const recordedOptions=isCustomDecision?[...options,selectedOption]:options;const decisionSource=isCustomDecision?"Human CEO — Custom":"Human CEO — selected from B-001 decision package";
  const {data:b001}=await supabase.from("agents").select("id").eq("organization_id",organizationId).eq("agent_code","B-001").maybeSingle();const {data:project}=session.project_id?await supabase.from("projects").select("project_code,name").eq("id",session.project_id).eq("organization_id",organizationId).maybeSingle():{data:null};const projectPrefix=project?`${project.project_code} — ${project.name}`:"Company-wide";const title=meeting.title.toLowerCase().includes(String(project?.project_code??"").toLowerCase())&&project?.project_code?meeting.title:`${projectPrefix}: ${meeting.title}`;const legalContext=legalReview?` AI Legal Review: ${legalReview.outcome}. ${legalReview.executive_note??""}`:"";const context=`Project: ${projectPrefix}. Meeting: ${meeting.title}. Decision source: ${decisionSource}. Question: ${session.decision_question}.${legalContext}`;const legalMinutes=legalReview?`\n\nAI Legal Review (${legalReview.outcome}): ${legalReview.executive_note??""}\nRisk summary: ${legalReview.risk_summary??""}`:"";
  const {data:decisionId,error}=await supabase.rpc("record_meeting_ceo_decision",{target_org_id:organizationId,target_meeting_id:meetingId,target_session_id:sessionId,target_project_id:session.project_id,target_title:title,target_context:context,target_options:recordedOptions,target_recommendation:session.recommendation?{text:session.recommendation}:null,target_rationale:rationale,target_risk_level:riskLevel,target_selected_option:selectedOption,target_legal_triage_status:session.legal_triage_status,target_legal_review_outcome:legalReview?.outcome??null,target_synthesis:session.synthesis??"",target_legal_minutes:legalMinutes,target_proposed_by_agent_id:b001?.id??null});
  if(error||!decisionId)redirect(`/meetings/room?meeting=${meetingId}&session=${sessionId}&error=Decision%20could%20not%20be%20recorded.`);const {data:decision}=await supabase.from("decisions").select("id,status").eq("id",String(decisionId)).eq("organization_id",organizationId).maybeSingle();const decisionStatus=decision?.status??(["high","critical"].includes(riskLevel)?"review":"approved");revalidatePath("/meetings/room");revalidatePath("/meetings");revalidatePath("/decisions");revalidatePath("/approvals");revalidatePath("/command-center");redirect(`/decisions?decision=${String(decisionId)}&status=${decisionStatus}&message=${decisionStatus==="review"?"Meeting%20decision%20created%20for%20governed%20approval.":"Meeting%20decision%20recorded%20by%20Human%20CEO."}`);
}

export default async function Boardroom({searchParams}:Props){
  const params=await searchParams;const {supabase,organizationId}=await ownerContext();const [{data:meetingData},{data:agentData}]=await Promise.all([supabase.from("meetings").select("id,project_id,title,purpose,status,agenda,created_at").eq("organization_id",organizationId).in("status",["draft","scheduled","running","completed"]).order("created_at",{ascending:false}).limit(30),supabase.from("agents").select("id,agent_code,display_name,name,role_title,avatar_url,presence_status,purpose,work_style,enabled").eq("organization_id",organizationId).neq("agent_code","T-001").order("agent_code")]);
  const allMeetings=(meetingData??[]) as Meeting[];const meetings=params.project?allMeetings.filter(i=>i.project_id===params.project):allMeetings;const agents=(agentData??[]) as Agent[];const selectedMeetingId=params.meeting??null;const meeting=selectedMeetingId?meetings.find(m=>m.id===selectedMeetingId)??((await supabase.from("meetings").select("id,project_id,title,purpose,status,agenda,created_at").eq("organization_id",organizationId).eq("id",selectedMeetingId).maybeSingle()).data as Meeting|null):null;
  let session:Session|null=null;if(meeting){let q=supabase.from("meeting_agent_sessions").select("id,meeting_id,project_id,status,decision_question,language,max_rounds,budget_cap_usd,recommendation,decision_options,synthesis,error_message,estimated_cost_usd").eq("organization_id",organizationId).eq("meeting_id",meeting.id);if(params.session)q=q.eq("id",params.session);const result=await q.order("created_at",{ascending:false}).limit(1).maybeSingle();session=result.data as Session|null;}
  let participants:Participant[]=[];let messages:Message[]=[];if(session){const [pr,mr]=await Promise.all([supabase.from("meeting_agent_participants").select("agent_id,seat_order,session_role,agents(id,agent_code,display_name,name,role_title,avatar_url,presence_status,purpose,work_style,enabled)").eq("organization_id",organizationId).eq("session_id",session.id).order("seat_order"),supabase.from("meeting_agent_messages").select("id,turn_index,round_no,message_type,content,agent_id,agents(agent_code,display_name,name,role_title)").eq("organization_id",organizationId).eq("session_id",session.id).order("turn_index")]);participants=(pr.data??[]) as unknown as Participant[];messages=(mr.data??[]) as unknown as Message[];}
  const seatedAgents=participants.map(p=>joinedAgent(p.agents)).filter((a):a is Agent=>Boolean(a));const transcript=messages.map(m=>{const a=joinedAgent(m.agents);const human=m.message_type==="ceo_decision"||m.message_type==="ceo_contribution";return{id:m.id,turnIndex:m.turn_index,roundNo:m.round_no,messageType:m.message_type,content:m.content,speakerCode:human?"CEO":a?.agent_code??"SYSTEM",speakerName:human?"Human CEO":a?.display_name??a?.name??"System",speakerRole:human?"Meeting Chair":a?.role_title??"Meeting Runtime"};});const decisionOptions=session?list(session.decision_options):[];
  return <main className="command-shell" style={{maxWidth:"100%",overflowX:"hidden"}}>
    <header className="command-header"><div><p className="eyebrow">RYTHM EXECUTIVE BOARDROOM</p><h1>Live governed multi-Agent meetings</h1><p className="subtitle">Human CEO-led deliberation with explicit chair control, traceable interventions, challenge rounds, synthesis and governed decisions.</p></div><Link className="secondary-button" href="/meetings">Meeting Engine</Link></header>
    <section className="organization-banner"><div><span>Meeting chair</span><strong>Human CEO</strong></div><div><span>Agent mode</span><strong>Enabled internal Agents only</strong></div><div><span>External actions / research</span><strong>Disabled · separately approval-gated</strong></div></section>
    {params.message?<p className="form-success">{params.message}</p>:null}{params.error?<p className="form-error">{params.error}</p>:null}
    <section className="panel panel-wide" style={{marginTop:18,minWidth:0,maxWidth:"100%",boxSizing:"border-box"}}><div className="panel-heading"><div><p className="label">Boardroom context</p><h2>{meeting?.title??"Select a meeting"}</h2></div>{meeting?<div className="row-meta"><span>{meeting.status}</span>{session?<b className={session.status==="completed"?"state-active":"state-paused"}>{session.status} Agent session</b>:null}</div>:null}</div><form method="get" style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,minWidth:0}}>{params.project?<input type="hidden" name="project" value={params.project}/>:null}<select name="meeting" defaultValue={meeting?.id??""}><option value="">Select meeting</option>{meetings.map(i=><option key={i.id} value={i.id}>{i.title} · {i.status}</option>)}</select><button className="secondary-button">Open in Boardroom</button></form>{meeting?<><p style={{color:"#596579",lineHeight:1.65}}>{meeting.purpose}</p><p className="label">Agenda</p><ol style={{color:"#596579",lineHeight:1.7}}>{list(meeting.agenda).map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ol></>:<p className="security-note">Choose the meeting you want to govern.</p>}</section>
    {meeting&&!session?<section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">CEO authorization</p><h2>Prepare Multi-Agent Session</h2></div></div><SessionPreparationForm meetingId={meeting.id} agents={agents} action={prepareSession}/></section>:null}
    {meeting&&session?<><MeetingDraftCleanup meetingId={meeting.id}/><section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">Decision mandate</p><h2>{session.decision_question}</h2></div><span className="pill">{session.max_rounds} rounds · ${Number(session.budget_cap_usd).toFixed(2)} cap</span></div>{meeting.status!=="running"&&["draft","scheduled"].includes(meeting.status)?<form action={startMeeting}><input type="hidden" name="meetingId" value={meeting.id}/><input type="hidden" name="sessionId" value={session.id}/><button>Enter Boardroom & start governed meeting</button></form>:null}<DeliberationConsole sessionId={session.id} meetingStatus={meeting.status} initialStatus={session.status} initialMessages={transcript} initialError={session.error_message} meetingTitle={meeting.title} decisionQuestion={session.decision_question} maxRounds={session.max_rounds} budgetCapUsd={Number(session.budget_cap_usd)} participants={seatedAgents.map(a=>({id:a.id,agentCode:a.agent_code,name:a.display_name??a.name,roleTitle:a.role_title,avatarUrl:a.avatar_url,enabled:a.enabled}))}/></section>
    {session.status==="completed"&&meeting.status==="completed"?<section className="panel panel-wide" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">Human CEO gate</p><h2>Record the meeting decision</h2></div><span className="pill">Agent recommendation is advisory</span></div><div style={{padding:14,borderRadius:12,background:"#f8f9fb",marginBottom:14}}><p className="label">B-001 recommendation</p><p style={{color:"#596579",lineHeight:1.65}}>{session.recommendation??"Review the synthesis and choose an option."}</p></div><form action={recordCeoDecision} className="auth-form"><input type="hidden" name="meetingId" value={meeting.id}/><input type="hidden" name="sessionId" value={session.id}/><label>CEO selected option<select name="selectedOption" required defaultValue=""><option value="" disabled>Select decision</option>{decisionOptions.map(o=><option key={o} value={o}>{o}</option>)}<option value={CUSTOM_CEO_OPTION}>Other — Custom Human CEO Decision</option></select></label><label>CEO custom decision<textarea name="customDecision" minLength={10} maxLength={2000} rows={3}/></label><label>CEO rationale<textarea name="rationale" required minLength={3} rows={5}/></label><label>Decision risk<select name="riskLevel" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High — routes to Approval Engine</option><option value="critical">Critical — routes to Approval Engine</option></select></label><button>Record Human CEO decision</button><p className="security-note">The Human CEO may choose a B-001 option or record a custom decision. High/Critical decisions route to governed approval.</p></form></section>:null}</>:null}
  </main>;
}
