'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/Button';
import type {Clarification} from '@/lib/company-core/contract';
type Agent={id:string;name:string;role_title:string;agent_status:string;reports_to_agent_id:string|null};
type Obligation={id:string;owner_agent_id:string;next_action:string;follow_up_at:string;resume_condition:string;status:string};
type Budget={id:string;category:string;currency:string;authorized_ceiling:number;committed:number;actual:number;remaining:number};
type Operating={project:{name:string;stage:string;accountable_agent_id:string};team:Agent[];obligations:Obligation[];budgets:Budget[];proposals:Array<{id:string;title:string;execution_result:{bridge_status?:string}}>};
type CustomerRound={id:string;status:string;answers:Record<string,unknown>;questions:Clarification[];submitted_at:string|null};
export default function CompanyOperatingPanel({projectId}:{projectId:string}){
 const [state,setState]=useState<Operating|null>(null),[questions,setQuestions]=useState<Clarification[]>([]),[rounds,setRounds]=useState<CustomerRound[]>([]),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 async function refresh(){const responses=await Promise.all([fetch(`/api/projects/operating?projectId=${projectId}`,{cache:'no-store'}).then(r=>r.json()),fetch(`/api/projects/clarifications?projectId=${projectId}`,{cache:'no-store'}).then(r=>r.json())]);if(responses[0].ok)setState(responses[0]);if(responses[1].ok){setQuestions(responses[1].questions);setRounds(responses[1].forms);}if(responses.some(r=>!r.ok))setNotice('Operating state could not be loaded.');}
 useEffect(()=>{let cancelled=false;Promise.all([fetch(`/api/projects/operating?projectId=${projectId}`,{cache:'no-store'}).then(r=>r.json()),fetch(`/api/projects/clarifications?projectId=${projectId}`,{cache:'no-store'}).then(r=>r.json())]).then(([a,b])=>{if(cancelled)return;if(a.ok)setState(a);if(b.ok){setQuestions(b.questions);setRounds(b.forms);}}).catch(()=>{if(!cancelled)setNotice('Could not load project operating state.');});return()=>{cancelled=true;};},[projectId]);
 async function act(endpoint:string,body:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setNotice('Saving…');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,...body})});const b=await r.json();if(!b.ok)throw new Error(b.error);setNotice(b.nextAction??'Saved.');await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Could not save.');}finally{lock.current=false;setBusy(false);}}
 async function openFile(formId:string,questionId:string){try{const r=await fetch(`/api/projects/clarifications/files?projectId=${projectId}&formId=${formId}&questionId=${questionId}`,{cache:'no-store'});const b=await r.json();if(!b.ok)throw new Error(b.error);window.open(b.url,'_blank','noopener,noreferrer');}catch(e){setNotice(e instanceof Error?e.message:'File unavailable.');}}
 const director=state?.team.find(a=>a.id===state.project.accountable_agent_id);
 return <section className="panel" style={{marginTop:18}}><p className="label">Company operating core</p><h2>{state?.project.name??'Project accountability'}</h2><p>Executive Director: <strong>{director?.name??'Awaiting ownership migration'}</strong> · Phase: {state?.project.stage??'Loading…'}</p><Button disabled={busy} onClick={()=>act('/api/projects/executive-evaluation',{})}>Run synthetic executive evaluation</Button><details><summary>Organizational hierarchy</summary><p>Human CEO → Executive Director → Department Managers → Specialists</p>{director?<ul>{state?.team.filter(a=>a.reports_to_agent_id===director.id).map(manager=><li key={manager.id}>{manager.name} · {manager.agent_status}<ul>{state.team.filter(a=>a.reports_to_agent_id===manager.id).map(a=><li key={a.id}>{a.name} · {a.role_title} · {a.agent_status}</li>)}</ul></li>)}</ul>:null}</details>
 <details><summary>Project execution flow</summary><p>Intake → Manager clarification → Reviewed roadmap → Delegation and governed execution → Quality and verification → Ready for delivery → Acceptance → Closeout</p></details>
 {state?.obligations.length?<div><h3>Owners and next actions</h3>{state.obligations.map(o=><details key={o.id}><summary>{o.next_action} · {o.status}</summary><p>Owner: {state.team.find(a=>a.id===o.owner_agent_id)?.name} · Follow-up: {new Date(o.follow_up_at).toLocaleDateString()}</p><p>Resume when: {o.resume_condition}</p></details>)}</div>:null}
 <details><summary>Approved execution intent requiring review</summary>{state?.proposals.filter(p=>!['dispatched','completed','no_external_action'].includes(p.execution_result?.bridge_status??'')).map(p=><form key={p.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/api/projects/operating',{action:'review_execution',proposalId:p.id,externalRequired:f.get('external')==='yes',evidence:f.get('evidence'),noReplayConfirmed:f.has('noReplay')});}}><p>{p.title} · {p.execution_result?.bridge_status??'Awaiting dispatch'}</p><label>Execution required<select name="external"><option value="yes">External action required</option><option value="no">Internal work only</option></select></label><label>Evidence and remaining scope after checking completed actions<input name="evidence" required/></label><label><input name="noReplay" type="checkbox" required/> I checked external references; this continuation will not replay completed actions</label><Button disabled={busy} type="submit">Record intent and continuation</Button></form>)}</details>
 <h3>Budget status</h3>{state?.budgets.length?<div style={{overflowX:'auto'}}><table><thead><tr><th>Category</th><th>Authorized</th><th>Committed</th><th>Actual</th><th>Remaining</th></tr></thead><tbody>{state.budgets.map(b=><tr key={b.id}><td>{b.category} · {b.currency}</td><td>{b.authorized_ceiling}</td><td>{b.committed}</td><td>{b.actual}</td><td>{b.remaining}</td></tr>)}</tbody></table></div>:<p>No spending authorization recorded. Approximate budgets support planning.</p>}
 <details><summary>Record project budget</summary><form className="auth-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/api/projects/operating',{action:'budget',category:f.get('category'),currency:f.get('currency'),periodStart:f.get('start'),periodEnd:f.get('end'),approximateMin:Number(f.get('min')),approximateMax:Number(f.get('max')),authorizedCeiling:Number(f.get('ceiling')),authorize:f.has('authorize'),authorizationReference:f.get('reference')});}}><label>Category<select name="category"><option value="media">Media spend</option><option value="service_fees">Service fees</option><option value="third_party">Third-party expenses</option><option value="internal">Internal AI / infrastructure</option></select></label><label>Currency<input name="currency" defaultValue="EUR" pattern="[A-Z]{3}" required/></label><label>Period start<input name="start" type="date" required/></label><label>Period end<input name="end" type="date" required/></label><label>Approximate minimum<input name="min" type="number" min="0" step="0.01"/></label><label>Approximate maximum<input name="max" type="number" min="0" step="0.01"/></label><label>Authorized ceiling<input name="ceiling" type="number" min="0" step="0.01" defaultValue="0"/></label><label><input name="authorize" type="checkbox"/> I authorize spending within this ceiling and period</label><label>Customer / manager authorization reference<input name="reference"/></label><Button type="submit" disabled={busy}>Save budget</Button></form></details>
 <h3>Manager clarification packet</h3>{questions.filter(q=>q.status==='open').map(q=><details key={q.id}><summary><input aria-label={`Refer ${q.question} to customer`} type="checkbox" checked={selected.includes(q.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,q.id]:v.filter(id=>id!==q.id))}/> {q.question}</summary><p>{q.reason}</p><p>Required stage: {q.required_stage??'planning'}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('/api/projects/clarifications',{action:'answer',questionId:q.id,answer:q.input_type==='multi_choice'?f.getAll('answer'):f.get('answer')});}}>{Array.isArray(q.options)&&q.options.length?q.input_type==='multi_choice'?q.options.map(o=><label key={String(o)}><input type="checkbox" name="answer" value={String(o)}/>{String(o)}</label>):<select aria-label={q.question} name="answer">{q.options.map(o=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<input aria-label={q.question} name="answer" required/>}<Button type="submit" disabled={busy}>Complete directly</Button></form><Button disabled={busy} onClick={()=>act('/api/projects/clarifications',{action:'explain',questionId:q.id})}>Request explanation</Button>{q.omission_permitted&&!q.consent_required&&q.materiality!=='required'?<form onSubmit={e=>{e.preventDefault();void act('/api/projects/clarifications',{action:'waive',questionId:q.id,reason:new FormData(e.currentTarget).get('reason')});}}><input aria-label="Waiver reason" name="reason" required/><Button disabled={busy} type="submit">Waive with reason</Button></form>:null}</details>)}<Button disabled={busy||!selected.length} onClick={()=>act('/api/projects/clarifications',{action:'refer_customer',questionIds:selected})}>Prepare selected questions for customer</Button>
 {rounds.length?<details><summary>Customer information requests and submissions</summary>{rounds.map(round=><div key={round.id}><p>{round.status} · {round.submitted_at?'Submitted for manager review':'Awaiting customer'}</p>{round.status==='submitted'?round.questions.map(q=><div key={q.id}><p>{q.question}: {q.input_type==='file'?'Uploaded document':JSON.stringify(round.answers[q.id]??'Unanswered')}</p>{q.input_type==='file'&&round.answers[q.id]?<Button onClick={()=>openFile(round.id,q.id)}>Review document</Button>:null}<Button disabled={busy} onClick={()=>act('/api/projects/clarifications',{action:'answer',questionId:q.id,answer:round.answers[q.id]})}>Validate answer</Button></div>):null}<Button disabled={busy||!selected.length} onClick={()=>act('/api/projects/clarifications',{action:'refer_customer',questionIds:selected,previousFormId:round.id})}>Request correction for selected questions</Button><Button disabled={busy||round.status==='revoked'} onClick={()=>act('/api/projects/clarifications',{action:'revoke_form',formId:round.id})}>Revoke link</Button></div>)}</details>:null}<p role="status" aria-live="polite">{notice}</p></section>;
}
