"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type LiveTask={id:string;title:string;status:string;priority:number;assigned_agent_id:string|null;waiting_on_approval_id:string|null;started_at?:string|null;completed_at?:string|null;updated_at?:string|null;agents?:{agent_code?:string;display_name?:string;name?:string}|null};
type LiveApproval={id:string;subject_type:string;subject_id:string;title:string;summary:string;risk_level:string;status:string;created_at:string;expires_at:string|null};
type LiveActivity={id:string;event_type:string;headline:string;detail:string|null;importance:string;created_at:string};
type LiveAgent={agent_id:string;status:string;assignment_role:string;agents?:{agent_code?:string;display_name?:string;name?:string;role_title?:string}|null};
type ProgressSnapshot={progressPercent:number;completedTasks:number;totalTasks:number;runningTasks:number;queuedTasks:number;awaitingApproval:number;blockedTasks:number;failedTasks:number;lastActivityAt:string|null};
type LivePayload={ok:boolean;project:{id:string;name:string;project_code:string;status:string;stage:string;progress_percent:number|null;last_heartbeat_at:string|null};progressSnapshot:ProgressSnapshot;execution:{id:string;execution_no:number;status:string;started_at:string|null;last_heartbeat_at:string|null;updated_at:string|null}|null;counts:{running:number;queued:number;waitingApproval:number;waitingOther:number;completed:number;failed:number;total:number};tasks:LiveTask[];approvals:LiveApproval[];activity:LiveActivity[];agents:LiveAgent[];serverTime:string};
type Props={projectId:string;initialStatus:string};

const statusLabel=(value:string)=>value.replaceAll("_"," ");
const initials=(value:string)=>value.split(/\s+/).map(v=>v[0]).join("").slice(0,2).toUpperCase();
const since=(value:string|null|undefined)=>{if(!value)return "—";const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return `${seconds}s`;const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes}m`;return `${Math.floor(minutes/60)}h`;};

export function ProjectLiveOperations({projectId,initialStatus}:Props){
  const [data,setData]=useState<LivePayload|null>(null);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [busyApproval,setBusyApproval]=useState<string|null>(null);
  const [notes,setNotes]=useState<Record<string,string>>({});
  const [,setTick]=useState(0);

  const load=useCallback(async()=>{
    try{
      const response=await fetch(`/api/projects/live?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store"});
      const payload=await response.json() as LivePayload&{error?:string};
      if(!response.ok||!payload.ok)throw new Error(payload.error||"Live project state is unavailable.");
      setData(payload);setError("");
    }catch(e){setError(e instanceof Error?e.message:"Live project state is unavailable.");}
  },[projectId]);

  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>setTick(v=>v+1),1000);return()=>window.clearInterval(timer);},[]);

  const resolve=async(approval:LiveApproval,resolution:"approved"|"rejected")=>{
    const typed=(notes[approval.id]??"").trim();
    if(resolution==="rejected"&&typed.length<3){setError("Add a short reason before rejecting this request.");return;}
    const responseNote=typed||(resolution==="approved"?"Approved by CEO from Project Operating System.":"");
    setBusyApproval(approval.id);setError("");setNotice(resolution==="approved"?"Authorizing workstream…":"Rejecting workstream…");
    try{
      const response=await fetch("/api/projects/live",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,approvalId:approval.id,resolution,responseNote})});
      const result=await response.json() as {ok?:boolean;error?:string;taskStatus?:string};
      if(!response.ok||!result.ok)throw new Error(result.error||"Approval could not be resolved.");
      setNotes(current=>{const next={...current};delete next[approval.id];return next;});
      setNotice(resolution==="approved"?"Approved. The affected workstream is queued to continue.":"Rejected. The affected workstream is blocked; unrelated work continues.");
      await load();
      window.setTimeout(()=>setNotice(""),4500);
    }catch(e){setError(e instanceof Error?e.message:"Approval could not be resolved.");setNotice("");}
    finally{setBusyApproval(null);}
  };

  const status=(data?.execution?.status??initialStatus).toLowerCase();
  const isExecutionOpen=status==="running"||status==="queued";
  const counts=data?.counts??{running:0,queued:0,waitingApproval:0,waitingOther:0,completed:0,failed:0,total:0};
  const activeAgents=(data?.agents??[]).filter(agent=>agent.status==="active");
  const completion=data?.progressSnapshot?.progressPercent??(counts.total?Math.round((counts.completed/counts.total)*100):0);
  const hasLiveWork=counts.running>0;
  const latestActivity=data?.activity?.[0];
  const visibleTasks=(data?.tasks??[]).filter(t=>["running","retrying","queued","waiting_for_approval"].includes(t.status)).slice(0,7);
  const neuralNodes=useMemo(()=>[
    {name:"INTAKE",meta:`${counts.total} missions`,hot:hasLiveWork},
    {name:"AGENT SWARM",meta:`${activeAgents.length} specialists`,hot:hasLiveWork&&activeAgents.length>0},
    {name:"INFERENCE",meta:`${counts.running} executing`,hot:counts.running>0},
    {name:"QUEUE",meta:`${counts.queued} pending`,hot:counts.queued>0},
    {name:"HUMAN GATE",meta:`${counts.waitingApproval} decisions`,hot:counts.waitingApproval>0},
    {name:"MEMORY",meta:`${counts.completed} outputs`,hot:counts.completed>0},
  ],[counts,activeAgents.length,hasLiveWork]);

  return <section className={`aiRuntime ${hasLiveWork?"isLive":"isIdle"}`} aria-live="polite">
    <style jsx>{`
      .aiRuntime{position:relative;margin-top:18px;border-radius:30px;overflow:hidden;color:#eaf9ff;background:#030711;border:1px solid rgba(96,236,255,.2);box-shadow:0 30px 90px rgba(3,7,17,.38),inset 0 0 80px rgba(24,67,123,.08);isolation:isolate}
      .aiRuntime:before{content:"";position:absolute;inset:-40%;background:conic-gradient(from 0deg at 50% 50%,transparent 0 70%,rgba(0,229,255,.08) 78%,transparent 86%);animation:radar 14s linear infinite;z-index:-2}.aiRuntime:after{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 35%,rgba(38,112,255,.16),transparent 35%),linear-gradient(rgba(73,186,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(73,186,255,.035) 1px,transparent 1px);background-size:auto,28px 28px,28px 28px;z-index:-3}@keyframes radar{to{transform:rotate(360deg)}}
      .scan{position:absolute;inset:0;pointer-events:none;background:linear-gradient(to bottom,transparent 0%,rgba(79,232,255,.06) 49%,rgba(79,232,255,.22) 50%,rgba(79,232,255,.06) 51%,transparent 100%);height:180px;animation:scan 5s ease-in-out infinite;opacity:.75}@keyframes scan{0%,100%{transform:translateY(-180px)}50%{transform:translateY(680px)}}
      .top{display:grid;grid-template-columns:1fr auto;gap:20px;padding:26px 28px 10px;align-items:start}.kicker{display:flex;align-items:center;gap:10px;font:800 11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.18em;color:#67e8ff}.hex{width:24px;height:24px;display:grid;place-items:center;clip-path:polygon(25% 6%,75% 6%,100% 50%,75% 94%,25% 94%,0 50%);background:linear-gradient(135deg,#2ce6ff,#725cff);color:#03111b;font-size:11px}.top h2{font-size:29px;margin:8px 0 7px;letter-spacing:-.025em}.sub{color:#91a9c3;max-width:790px;font-size:13px;line-height:1.55}.live{display:flex;align-items:center;gap:9px;padding:10px 13px;border:1px solid rgba(83,255,197,.28);background:rgba(21,91,76,.18);border-radius:999px;font:800 11px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;color:#9effdb}.live i{width:8px;height:8px;border-radius:50%;background:#50ffc2;box-shadow:0 0 0 0 rgba(80,255,194,.55);animation:ping 1.5s infinite}.isIdle .live{color:#9aaabd;border-color:rgba(160,175,190,.16);background:rgba(90,100,115,.08)}.isIdle .live i{background:#718096;animation:none;box-shadow:none}@keyframes ping{70%{box-shadow:0 0 0 12px rgba(80,255,194,0)}}
      .console{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(310px,.75fr);gap:16px;padding:16px 28px 20px}.neural{position:relative;min-height:460px;border-radius:23px;overflow:hidden;border:1px solid rgba(104,215,255,.13);background:radial-gradient(circle at center,rgba(36,91,179,.18),rgba(3,9,20,.74) 47%,rgba(1,5,12,.92));box-shadow:inset 0 0 55px rgba(0,0,0,.5)}
      .neural:before{content:"NEURAL ORCHESTRATION MESH";position:absolute;left:17px;top:15px;font:700 9px ui-monospace,monospace;letter-spacing:.18em;color:rgba(124,213,255,.58)}
      .brain{position:absolute;left:50%;top:50%;width:176px;height:176px;transform:translate(-50%,-50%);border-radius:50%;display:grid;place-items:center;z-index:4}.brain:before,.brain:after{content:"";position:absolute;border-radius:50%;inset:0;border:1px solid rgba(76,221,255,.4);box-shadow:0 0 45px rgba(0,202,255,.18),inset 0 0 45px rgba(64,58,255,.15)}.brain:before{animation:orbit 9s linear infinite}.brain:after{inset:17px;border-style:dashed;border-color:rgba(133,101,255,.48);animation:orbitReverse 6s linear infinite}.core{width:103px;height:103px;border-radius:50%;display:grid;place-items:center;text-align:center;background:radial-gradient(circle at 38% 30%,#173c7e,#091c40 55%,#030914);border:1px solid rgba(123,232,255,.42);box-shadow:0 0 42px rgba(42,194,255,.26);position:relative;z-index:3}.isLive .core{animation:breathe 2.2s ease-in-out infinite}.core strong{font:900 16px ui-monospace,monospace;color:#dffbff}.core span{display:block;margin-top:5px;font:700 9px ui-monospace,monospace;letter-spacing:.1em;color:#69d9ff}@keyframes breathe{50%{transform:scale(1.055);box-shadow:0 0 65px rgba(42,194,255,.42)}}@keyframes orbit{to{transform:rotate(360deg)}}@keyframes orbitReverse{to{transform:rotate(-360deg)}}
      .sat{position:absolute;width:142px;padding:11px 12px 10px;border-radius:13px;background:rgba(4,15,31,.85);border:1px solid rgba(100,201,255,.14);backdrop-filter:blur(12px);z-index:6;box-shadow:0 10px 30px rgba(0,0,0,.22)}.sat:before{content:"";position:absolute;left:-1px;top:9px;bottom:9px;width:2px;border-radius:2px;background:#41506a}.sat.hot:before{background:linear-gradient(#3ce5ff,#6f5cff,#4bffbd);box-shadow:0 0 10px #38dfff}.sat b{display:block;font:850 10px ui-monospace,monospace;letter-spacing:.08em;color:#c9f7ff}.sat small{display:block;margin-top:5px;font:600 10px ui-monospace,monospace;color:#7e9ab4}.sat.hot{border-color:rgba(69,217,255,.28)}.s0{left:7%;top:15%}.s1{right:7%;top:15%}.s2{left:4%;top:46%}.s3{right:4%;top:46%}.s4{left:10%;bottom:12%}.s5{right:10%;bottom:12%}
      .wire{position:absolute;left:50%;top:50%;width:38%;height:1px;transform-origin:0 0;background:linear-gradient(90deg,rgba(64,219,255,.55),rgba(111,89,255,.1));z-index:2;overflow:visible}.wire:after{content:"";position:absolute;top:-2px;width:5px;height:5px;border-radius:50%;background:#8bf4ff;box-shadow:0 0 12px #54ddff;animation:packet 2.4s linear infinite}.w0{transform:rotate(208deg)}.w1{transform:rotate(332deg)}.w2{transform:rotate(180deg)}.w3{transform:rotate(0deg)}.w4{transform:rotate(145deg)}.w5{transform:rotate(35deg)}@keyframes packet{from{left:0}to{left:100%}}.isIdle .wire:after{animation-play-state:paused;opacity:.25}
      .orbitDot{position:absolute;left:50%;top:50%;width:7px;height:7px;margin:-3px;border-radius:50%;background:#6ae9ff;box-shadow:0 0 12px #6ae9ff;animation:orbitDot 5s linear infinite;transform-origin:0 0}@keyframes orbitDot{0%{transform:rotate(0deg) translateX(118px)}100%{transform:rotate(360deg) translateX(118px)}}
      .telemetry{display:flex;flex-direction:column;gap:11px}.hud{border:1px solid rgba(101,213,255,.12);border-radius:18px;background:rgba(5,14,29,.76);padding:15px;box-shadow:inset 0 0 24px rgba(45,130,255,.035)}.hudTitle{font:800 9px ui-monospace,monospace;letter-spacing:.15em;color:#5fdcff;margin-bottom:11px}.metricGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.metric{padding:11px;border-radius:12px;background:rgba(255,255,255,.026);border:1px solid rgba(255,255,255,.055)}.metric span{font:650 9px ui-monospace,monospace;color:#6f879f;text-transform:uppercase}.metric strong{display:block;font:900 25px ui-monospace,monospace;color:#ecfbff;margin-top:3px}.metric.em strong{color:#ffcf7a}.metric.go strong{color:#70f0c1}.bar{height:6px;border-radius:999px;background:#101d2d;overflow:hidden;margin-top:9px}.fill{height:100%;background:linear-gradient(90deg,#665bff,#22dfff,#54f1b5);box-shadow:0 0 12px rgba(44,223,255,.45);transition:width .5s ease}.activity strong{font-size:12px;color:#d8f5ff}.activity p{margin:5px 0 0;color:#7f99b2;font-size:11px;line-height:1.5}.agentRow{display:flex;gap:8px;align-items:center;margin-top:8px}.avatar{width:29px;height:29px;display:grid;place-items:center;border-radius:8px;background:linear-gradient(135deg,#153c72,#241e59);border:1px solid rgba(103,213,255,.2);font:900 9px ui-monospace,monospace;color:#92ecff}.agentRow div:last-child{min-width:0}.agentRow b{font-size:11px;color:#c9e8f2}.agentRow small{display:block;font:600 9px ui-monospace,monospace;color:#648096;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .tasks{padding:0 28px 20px}.tasksHead,.approvalHead{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.tasksHead h3,.approvalHead h3{margin:0;font-size:16px}.micro{font:700 9px ui-monospace,monospace;letter-spacing:.12em;color:#5b819d}.taskRail{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:9px}.task{position:relative;padding:12px;border-radius:14px;background:rgba(5,16,31,.74);border:1px solid rgba(94,176,220,.11);overflow:hidden}.task:before{content:"";position:absolute;left:0;top:0;bottom:0;width:2px;background:#2c4056}.task.running:before{background:#4ff2c1;box-shadow:0 0 12px #4ff2c1}.task.retrying:before{background:#ffb14d}.task.waiting_for_approval:before{background:#d281ff}.task b{display:block;font-size:11px;color:#d8edf5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.task span{display:block;margin-top:5px;font:700 9px ui-monospace,monospace;color:#69869e;text-transform:uppercase}
      .approvals{padding:0 28px 27px}.approvalGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(295px,1fr));gap:10px}.approval{position:relative;padding:15px;border-radius:17px;background:linear-gradient(145deg,rgba(38,22,57,.64),rgba(7,17,32,.82));border:1px solid rgba(194,112,255,.2);box-shadow:inset 0 0 26px rgba(162,69,255,.035)}.approval.processing{opacity:.7}.approvalTop{display:flex;gap:10px;justify-content:space-between}.approvalTop b{font-size:12px;line-height:1.4;color:#f2e8ff}.risk{flex:none;font:800 9px ui-monospace,monospace;padding:5px 7px;border-radius:999px;color:#ffd292;background:rgba(255,168,54,.09);border:1px solid rgba(255,168,54,.15)}.approval p{font-size:11px;line-height:1.5;color:#8ea3ba}.note{box-sizing:border-box;width:100%;min-height:56px;padding:10px;border-radius:11px;background:rgba(1,8,18,.7);color:#e9faff;border:1px solid rgba(92,175,220,.12);resize:vertical;outline:none}.note:focus{border-color:rgba(70,221,255,.42);box-shadow:0 0 0 3px rgba(46,194,255,.06)}.buttons{display:flex;gap:8px;margin-top:9px}.buttons button{position:relative;border:0;border-radius:10px;padding:9px 12px;font-weight:850;font-size:11px;cursor:pointer;transition:.16s ease}.approve{background:linear-gradient(135deg,#43e8c0,#60f0a5);color:#04221a}.reject{background:rgba(255,255,255,.055);color:#d8e7f4;border:1px solid rgba(255,255,255,.08)!important}.buttons button:hover:not(:disabled){transform:translateY(-1px);filter:brightness(1.06)}.buttons button:disabled{opacity:.48;cursor:progress}.approval.processing button:first-of-type:after{content:"";position:absolute;inset:0;border-radius:10px;background:linear-gradient(90deg,transparent,rgba(255,255,255,.35),transparent);animation:shimmer 1s infinite}@keyframes shimmer{from{transform:translateX(-100%)}to{transform:translateX(100%)}}
      .message{margin:0 28px 14px;padding:10px 12px;border-radius:11px;font-size:11px}.error{background:rgba(255,75,98,.08);border:1px solid rgba(255,75,98,.2);color:#ffc6cf}.notice{background:rgba(55,230,184,.08);border:1px solid rgba(55,230,184,.18);color:#a7ffe3}.empty{font:600 10px ui-monospace,monospace;color:#617e95;padding:8px 0}
      @media(max-width:950px){.console{grid-template-columns:1fr}.neural{min-height:480px}.top{grid-template-columns:1fr}.live{width:max-content}}@media(max-width:650px){.top,.console,.tasks,.approvals{padding-left:16px;padding-right:16px}.neural{min-height:560px}.sat{width:112px}.s0{left:3%;top:12%}.s1{right:3%;top:12%}.s2{left:2%;top:40%}.s3{right:2%;top:40%}.s4{left:4%;bottom:9%}.s5{right:4%;bottom:9%}.brain{width:142px;height:142px}.core{width:88px;height:88px}.taskRail{grid-template-columns:1fr 1fr}}
      @media(prefers-reduced-motion:reduce){.aiRuntime:before,.scan,.live i,.brain:before,.brain:after,.core,.wire:after,.orbitDot,.approval.processing button:first-of-type:after{animation:none!important}}
    `}</style>
    <div className="scan"/>
    <div className="top"><div><div className="kicker"><span className="hex">AI</span> RYTHM AUTONOMOUS PROJECT INTELLIGENCE</div><h2>{hasLiveWork?"Agentic execution network online":isExecutionOpen?"Execution queued · awaiting active work":"AI project runtime standby"}</h2><div className="sub">A live neural-style operations surface for autonomous agents, reasoning queues, human governance gates and verified outputs. Visual motion is symbolic; operational states are real and refresh every 5 seconds.</div></div><div className="live"><i/>{hasLiveWork?`EXECUTION ${data?.execution?.execution_no??""} · ACTIVE`:statusLabel(status).toUpperCase()}</div></div>
    {error?<div className="message error">{error}</div>:null}{notice?<div className="message notice">{notice}</div>:null}
    <div className="console"><div className="neural">{neuralNodes.map((node,index)=><div className={`sat s${index} ${node.hot?"hot":""}`} key={node.name}><b>{node.name}</b><small>{node.meta}</small></div>)}{[0,1,2,3,4,5].map(i=><div key={i} className={`wire w${i}`}/>)}<div className="orbitDot"/><div className="brain"><div className="core"><div><strong>RYTHM</strong><span>{hasLiveWork?"COGNITIVE CORE":"STANDBY"}</span></div></div></div></div><div className="telemetry"><div className="hud"><div className="hudTitle">REAL-TIME TELEMETRY</div><div className="metricGrid"><div className="metric go"><span>Running</span><strong>{counts.running}</strong></div><div className="metric"><span>Queued</span><strong>{counts.queued}</strong></div><div className="metric em"><span>CEO gates</span><strong>{counts.waitingApproval}</strong></div><div className="metric"><span>Outputs</span><strong>{counts.completed}</strong></div></div></div><div className="hud"><div className="hudTitle">MISSION COMPLETION · {completion}%</div><div className="bar"><div className="fill" style={{width:`${completion}%`}}/></div><div className="activity" style={{marginTop:12}}><strong>Runtime heartbeat</strong><p>{since(data?.execution?.last_heartbeat_at??data?.project?.last_heartbeat_at)} ago · server-side durable execution</p></div></div><div className="hud"><div className="hudTitle">ACTIVE AI SPECIALISTS</div>{activeAgents.slice(0,5).map(agent=>{const a=agent.agents;const name=a?.display_name||a?.name||agent.assignment_role;return <div className="agentRow" key={agent.agent_id}><div className="avatar">{initials(name)}</div><div><b>{name}</b><small>{a?.agent_code||agent.assignment_role}</small></div></div>})}{!activeAgents.length?<div className="empty">No active specialist assignment reported.</div>:null}</div><div className="hud"><div className="hudTitle">LATEST COGNITIVE EVENT</div><div className="activity"><strong>{latestActivity?.headline||"Awaiting runtime event"}</strong><p>{latestActivity?.detail||"The event stream will update as agents reason, execute and hand off work."}</p></div></div></div></div>
    <div className="tasks"><div className="tasksHead"><h3>Agent workstreams</h3><span className="micro">LIVE EXECUTION GRAPH</span></div><div className="taskRail">{visibleTasks.length?visibleTasks.map(task=><div className={`task ${task.status}`} key={task.id}><b>{task.title}</b><span>{statusLabel(task.status)} · {task.agents?.agent_code||"unassigned"}</span></div>):<div className="empty">No active or queued workstreams.</div>}</div></div>
    <div className="approvals"><div className="approvalHead"><h3>Human authority gates</h3><span className="micro">{data?.approvals?.length??0} CEO DECISIONS PENDING</span></div>{data?.approvals?.length?<div className="approvalGrid">{data.approvals.map(approval=><div className={`approval ${busyApproval===approval.id?"processing":""}`} key={approval.id}><div className="approvalTop"><b>{approval.title}</b><span className="risk">{approval.risk_level}</span></div><p>{approval.summary}</p><textarea className="note" value={notes[approval.id]??""} onChange={e=>setNotes(current=>({...current,[approval.id]:e.target.value}))} placeholder="Optional approval note · rejection requires a reason" disabled={busyApproval===approval.id}/><div className="buttons"><button className="approve" data-processing-label="Authorizing workstream" disabled={busyApproval!==null} onClick={()=>void resolve(approval,"approved")}>{busyApproval===approval.id?"Authorizing…":"Approve & continue"}</button><button className="reject" data-processing-label="Rejecting workstream" disabled={busyApproval!==null} onClick={()=>void resolve(approval,"rejected")}>{busyApproval===approval.id?"Please wait…":"Reject"}</button></div></div>)}</div>:<div className="empty">No human decision is blocking a workstream. Independent agents continue autonomously.</div>}</div>
  </section>;
}
