"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Clarification={id:string;question:string;reason:string;input_type:string;options:unknown[]};
type Connection={id:string;provider_key:string;display_name:string;status:string};
type Capability={provider_key:string;capability_key:string;description:string|null;risk_level:string;default_approval_mode:string};
type Scope={id:string;status:string}|null;
type Props={projectId:string;projectStatus:string;clarifications:Clarification[];connections:Connection[];capabilities:Capability[];latestScope:Scope;};

async function post(endpoint:string,body:unknown){const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as {ok?:boolean;error?:string};if(!r.ok||!d.ok)throw new Error(d.error||"Request failed.");return d;}

export function ProjectGovernanceControls({projectId,projectStatus,clarifications,connections,capabilities,latestScope}:Props){
  const router=useRouter();const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState("");
  const run=async(key:string,fn:()=>Promise<unknown>)=>{setBusy(key);setNotice("");try{await fn();setNotice("Saved. Project state has been updated.");router.refresh();}catch(e){setNotice(e instanceof Error?e.message:"Request failed.");}finally{setBusy(null);}};
  return <>
    {clarifications.length?<section className="panel" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">Clarification</p><h2>Only material questions</h2></div><span className="pill">{clarifications.length} open</span></div><div className="data-list">{clarifications.map(item=><form key={item.id} onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(`clarify-${item.id}`,()=>post("/api/projects/control",{projectId,action:"answer_clarification",clarificationId:item.id,answer:String(form.get("answer")??"")}));}} className="data-row" style={{display:"block"}}><strong>{item.question}</strong><span style={{display:"block",margin:"6px 0 10px"}}>{item.reason}</span>{Array.isArray(item.options)&&item.options.length?<select name="answer" required>{item.options.map((option,index)=><option value={String(option)} key={index}>{String(option)}</option>)}</select>:<input name="answer" required placeholder="Your answer"/>}<button disabled={busy!==null} style={{marginLeft:10}}>{busy===`clarify-${item.id}`?"Saving…":"Save answer"}</button></form>)}</div></section>:null}

    <section className="panel" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">Connections</p><h2>Attach a specific resource</h2></div><span className="pill">Least privilege</span></div><p className="subtitle">Company-level accounts stay reusable. This grants this project only the resource and capabilities you confirm.</p>{connections.filter(c=>c.status==="connected").length?<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);const integrationId=String(form.get("integrationId")??"");const selected=connections.find(c=>c.id===integrationId);const caps=form.getAll("capabilities").map(String);void run("connection",()=>post("/api/projects/connections",{projectId,integrationId,resourceType:selected?.provider_key,resourceRef:String(form.get("resourceRef")??""),displayName:String(form.get("displayName")??""),capabilities:caps}));}} className="auth-form"><label>Connected account<select name="integrationId" required>{connections.filter(c=>c.status==="connected").map(c=><option key={c.id} value={c.id}>{c.display_name} · {c.provider_key}</option>)}</select></label><label>Specific resource / identifier<input name="resourceRef" required placeholder="Repository, property, project or resource ID"/></label><label>Display name<input name="displayName" placeholder="Production repository"/></label><details><summary style={{cursor:"pointer"}}>Capabilities</summary><div style={{display:"grid",gap:8,marginTop:10}}>{capabilities.map(cap=><label key={`${cap.provider_key}-${cap.capability_key}`} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" name="capabilities" value={cap.capability_key}/><span><strong>{cap.capability_key}</strong> · {cap.risk_level} · {cap.default_approval_mode}</span></label>)}</div></details><button disabled={busy!==null}>{busy==="connection"?"Attaching…":"Attach to Project"}</button></form>:<p className="security-note">No connected company accounts are available yet. Connect an integration first, then attach its specific resource here.</p>}</section>

    <section className="panel" style={{marginTop:18}}><div className="panel-heading"><div><p className="label">Human CEO Authority</p><h2>Project Control</h2></div><span className="pill">{projectStatus.replaceAll("_"," ")}</span></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{latestScope&&latestScope.status!=="approved"?<button disabled={busy!==null} onClick={()=>void run("scope",()=>post("/api/projects/control",{projectId,action:"approve_scope",scopeId:latestScope.id}))}>{busy==="scope"?"Approving…":"Approve Scope"}</button>:null}{projectStatus==="active"?<button disabled={busy!==null} onClick={()=>void run("pause",()=>post("/api/projects/control",{projectId,action:"pause"}))}>Pause Project</button>:projectStatus==="on_hold"?<button disabled={busy!==null} onClick={()=>void run("resume",()=>post("/api/projects/control",{projectId,action:"resume"}))}>Resume Project</button>:null}{!["completed","cancelled"].includes(projectStatus)?<button disabled={busy!==null} onClick={()=>{if(confirm("Cancel this project execution? Completed side effects will not be reversed."))void run("cancel",()=>post("/api/projects/control",{projectId,action:"cancel"}));}}>Cancel Project</button>:null}</div>{notice?<p className="security-note" role="status">{notice}</p>:null}</section>
  </>;
}
